### ISSUE TITLE
Add Table tags

### ISSUE THREAD

**Issue by kenwheeler** [FormidableLabs/spectacle#10]
soon

**Comment by bebraw** [comment]
FYI, I have an implementation at https://github.com/survivejs/frontend-in-2015/commit/31cb3378059829c2804e96a31668090759e2d29f . I'm not sure if that's what was on your mind but it works. Note that `Appear` is not supported yet. I'll probably wait your version for that.

**Comment by bebraw** [comment]
@kenwheeler Are you going to include some kind of Table tags to the lib?

**Comment by kenwheeler** [comment]
Yes

**Comment by bebraw** [comment]
@kenwheeler Any idea what happened to this? Are you going to include `Table` at some point? Need a PR?

**Comment by kenwheeler** [comment]
Please
