### ISSUE TITLE
Should Cite support a style prop?

### ISSUE THREAD

**Issue by pedrottimark** [FormidableLabs/spectacle#100]
Most components support a style prop, although it is undocumented.

For example, here is an excerpt from Quote:

      <span style={[this.context.styles.components.quote, this.getStyles(), this.props.style]}>
        {this.props.children}
      </span>

Quote.propTypes = {
  children: PropTypes.node,
  style: PropTypes.object
};

Cite supports theme and Base style props, but not a style prop:

      <cite style={[this.context.styles.components.cite, this.getStyles()]}>
        - {this.props.children}
      </cite>

Cite.propTypes = {
  children: PropTypes.node
};

**Comment by pedrottimark** [comment]
One zero zero, what an honor. But maybe you want to throw some stale sea weed at me, ha ha?

**Comment by kenwheeler** [comment]
It should
