### ISSUE TITLE
Make Compatible With Powerpoint

### ISSUE THREAD

**Issue by shabegom** [FormidableLabs/spectacle#1003]
### Description

I would like to create spectacle slideshows, but I want to make them in Powerpoint by Microsoft.

### Proposal

Add a button in Powerpoint called "Spectalize", preferably it would also have an anthropomorphic paperclip pop up and shoot confetti all over the screen.

### Links / References

[Powerpoint by Microsoft](https://en.wikipedia.org/wiki/April_Fools%27_Day)

**Comment by tptee** [comment]
I too want to make spectacle slideshows in Powerpoint, but my business requires it to sync to Sharepoint. We need the power to share the points! Where are the maintainers??????
