### ISSUE TITLE
Lander site: Update Formidable logo on last slide

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/spectacle#101]
http://projects.formidablelabs.com/spectacle/#/9 is using our old branding:

<img width="922" alt="screen shot 2015-11-17 at 5 22 17 pm" src="https://cloud.githubusercontent.com/assets/794843/11230009/ded57ac6-8d4f-11e5-91b1-4e41a2b45326.png">

**Comment by kenwheeler** [comment]
Noted

**Comment by kenwheeler** [comment]
I'll ping you back channel tomorrow about assets

**Comment by kenwheeler** [comment]
Fixed on master
