### ISSUE TITLE
Chore: Audit prod dependencies

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/spectacle#1014]
We should audit all our prod deps for actual usage. Discovered today that we're not using:

- [ ] `marksy`: https://github.com/FormidableLabs/spectacle/search?q=marksy

**Comment by sneakers-the-rat** [comment]
`depcheck` says:

```
Unused dependencies
* broadcastchannel-polyfill
* dedent
* marksy
* normalize-newline
* prism-react-renderer

Unused devDependencies
* babel-eslint
* babel-plugin-transform-jsx-to-htm
* typescript
* webpack-cli
```

**Comment by ryan-roemer** [comment]
Thanks @sneakers-the-rat 

Some random notes:

- `prism-react-render` is a real prod dep at https://github.com/FormidableLabs/spectacle/blob/main/docs/src/components/mdx.js#L8
- `babel-plugin-transform-jsx-to-htm`: https://github.com/FormidableLabs/spectacle/blob/75052e61bedabf5ed9965506bb1fb7e82112782f/scripts/one-page.js#L36
- `webpack-cli` provides `webpack` CLI script
- I think `babel-eslint` is needed for `eslint` commands

**Comment by todortotev** [comment]
@ryan-roemer mind if I try helping?

**Comment by Himanshu2561** [comment]
@ryan-roemer , I would also like to help !
