### ISSUE TITLE
Question regarding progress dots

### ISSUE THREAD

**Issue by alvarezGarciaMarcos** [FormidableLabs/spectacle#1046]
### Question

I have installed the package with _yarn_ and started a presentation with the _spectacle-boilerplate_, and I a getting some weird behavior, that I've also seen in the demo presentation. The _Full screen_ button and the progress dots are animated within the slide. Shouldn't they be static in the page to show the progress of the presentation? Am I missing some configuration?

Thank you.

### Background Info/Attempts

I've used the sample generated by the _spectacle-boilerplate_ command.

**Comment by fritz-c** [comment]
I noticed that with older versions, but it appears to be fixed in v9.5.1, at least.
https://codesandbox.io/s/simple-spectacle-example-lq1tbm
