### ISSUE TITLE
Text wrapping

### ISSUE THREAD

**Issue by dav1d-wright** [FormidableLabs/spectacle#1050]
### Question
Hi, I have been unsuccessfully trying to find out what components or properties to use in order to wrap text within a Text component. Ideally I would like to use the left half of a slide for text, and the right half for an image. Unfortunately though, the text sometimes overlaps to the second half of the slide.

I would be greatful for any hints to achieve this.

### Background Info/Attempts
I have tried Tables, Grids, as well as Flexboxes. I assume this should be possible using some of these components, but I've most likely not found the corresponding properties.

The closest I've come is by using the following code:

```jsx
      <Slide id="optical-flow">
        <Heading>Optical Flow</Heading>
        <Table>
          <TableRow>
            <TableCell backgroundColor="primary" maxWidth="50px">
              <Text color="white">asdfasdfasdfasdfasdfasdfasdfasdasdasdfasdfasdasdasfas</Text>
            </TableCell>
            <TableCell backgroundColor="secondary" maxWidth="50px">
              <Text color="red">asdfasdfasdfasdfasdfasdfasdfasdasdasdfasdfasdasdasfas</Text>
            </TableCell>
          </TableRow>
        </Table>
      </Slide>
```

With the result:

![Screenshot 2021-07-23 at 14 08 21](https://user-images.githubusercontent.com/3441341/126779702-73a5b549-b309-4ce5-aecc-4b6341640ea9.png)

**Comment by AbhishekJamhoriya** [comment]
@dav1d-wright can i work on this issue.

**Comment by dav1d-wright** [comment]
@AbhishekJamhoriya that would be great for me, but I have no ties to FormidableLabs :)

**Comment by jrwJunior** [comment]
Foo

**Comment by fritz-c** [comment]
There is a CSS property, [`overflow-wrap`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap) that is relevant to your issue. Words that are too long will not be broken by default. You can set it to `break-word` to get the behavior you describe.

Demo: https://codesandbox.io/s/long-text-wrapping-spectacle-okpjbj
