### ISSUE TITLE
Demo/example doesn't work in latest Chrome

### ISSUE THREAD

**Issue by Nezteb** [FormidableLabs/spectacle#1058]
### Prerequisites

- [X] I've searched open [issues](https://www.github.com/FormidableLabs/spectacle/issues) to make sure I'm not opening a duplicate issue
- [X] I have read through the [docs](https://www.formidable.com/open-source/spectacle/docs) before asking a question
- [X] I am using the latest version of Spectacle

### Describe Your Environment

What browser are you using?
- Chrome 92.0.4515.159 (Official Build) (x86_64)

What machine are you on?
- macOS Big Sur 11.5.2

### Describe the Problem

1. Open https://raw.githack.com/FormidableLabs/spectacle/main/examples/one-page.html
2. See blank white page and error in the console: <img width="625" alt="Screen Shot 2021-08-20 at 12 44 48 PM" src="https://user-images.githubusercontent.com/3588798/130273633-e21c3d42-0fb2-40dc-a028-591398161325.png">
3. Demo works fine embedded on the docs page: https://formidable.com/open-source/spectacle/

**Expected behavior:** [What you expect to happen]

Demo link in the `README` should work.

**Actual behavior:** [What actually happens]

Demo link in the `README` doesn't work.

**Comment by ryan-roemer** [comment]
Thanks @Nezteb ! Yep, one-page is in "dev mode" and we need to revert that to real live version. I'll get a bugfix PR up soon.

**Comment by ryan-roemer** [comment]
@carlos-kelly The latest one-page.html works with local `dist/**.js` but _not_ with published spectacle for something related to fragments. Are we behind in publishing?
