### ISSUE TITLE
Pacman progress a solid dot without moving jaws

### ISSUE THREAD

**Issue by pedrottimark** [FormidableLabs/spectacle#106]
Apparent regression in radium 0.14.2
It works in newer 0.15.0 and 0.15.1 as in original 0.13.2

**Comment by adamdicarlo** [comment]
Seeing this after cloning spectacle-boilerplate yesterday. `npm ls` tells me I have Spectacle 1.0.5 which uses Radium 0.17.1.

Looks like pacman's issue has something to do with this:

`animation:[object Object] 0.12s linear 10 alternate both`

**Comment by BenDiuguid** [comment]
This works on a clean install of [Spectacle Boilerplate](https://github.com/FormidableLabs/spectacle-boilerplate/)

with npm -v : 3.9.5 and node -v : 6.2.2

👍

**Comment by kenwheeler** [comment]
Thanks for confirming, closing this out
