### ISSUE TITLE
Type definition for CodePane's highlightRanges parameter is incomplete

### ISSUE THREAD

**Issue by neobrain** [FormidableLabs/spectacle#1062]
### Describe the Problem

The [docs for CodePane](https://formidable.com/open-source/spectacle/docs/api-reference/#code-pane) allow for passing an array of arrays for the `highlightRanges` parameter, as indicated by the example `[[6, 8], [10, 15]]`. However, this usage pattern doesn't compile with the current typescript definition `highlightRanges?: number | number[]`.

What's missing is another alternative: `highlightRanges` can also be a `number[][]`

### Additional Information

Is it okay to submit a PR for simple changes like this or do you prefer issue reports?

**Comment by neobrain** [comment]
I reflected about this some more, and actually the type can be refined even more: Since only two-element arrays or single-element entries are allowed, the `number[]` alternative could be replaced by `(number | [number, number])[]`.

This would allow `highlightRanges={[[1,5], [7,11], 13]}` and `highlightRanges={[[13,15],17]}`, but not `highlightRanges={[[1,5,3]]}` and neither `highlightRanges={[[13]]}`.

**Comment by SebastiaanNijland** [comment]
I think https://github.com/FormidableLabs/spectacle/pull/991 addresses this issue.

**Comment by neobrain** [comment]
> I think #991 addresses this issue.

Yup! Let's hope it gets merged at some point :)

**Comment by neobrain** [comment]
#1070 also addressed this and has been merged :)
