### ISSUE TITLE
Bug: Export Mode doesn't work in Firefox.

### ISSUE THREAD

**Issue by DanielBadura** [FormidableLabs/spectacle#1077]
### Question

Hello 👋 

I'm building some slides right now and wanted to look an a PDF export but oddly only the first Slide is visible but the PDF has the full 121 slides as pages but they are all white. I looked into similiar issues where ppl said imported slides have some issue and moved all CustomSlides which were imported into the `App.tsx` but that did produce a different result. I used Firefox to generate the PDF.

TL;DR: Chrome is working Firefox not.

Is Firefox not supported or is this a bug?

### Background Info/Attempts

I used:
* Firefox 94.0.1 (64Bit) as a browser
* react ^17.0.2
* spectacle ^8.4.1
* typescript ^4.1.2

Here a screen of the PDF generation preview:
![Bildschirmfoto 2021-11-26 um 12 46 09](https://user-images.githubusercontent.com/2017762/143576283-e3b9490b-9eb7-414b-9951-98d0926896d8.png)

You can see, only the first slide gets into the PDF and even that slides is a little bit off.

After that i tried this simple example:
```
const theme = {
    colors: {
        primary: '#333333',
        secondary: '#39bbcf',
        tertiary: '#efefef',
        quaternary: '#efefef',
        grey: '#ddd',
        red: '#c92a2a'
    },
    fonts: {
        primary: 'Ubuntu',
    }
};

function App() {
  return (
      <Deck theme={theme} transition={{from: {}, leave: {}, enter: {}}}>
          <Slide backgroundColor="primary">
              <FlexBox height="100%">
                  <Heading size={3} lineHeight={1} color="secondary">
                      Slide 1
                  </Heading>
              </FlexBox>
          </Slide>
          <Slide backgroundColor="primary">
              <FlexBox height="100%">
                  <Heading size={3} lineHeight={1} color="secondary">
                      Slide 2
                  </Heading>
              </FlexBox>
          </Slide>
      </Deck>
  );
}
```
With this i get the same result, only first slide and still off:
![Bildschirmfoto 2021-11-26 um 12 51 54](https://user-images.githubusercontent.com/2017762/143576914-f362e5bd-4d5b-44ae-ad60-8d533813a446.png)

I'll downloaded chrome and tried all steps above backwards and everything worked:
![Bildschirmfoto 2021-11-26 um 13 03 04](https://user-images.githubusercontent.com/2017762/143578235-d75539ed-5119-4635-9c18-df95028f67a5.png)

**Comment by ryan-roemer** [comment]
Confirmed with https://raw.githack.com/FormidableLabs/spectacle/main/examples/one-page.html?exportMode=true on FF 98.0 -- first page visible, blank pages in print dialog for everything else.
