### ISSUE TITLE
Does Spectacle Work with webpack v5?

### ISSUE THREAD

**Issue by RachitKeertiDas** [FormidableLabs/spectacle#1080]
### Question

I tried to run the `create-react-app` method of using Spectacle as a standard react app, however, this failed using `create-react-app` v5.0.0 and webpack v5. Is there any workaround for this?

### Background Info/Attempts

I used `create-react-app` to create a standard react app, installed Spectacle v8.5, and used the standard boilerplate code as provided in the official documentation.

The following error message shows up on running `npm run start`:
```
Compiled with problems:

ERROR in ./node_modules/mdast-util-assert/index.js 3:13-30

Module not found: Error: Can't resolve 'assert' in '/home/rachit/GitRepos/ug_orientation_2k21/node_modules/mdast-util-assert'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
	- install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "assert": false }


ERROR in ./node_modules/unist-util-assert/index.js 3:13-30

Module not found: Error: Can't resolve 'assert' in '/home/rachit/GitRepos/ug_orientation_2k21/node_modules/unist-util-assert'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
	- install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "assert": false }
```

**Comment by artcoded-net** [comment]
Hi, as a workaround, installing the 'assert' package as it suggests in the error message, did solve the issue for me

**Comment by ryan-roemer** [comment]
Hi Folks -- I've added https://github.com/FormidableLabs/spectacle/issues/1081 with a list of the work to update webpack to v5. i don't think we'll encounter any big issues other than missing node polyfills in v5 that we'll have to add some config for.

**Comment by RachitKeertiDas** [comment]
Yup, I can confirm adding the `assert` package gets rid of the error and it works as intended. Thanks for the suggestion!

Closing the issue as a To-Do List for all the required changes for webpack v5 has already been created in #1081.

Thank you for all the help again!
