### ISSUE TITLE
Export Mode is broken

### ISSUE THREAD

**Issue by gpichot** [FormidableLabs/spectacle#1097]
### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://www.github.com/FormidableLabs/spectacle/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the [docs](https://www.formidable.com/open-source/spectacle/docs) before asking a question
- [x] I am using the latest version of Spectacle

What version of Spectacle are you using? (can be found by running `npm list spectacle`)
`spectacle@9.0.0`
What version of React are you using? (can be found by running `npm list react`)
`react@17.0.2`
What browser are you using?
`chrome`
What machine are you on?
`macOS M1`

### Describe the Problem

Export mode is not working on main branch (and on 9.0.0).
For instance :
https://raw.githack.com/FormidableLabs/spectacle/main/examples/one-page.html?slideIndex=0&stepIndex=0&exportMode=true 

Error is : Cannot read properties of null (reading 'slideIndex')

**Expected behavior:** It should allow me to print my presentation as PDF.

**Actual behavior:** Blank page for now

**Comment by ryan-roemer** [comment]
Thanks for the reproduction @gpichot ! I've confirmed the behavior with this stack trace:

```
react-dom.production.min.js:141 TypeError: Cannot read properties of null (reading 'slideIndex')
    at spectacle.min.js:2:740583
    at Le (react-dom.production.min.js:100:3)
    at yh (react-dom.production.min.js:110:387)
    at Pj (react-dom.production.min.js:235:116)
    at di (react-dom.production.min.js:168:305)
    at Nj (react-dom.production.min.js:168:236)
    at sc (react-dom.production.min.js:168:96)
    at gf (react-dom.production.min.js:162:109)
    at react-dom.production.min.js:73:230
    at unstable_runWithPriority (react.production.min.js:24:26)
```


I didn't dig into the rc-versions for v9, but https://raw.githack.com/FormidableLabs/spectacle/v8.5.0/examples/one-page.html?slideIndex=0&stepIndex=0&exportMode=true works fine.

**Comment by ryan-roemer** [comment]
```js
// src/components/deck/deck.tsx
    useAutoPlay({
      enabled: autoPlay,
      loop: autoPlayLoop,
      interval: autoPlayInterval,
      navigation: {
        skipTo,
        stepForward,
        // activeView is `null` and blows up
        isFinalSlide: activeView.slideIndex === slideIds.length - 1
      }
    });
```

**Comment by ryan-roemer** [comment]
Fixed in `spectacle@9.0.1`

**Comment by gpichot** [comment]
Thanks @ryan-roemer ! I tested and it works now.

On the Export Mode "interactive stepper", I am still spotting some issues :

For instance on https://raw.githack.com/FormidableLabs/spectacle/main/examples/one-page.html?slideIndex=0&stepIndex=0&exportMode=true
- slide 3 is blank (custom background) ;
- slide 4 show an empty slide while there is 3 stepper elements
If you want I can open another issue.

(I can see these issues on the v8.5.0 version too)

**Comment by ryan-roemer** [comment]
Hi @gpichot -- thanks for the feedback. Yeah, if you could open new, separate issues that would be great!

**Comment by gpichot** [comment]
Hi @ryan-roemer I opened two issues related to these issues (references above).
