### ISSUE TITLE
[Export Mode] Animated elements not displayed on slide

### ISSUE THREAD

**Issue by gpichot** [FormidableLabs/spectacle#1099]
### Prerequisites

- [x] I've searched open [issues](https://www.github.com/FormidableLabs/spectacle/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the [docs](https://www.formidable.com/open-source/spectacle/docs) before asking a question
- [x] I am using the latest version of Spectacle

### Describe Your Environment

Can be seen on v8.5.0, main and v9.0.1 (slide 4)
https://raw.githack.com/FormidableLabs/spectacle/main/examples/one-page.html?slideIndex=0&stepIndex=0&exportMode=true
https://raw.githack.com/FormidableLabs/spectacle/v9.0.1/examples/one-page.html?slideIndex=0&stepIndex=0&exportMode=true

### Describe the Problem

Slide with animated elements are displayed without the content of the animated elements.

**Expected behavior:** Either the slide should appear with all animated elements or a slide should be added for each successive animated element.

**Actual behavior:** Slide is displayed without the animated elements.

### Additional Information

As requested https://github.com/FormidableLabs/spectacle/issues/1097 I opening this issue

**Comment by carlos-kelly** [comment]
@gpichot We believe 9.1.0 fixes this, if not please let us know!
