### ISSUE TITLE
[Export Mode] Slide with custom background is blank

### ISSUE THREAD

**Issue by gpichot** [FormidableLabs/spectacle#1100]
### Prerequisites

- [x] I've searched open [issues](https://www.github.com/FormidableLabs/spectacle/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the [docs](https://www.formidable.com/open-source/spectacle/docs) before asking a question
- [x] I am using the latest version of Spectacle

### Describe Your Environment

Can be seen on v8.5.0, main and v9.0.1 (slide 3)
https://raw.githack.com/FormidableLabs/spectacle/main/examples/one-page.html?slideIndex=0&stepIndex=0&exportMode=true
https://raw.githack.com/FormidableLabs/spectacle/v9.0.1/examples/one-page.html?slideIndex=0&stepIndex=0&exportMode=true

### Describe the Problem

Slide with custom background is blank.

**Expected behavior:** The slide content should be displayed (maybe without the custom background)

**Actual behavior:** Slide is blank.

### Additional Information

As requested https://github.com/FormidableLabs/spectacle/issues/1097 I opening this issue

**Comment by carlos-kelly** [comment]
@gpichot Hopefully 9.0.3 fixes this, if not please let us know!
