### ISSUE TITLE
Add animated PacMan Progress component

### ISSUE THREAD

**Issue by carlos-kelly** [FormidableLabs/spectacle#1105]
### Description

[](https://github.com/FormidableLabs/spectacle/blob/v4.4.1/src/components/progress.js)Previous versions of Spectacle had a Pacman progress indicator instead of just progress dots. We should add a Pacman progress indicator component back to Spectacle.

### Proposal

The previous implementation can be seen

[https://github.com/FormidableLabs/spectacle/blob/v4.4.1/src/components/progress.js](https://github.com/FormidableLabs/spectacle/blob/v4.4.1/src/components/progress.js)

and can likely be heavily lifted for the new implementation. We should make it a separate component called `<AnimatedProgress />`

with similar color and size props as `<Progress />`

**Comment by lenniezelk** [comment]
Hello, I'd like to work on this

**Comment by carlos-kelly** [comment]
@lenniezelk Feel free to take a go at it! Thanks!

**Comment by zubhav** [comment]
@lenniezelk Are you still working on this one? 🙂

**Comment by lenniezelk** [comment]
Yes i am

Regards,

Lenny.

**Comment by lenniezelk** [comment]
@carlos-kelly @zubhav  i'm studying the shared link https://github.com/FormidableLabs/spectacle/blob/v4.4.1/src/components/progress.js and I'm struggling to understand `Pacman.Base` and `Pacman.Body`
Kindly help me understand what is going on.

**Comment by sauliuskerusauskas** [comment]
@lenniezelk - I hope you don't mind if I start taking a look at this one? 🙂 

I'm diving into a related improvement https://github.com/FormidableLabs/spectacle/issues/1106 that involves some refactoring and this component is going to be the perfect way for me to test my solution.
