### ISSUE TITLE
Add command bar for common Spectacle operations

### ISSUE THREAD

**Issue by carlos-kelly** [FormidableLabs/spectacle#1115]
### Description

Add a command bar to Spectacle that can quickly let users perform the following commands:
- Enter/Exit Presentation Mode
- Enter/Exit Overview Mode
- Enter Export Mode (and preferably launch the browser dialog to export to PDF)
- Next Slide
- Previous Slide
- Restart Presentation
- Start/Restart Timer (if in Presenter mode)
- Pause Timer (if in Presenter mode)

### Proposal

Investigate if KBar is the best solution for a React-based command bar.

### Links / References

[KBar React Library](https://kbar.vercel.app)

**Comment by mwritter** [comment]
Kbar has a couple of dependencies that don't support our current version of 'react' and 'react-dom'
<img width="930" alt="Screen Shot 2022-07-21 at 9 45 31 AM" src="https://user-images.githubusercontent.com/14057928/180229039-025320ab-b6a9-4895-bd19-2af9d72d00bb.png">

**Comment by mwritter** [comment]
@carlos-kelly @gksander - quick mvp:

https://user-images.githubusercontent.com/14057928/180236385-b6e108e1-2c9f-47a4-a097-748ca0843701.mov

The 'command bar' works as expected, keyboard shortcuts also trigger the appropriate 'actions'.
