### ISSUE TITLE
BroadcastChannel gets closed before being used

### ISSUE THREAD

**Issue by claudiuandrei** [FormidableLabs/spectacle#1130]
https://github.com/FormidableLabs/spectacle/blob/00c337f62c22d0e8b1ffa1ec0ab45286fe760caa/src/hooks/use-broadcast-channel.ts#L25-L32

With React 18, in Strict Mode the effects are firing twice, which makes this code break as the channel is closed and then never opened again because the name is the same. Probably a better approach here would be to use a ref instead of state as it will also cause fewer re-renders.

I can make a pull request if needed.

**Comment by gksander** [comment]
This fix should be live in `9.2.1`.
