### ISSUE TITLE
Warning in console when using CodePane

### ISSUE THREAD

**Issue by AlbertBrand** [FormidableLabs/spectacle#1137]
What version of Spectacle are you using? (can be found by running `npm list spectacle`)
9.2.1

What version of React are you using? (can be found by running `npm list react`)
18.2.0

### Describe the Problem

Check the console when using a `CodePane`:

```
Warning: React does not recognize the `lineNumberProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `linenumberprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

This is triggered by the upgrade of `react-syntax-highlighter`, they have dropped `lineNumberProps` in newer versions.
Interestingly it doesn't seem to cause problems with highlighting in the`CodePane`.

**Comment by mwritter** [comment]
Looks like this was due to a regression in `react-syntax-highlighter`, and also looks like a fix was started but not finished.
https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/311
