### ISSUE TITLE
Replace fragment

### ISSUE THREAD

**Issue by kenwheeler** [FormidableLabs/spectacle#114]
Add a fragment type, like `Appear` that replaces the current content sequentially, instead of showing sequentially.

**Comment by pedrottimark** [comment]
@kenwheeler Hey, when you get a chance, can you add a few short snippets of JSX in this issue to illustrate this component?

My mental picture is hazy, thinking of JavaScript ternary (replaced ? from : to) or HTML <del>from</del><ins>to</ins> but those analogies might be way off.

Replace probably has a lot in common with Appear, so I want to think ahead as I explore potential changes to Appear for #77 and #117. Also whether there are any other ways to display these components than inspecting and mutating the rendered DOM elements.

**Comment by kenwheeler** [comment]
I was thinking something like:

```
<Replace>
   <Heading>Hey</Heading>
   <Heading>Yall</Heading>
</Replace>
```

**Comment by kenwheeler** [comment]
^ where it shows one child at a time in order

**Comment by kenwheeler** [comment]
I'm doing a major refactor at the moment to pull `react-router` out and replace it with `History`, once I get everything pushed I'll revisit the Appear PR's and get them merged/updated

**Comment by pedrottimark** [comment]
Thank you. So an analogy is an explicitly-controlled carousel which always
displays one child.

After the refactoring, will Spectacle use Redux to store the app state
including current view, current slide, number of Appear fragments visible
on current slide, which Replace children are visible?

**Comment by kenwheeler** [comment]
indeed

**Comment by kenwheeler** [comment]
Closing in favor of extended fragments coming in 3.0
