### ISSUE TITLE
Bug: Spectacle-cli is missing built "bin", ships "src"

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/spectacle#1165]
`spectacle` CLI is missing the built files and publishing `src`.

See, e.g. https://unpkg.com/browse/spectacle-cli@2.0.0-alpha.1/

**Comment by gksander** [comment]
Addressed via #1166, not yet published.

**Comment by fritz-c** [comment]
@gksander Is this published now?

**Comment by gksander** [comment]
Ahh yep, should be good on this front. We should be able to close this.
