### ISSUE TITLE
weird <ul> formatting on MS Edge

### ISSUE THREAD

**Issue by luisrudge** [FormidableLabs/spectacle#117]
![image](https://cloud.githubusercontent.com/assets/941075/11378265/7cf10fa0-92d1-11e5-9403-e03f4519ff3c.png)

**Comment by pedrottimark** [comment]
@luisrudge Thank you for the helpful screen pictures. Here are a few questions:
Which operating system version does your computer have?
Which browser versions at the left and right?
In which browser, does this slide work they way that you expect?
In the browser at the right, the list bullets appeared at the same time as the text when you pressed an arrow key?

For comparison, on OS X 10.11.1,
Firefox 42 and 44 look as the picture at the left
Chrome 46 and Opera 33 look as the picture at the right

**Comment by pedrottimark** [comment]
@luisrudge Can you please do an experiment?

1. First add enough text to a ListItem so it wraps to a second line.
See what you think of the appearance in Chrome.

2. In src/themes/default/screen.js see what difference it makes if you change listStylePosition: "inside" to listStylePosition: "outside"

In Chrome, please confirm that the difference is (a) the second line of the long item has a hanging indent to align with the first line and (b) the behavior of appearing items remains the same as before.

What difference does it make in Edge?

Do you have Firefox on your computer? The difference is makes for me is no weird line break, and (a) same as Chrome, but (b) all bullets are visible, even before the text of the items appears.

**Comment by luisrudge** [comment]
> Which operating system version does your computer have?

Windows 10

> Which browser versions at the left and right?

Left:
![image](https://cloud.githubusercontent.com/assets/941075/11613667/35a42ee6-9c10-11e5-8f1e-189bc2b0b1a3.png)
Right: Chrome 46.0.2490.86 m

> In which browser, does this slide work they way that you expect?

Chrome is alright.

> In the browser at the right, the list bullets appeared at the same time as the text when you pressed an arrow key?

Yes

**Comment by luisrudge** [comment]
Using `listStylePosition: "outside"` solved the issue in MS EDGE and, to be honest, should be the default style. 

The first item is using "inside" and the second one "outsite". The second one is much better than the first one IMO
![image](https://cloud.githubusercontent.com/assets/941075/11613694/77f5051c-9c11-11e5-9d79-06d1acd4afb2.png)

**Comment by pedrottimark** [comment]
@luisrudge Thank you for your detailed comments. I agree with your comment about the default style.

One more question about Edge with listStylePosition: "outside" how does it display the bullet if a ListItem contains an Appear element? For example, on the slide with Inline style based theme system, and so on.

In Chrome, the bullet is invisible when the text is invisible and visible when the text is visible. In Firefox, all bullets are visible, even before the text becomes visible.

A way to solve the inconsistency might be to change the recommended JSX for lists in Spectacle so Appear contains ListItem <List><Appear><ListItem>…</ListItem></Appear>…</List> especially if it is possible for Appear not to output an enclosing div if is has only one child. That would prevent invalid HTML <ul><div><li>…</li></div>…</ul>

**Comment by luisrudge** [comment]
It shows the dots right away (like your firefox example) with this code:

```js
<List>
  <ListItem><Appear fid="1">item 1</Appear></ListItem>
  <ListItem><Appear fid="2">item 2</Appear></ListItem>
  <ListItem><Appear fid="3">item 1</Appear></ListItem>
</List>
```

**Comment by kenwheeler** [comment]
Fixed on master
