### ISSUE TITLE
URLs for slide broken, slideshow always starts at 0 on load/refresh.

### ISSUE THREAD

**Issue by sneakers-the-rat** [FormidableLabs/spectacle#1171]
### Describe Your Environment

What version of Spectacle are you using? (can be found by running `npm list spectacle`)

Fresh clone & install of https://github.com/FormidableLabs/spectacle/commit/8dac6a30fac55e4c65fe23288ee80964b4e536f6

(by the way this is broken too. had to manually install pnpm)

```bash
yarn add pnpm
npx pnpm install
npx pnpm start:js
```

What browser are you using?
Tested on Firefox and Chrome

What machine are you on?
macOS and android

### Describe the Problem

True of any slideshow I try, including the examples in the repository:

Opening a slideshow and navigating to another slide, eg. `http://localhost:3000/?slideIndex=2&stepIndex=0`, and then refreshing will take me back to the 0th slide. Going to the link directly also boots me back to the beginning of the slideshow. This sort of sucks a lot and breaks one of the major reasons why I use this -- being able to link directly to specific slides.

I think it might have something to do with slide 0, step 0 being hardcoded in the deck's usage of location sync....

https://github.com/FormidableLabs/spectacle/blob/8dac6a30fac55e4c65fe23288ee80964b4e536f6/packages/spectacle/src/components/deck/deck.tsx#L281-L287

edit: was able to resolve the problem by reverting to the old style ReactDOM usage. 

ie. rather than

```jsx
import { createRoot } from 'react-dom/client';

const container = document.getElementById('root')
const root = createRoot(container);
root.render(<Presentation />);
```

using 

```jsx
import ReactDOM from 'react-dom'

ReactDOM.render(<Presentation />, document.getElementById('root'))
```

**Comment by AaronPowell96** [comment]
@sneakers-the-rat Hopefully this fix allows you to link to specific slides again! Please reach out if you have further issues.
