### ISSUE TITLE
`spectacle-mdx-loader`: Migration to monorepo

### ISSUE THREAD

**Issue by gksander** [FormidableLabs/spectacle#1178]
## What?

With the migration to the spectacle monorepo, we need to also migrate the [`spectacle-mdx-loader`](https://github.com/FormidableLabs/spectacle-mdx-loader) to the monorepo. [See here](https://github.com/FormidableLabs/spectacle/wiki/Spectacle-Roadmap#spectacle-mdx-loader).

For this issue, we should create a `mdx-loader` package in the monorepo and migrate the code from the existing repository into the monorepo.

**Comment by fritz-c** [comment]
Duplicate of #1164
