### ISSUE TITLE
Babel 6

### ISSUE THREAD

**Issue by pedrottimark** [FormidableLabs/spectacle#118]
@kenwheeler is it better to go ahead and get the change from 5 to 6 out of the way?

devDependencies is not a particular strength of mine, but I know somebody... @knowbody :)

**Comment by knowbody** [comment]
we can't change it to Babel 6 as that would break the react-transform dependency. We can do that whenever react-transform will support Babel 6.

**Comment by LeoAJ** [comment]
[react-transform](https://github.com/gaearon/babel-plugin-react-transform) beta is supporting babel 6 now, try to update from babel 5 to babel 6 but looks like babel 6 is not currently supporting decorator yet, check this [issue](http://phabricator.babeljs.io/T2645) on babel 6 tracker.

**Comment by knowbody** [comment]
@LeoAJ already on it, check #131

**Comment by LeoAJ** [comment]
@knowbody Cool! Totally miss that, apologized, thanks!
