### ISSUE TITLE
Hot reloading is not working on master

### ISSUE THREAD

**Issue by luisrudge** [FormidableLabs/spectacle#120]

**Comment by kenwheeler** [comment]
For which files?

**Comment by kenwheeler** [comment]
cc @knowbody

**Comment by luisrudge** [comment]
`./index.js`

Here's what I'm doing:

```
git clone [this repo]
npm i
npm start
edit ./index.js file 
nothing happens
```

**Comment by luisrudge** [comment]
If I do type `webpack-dev-server --hot --inline --port 3000`, it kinda works, but it's doing a full page refresh

**Comment by luisrudge** [comment]
Here's the log info:

![image](https://cloud.githubusercontent.com/assets/941075/11404532/80b77940-9389-11e5-8ec4-b2b3b67324ee.png)

However, it doesn't reload the page automatically

**Comment by kenwheeler** [comment]
What file were you editing

**Comment by luisrudge** [comment]
the `./index.js` file, where you have the <Deck> and <Slide>'s

**Comment by knowbody** [comment]
confirmed we broke it :construction_worker: 

working to fix it

**Comment by kenwheeler** [comment]
Fixed on master
