### ISSUE TITLE
`website`: Add quality checks.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/spectacle#1203]
We need to add all the following to `website/package.json` wireit tasks:

- [x] `lint`
- [x] `lint:fix`
- [x] `prettier`
- [x] `prettier:fix`
- [ ] `types:check` (Note -- this is blocked by #1201 )

Then:

- [ ] Integrate all those checks in root aggregate tasks in `package.json`
- [ ] Remove `paths-ignore` in main CI workflow so we do all docs code checking there
- However, let's keep the `build` task in `website` out of both wireit and CI and leave it to just the docs workflow.

**Comment by paulmarsicloud** [comment]
I'll take a pass at this in https://github.com/FormidableLabs/spectacle/tree/chore/website-quality-checks 👍

**Comment by paulmarsicloud** [comment]
I'm running into some odd issues with this one. Running `pnpm prettier:pkgs` from the top-level folder shows this:
```
> spectacle-monorepo@ prettier:pkgs /Users/paulmarsicovetere/Documents/code/FormidableLabs/spectacle
> wireit

🏃 [website:prettier] Running command "nps prettier:website -- -- "*.js" src"
✅ [examples/one-page:prettier] Already fresh
✅ [examples/js:prettier] Already fresh
✅ [examples/typescript:prettier] Already fresh
✅ [examples/md:prettier] Already fresh
✅ [packages/create-spectacle:prettier] Already fresh
✅ [packages/spectacle:prettier] Already fresh
nps is executing `prettier:website` : nps prettier:base -- -- --config ../.prettierrc --ignore-path ../.prettierignore *.js src
nps is executing `prettier:base` : prettier --list-different --config ../.prettierrc --ignore-path ../.prettierignore babel.config.js docusaurus.config.js formideploy.config.js sidebars.js src
docusaurus.config.js
src/components/global/body-copy.tsx
src/utils/numbers.js
The script called "prettier:base" which runs "prettier --list-different --config ../.prettierrc --ignore-path ../.prettierignore babel.config.js docusaurus.config.js formideploy.config.js sidebars.js src" failed with exit code 1 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "prettier:website" which runs "nps prettier:base -- -- --config ../.prettierrc --ignore-path ../.prettierignore *.js src" failed with exit code 1 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
❌ [website:prettier] Failed with exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```

What is strange is that when I `prettier` from the `website` folder via `npx`, this works properly without error: 
```
spectacle/website > npx prettier --list-different --config ../.prettierrc --ignore-path ../.prettierignore babel.config.js docusaurus.config.js formideploy.config.js sidebars.js src
docusaurus.config.js
src/components/global/body-copy.tsx
src/utils/numbers.js
```

I'm missing _something_ in the `packages-scripts.js`, I'm just not sure what

**Comment by ryan-roemer** [comment]
What’s the exit code of that prettier command you just executed? If list different is giving you file results I think that means that that’s a failure?

**Comment by ryan-roemer** [comment]
And does “prettier:fix” actually change the 3 files in question and then cause “prettier” task to succeed?

**Comment by paulmarsicloud** [comment]
Wow, I can't believe I didn't think to try that 🤦 

` pnpm prettier:pkgs:fix` gave the same error, but completed. So I ran `pnpm prettier:pkg` and it worked properly!

Will continue on!

**Comment by ryan-roemer** [comment]
That sounds right. What I think is happening is that the fix task actually runs the check first, to take advantage of caching, and then if it fails runs the actual fixing task. So there is an intermediate failure if the fix task actually mutates files. And that’s all as expected

**Comment by paulmarsicloud** [comment]
alrighty, so now I'm getting this error for `types:check` even on the `main` branch:

```
pnpm run types:check

> spectacle-monorepo@ types:check /Users/paulmarsicovetere/Documents/code/FormidableLabs/main_branches_only/spectacle
> wireit

🏃 [packages/create-spectacle:types:check] Running command "nps types:check -- -- --p tsconfig.typecheck.json"
🏃 [packages/spectacle:types:check] Running command "nps types:check"
🏃 [examples/typescript:types:check] Running command "nps types:check"
nps is executing `types:check` : tsc --noEmit
nps is executing `types:check` : tsc --noEmit --p tsconfig.typecheck.json
nps is executing `types:check` : tsc --noEmit
index.tsx(11,3): error TS2305: Module '"spectacle"' has no exported member 'AnimatedProgress'.
index.tsx(23,3): error TS2305: Module '"spectacle"' has no exported member 'SlideLayout'.
The script called "types:check" which runs "tsc --noEmit" failed with exit code 2 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
✅ [packages/create-spectacle:types:check] Executed successfully
✅ [packages/spectacle:types:check] Executed successfully
❌ [examples/typescript:types:check] Failed with exit status 2
 ELIFECYCLE  Command failed with exit code 1.
```

Once this is resolved, I think I should be good to PR for the `lint` and `prettier` changes 👍

**Comment by paulmarsicloud** [comment]
some interesting things happening with the `types:check` changes.

When `pnpm install` is run, it installs a different number of `node_modules` packages in `website` (I'm sure this is by design):
```
ls -lah website/node_modules | wc -l
20
```

When trying to run `npx tsc --noEmit` these errors show:
```
error TS2688: Cannot find type definition file for '@docusaurus/theme-classic'.
  The file is in the program because:
    Entry point of type library '@docusaurus/theme-classic' specified in compilerOptions

error TS2688: Cannot find type definition file for 'node'.
  The file is in the program because:
    Entry point of type library 'node' specified in compilerOptions


Found 2 errors.
```

When `yarn` is run directly in the `website` folder, a much higher number of `node_modules` packages are installed:
```
ls -lah website/node_modules | wc -l
786
```

Then, when `npx tsc --noEmit` is run again, no errors are shown.

Digging into this

**Comment by ryan-roemer** [comment]
@paulmarsicloud I’m happy to pair up tomorrow in this if you want fresh eyes.

I would expect yarn and pnpm to be very different for installed modules because of how they work. But pnpm is more strict for things like phantom dependencies so may be that too

**Comment by paulmarsicloud** [comment]
thanks @ryan-roemer ! Yeah I'm trying with https://pnpm.io/npmrc#node-linker `node-linker: hoisted` which does make `npx tsc --noEmit` work, but then `pnpm run test` fails with `Cannot find module 'react-dom/client' from '../../node_modules/@testing-library/react/dist/pure.js'` so yeah might need another set of eyes to run through this 😄

**Comment by paulmarsicloud** [comment]
@ryan-roemer got it; need to set [this](https://pnpm.io/npmrc#shamefully-hoist) to `true` in order to work for docs website 🙌 
PR ready: https://github.com/FormidableLabs/spectacle/pull/1216
