### ISSUE TITLE
presenter mode + slide with <Appear> items behaviour is wrong

### ISSUE THREAD

**Issue by luisrudge** [FormidableLabs/spectacle#122]
(Sorry about the huge gif)

When I hit `arrow-right` to show the next `Appear` item, the presenter mode thinks I'm changing to the next slide

![presenter-mode-and-list-items](https://cloud.githubusercontent.com/assets/941075/11407892/c8d7eefe-939c-11e5-9304-c149aa46d896.gif)

**Comment by kenwheeler** [comment]
Fixed now, sorry about that!

**Comment by luisrudge** [comment]
It's still a little weird:
Notice how the preview is moving the slides forward..

![presenter-mode-and-list-items](https://cloud.githubusercontent.com/assets/941075/11409708/d86e5536-93a8-11e5-9ce7-dc9d3df18dca.gif)

**Comment by pedrottimark** [comment]
@luisrudge When you write "It's still a little weird" do you mean that in presenter mode, if the current slide and the next (look ahead) slide both contain Appear components, then the arrow keys affect the Appear components in both slides?

That just happened to me. Also in a deck made with 0.0.5, so apparently not a recent regression.

Which is more useful for you: all Appear components in the next (look ahead) slide are visible or not visible?

**Comment by luisrudge** [comment]
@pedrottimark that's correct. I think the preview should always show the final state, with all appear elements shown.

**Comment by pedrottimark** [comment]
@kenwheeler Result of research: Appear components contained in either the main or next (look ahead) slide assume that the current slide index number from context applies to them. A possible direction is for them to receive the slide index number of their ancestor slide from context. Appear components whose ancestor slide differs from the current slide would be visible in presenter mode. Slide components already receive their own index number as a key prop, but it is unused.

**Comment by kenwheeler** [comment]
Should the presenter mode only show it completed? One would think while presenting you would want to see the appears as they appear?

**Comment by kenwheeler** [comment]
It shouldn't show in the next slide

**Comment by luisrudge** [comment]
In the current slide preview, it should show the appear in with the default behavior.. but in the next slide preview, it should show completed

**Comment by kenwheeler** [comment]
Fixed on master
