### ISSUE TITLE
iframe state doesn't get synced in presenter mode

### ISSUE THREAD

**Issue by bebraw** [FormidableLabs/spectacle#123]
If you use iframes and alter their content somehow (i.e., scroll), it doesn't sync with the presentation.

I'm aware it might not be trivial to pull this off technically but just thought to mention so you can at least document this.

**Comment by kenwheeler** [comment]
Yeah I had something similar where I had a live typing transpiler component and I needed to do it on the crowd facing browser. I wonder how to do this. Maybe serialize all events and pass them through localStorage and fire them on the other side? Thoughts?

**Comment by bebraw** [comment]
@kenwheeler Yeah, `localStorage` is nice for syncing given it's shared state.

References: http://stackoverflow.com/a/12514384/228885, https://ponyfoo.com/articles/cross-tab-communication .

**Comment by kenwheeler** [comment]
Yeah that's how I do slide syncing now, maybe setup reverse event delegation where I listen to events on the document and serialize the event and the targets and trigger it. I'll play and see how it goes.

**Comment by kenwheeler** [comment]
I wasn't able to get this working.
