### ISSUE TITLE
Remove `create-react-app` option, Add new option 1 using Next.js?

### ISSUE THREAD

**Issue by karlhorky** [FormidableLabs/spectacle#1260]
### Description

Now that [`create-react-app` is going away](https://github.com/reactjs/react.dev/pull/5487#issuecomment-1409720741) (it's turning into a launcher), I would propose the following changes:

1. Remove all mentions of `create-react-app` from the tutorial (this is Option 1, so very visible)
2. Add a new Option 1 that uses Next.js instead - ideally using the App Router + React Server Components

### Proposal

By changing the documentation and providing a polished, tested template using Next.js

### Links / References

Linked above already

**Comment by carloskelly13** [comment]
@karlhorky This is a good idea. I think the quickest way to boot strap a new Spectacle deck when wanting to use JSX + React components is Vite, but Next App Router is also a good choice.

**Comment by karlhorky** [comment]
Thanks for this @carloskelly13 ! 🙌 @ProchaLu will try out migrating our slides from `mdx-deck` to Spectacle + Next.js + App Router.

**Comment by carloskelly13** [comment]
Yeah! Let us know if you find anything during the migration!
