### ISSUE TITLE
iphone 6 demo quote slide broken

### ISSUE THREAD

**Issue by vvo** [FormidableLabs/spectacle#129]
![2015-12-08-105801_602x597_scrot](https://cloud.githubusercontent.com/assets/123822/11652887/9864b402-9d9a-11e5-92ea-4c1207aa69b6.png)

**Comment by vvo** [comment]
Sorry to just drop this but I was excited by the project, checked out in the subway and.. this slide did not meet my expectations! Good work still it seems a great project.

**Comment by kenwheeler** [comment]
Thanks for finding this! On it.

**Comment by kenwheeler** [comment]
Fixed on master
