### ISSUE TITLE
Demo link is broken

### ISSUE THREAD

**Issue by vidhill** [FormidableLabs/spectacle#1298]
### Prerequisites

- [ x] I have searched the open [issues](https://www.github.com/FormidableLabs/spectacle/issues) to make sure I'm not opening a duplicate issue
- [ ] I have read through the [docs](https://www.formidable.com/open-source/spectacle/docs) before asking a question
- [ x] I am using the latest version of Spectacle

### Describe Your Environment

**What browser are you using?** Chrome Version 118.0.5993.117

**What platform are you on?** macOS

### Describe the Problem

The demo link ( https://raw.githack.com/FormidableLabs/spectacle/main/examples/one-page/index.html  ), linked from https://github.com/FormidableLabs/spectacle/blob/main/packages/spectacle/README.md is broken

**Expected behavior:** Demo

**Actual behavior:** Blank page

**Comment by carloskelly13** [comment]
We have fixed the import map path. You may need to clean the browser cache to see the changes reflected.

<img width="1491" alt="Screenshot 2023-11-15 at 3 43 49 PM" src="https://github.com/FormidableLabs/spectacle/assets/1738349/7c5156ed-607b-4c8b-a539-fe03a8156c5d">
