### ISSUE TITLE
Point homepage at http://stack.formidable.com/spectacle

### ISSUE THREAD

**Issue by david-davidson** [FormidableLabs/spectacle#133]
Hey @kenwheeler, I don't think I have write/edit access here, but would you mind updating the homepage (top of the repo view) to point at the new URL, http://stack.formidable.com/spectacle ? :facepunch:

**Comment by kenwheeler** [comment]
![image](https://cloud.githubusercontent.com/assets/286616/11885844/1c18b7c8-a4d8-11e5-9f26-a1700a49d08c.png)
