### ISSUE TITLE
codePane font overwrite does not work

### ISSUE THREAD

**Issue by wmonk** [FormidableLabs/spectacle#135]
When setting the font families with createTheme, the `codePane` element receives the correct font definition. However, Prism overwrites this rule with it's own font family.

It is possible to fix this by adding `fontFamily: fonts.tertiary` to the `codePane` -> `code` style definition, but wasn't sure if this was the intended behaviour.

If you want I can make a pull request. Thanks!

**Comment by kenwheeler** [comment]
A PR would be happily accepted. Great catch!

**Comment by kenwheeler** [comment]
closing pending PR

**Comment by LeonardAukea** [comment]
Nobody is on this?
