### ISSUE TITLE
Appear component does not work on final slide when controlling with Presenter

### ISSUE THREAD

**Issue by wmonk** [FormidableLabs/spectacle#136]
Steps to reproduce:

1. Create presentation (I used the boilerplate, with no extra changes)
2. Add an `Appear` component to the final slide
3. Open presenter and deck
4. Get to last slide, and press right arrow key
5. Presenter changes state correctly, deck does not change

No errors appear in either console.

**Comment by kenwheeler** [comment]
Whoah, I'll get this one fixed quick
