### ISSUE TITLE
PDF Export only exporting the first slide & ignoring rest

### ISSUE THREAD

**Issue by detj** [FormidableLabs/spectacle#137]
Export only shows up and prints PDF of the first slide. Only page 1 is exported. The screenshot on README.md though shows `10` pages. For testing, I tried exporting after cloning the master branch without any modifications.

![PDF Export Screenshot](https://camo.githubusercontent.com/1b5ebc3305e09162390fafe716673c4133cd103b/687474703a2f2f692e696d6775722e636f6d2f7436474c354f632e706e67)

Tried on Chrome 47, Firefox 43 & Safari 9.0.3.

**Comment by knowbody** [comment]
@detj just make sure that your URL has: `?export` in the end and tick the: *Background graphics* option.

This is what I've tried on master:

<img width="1264" alt="screen shot 2016-01-03 at 14 22 17" src="https://cloud.githubusercontent.com/assets/3802023/12079125/a6cafab6-b225-11e5-8885-9c554eda0678.png">


@kenwheeler maybe we can just add this flag (`?export`) after someone hits **cmd/ctrl + p**?

**Comment by ryan-roemer** [comment]
@knowbody -- The ambiguity with the event listener default on ctrl-p is if someone wants `http://localhost:3000/#/?export&print` instead.

**Comment by knowbody** [comment]
I see, you've got a point here @ryan-roemer, thanks :+1:

**Comment by detj** [comment]
Okay @knowbody. That worked. The README says `/#/?export` instead of just `?export`. I think it should be updated.

**Comment by knowbody** [comment]
It's because we use browser history, if you are using hash history than the hash would be valid. I will update the docs with:

> append your URL with `?export`

does that seem better?

**Comment by detj** [comment]
Yup, it does.

**Comment by knowbody** [comment]
done here: #140
