### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by mdamien** [FormidableLabs/spectacle#14]
Hey, I would like to repurpose it for a project, can you put a random license on it ? :smiley:

**Comment by kenwheeler** [comment]
Repurpose it?

**Comment by mdamien** [comment]
Yeah, as a game for kids where you makes choices at each slide and it redirect you to another slide.  (like "be your own hero" books).

Also the project structure is really well done, I think a lot of people are gonna use it to bootstrap their projects.

**Comment by kenwheeler** [comment]
Well that sounds fun. I'll throw it under a MIT license this morning (on mobile atm)

**Comment by kenwheeler** [comment]
Added MIT, enjoy
