### ISSUE TITLE
npm install spectacle fails

### ISSUE THREAD

**Issue by aickin** [FormidableLabs/spectacle#141]
When I run `npm install spectacle`, it fails with the following error:

```
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "spectacle"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package history@1.13.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router@1.0.3 wants history@^1.17.0

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/MYUSER/code/ssr-perf-talk-2/npm-debug.log
```

When I look at `spectacle`'s package.json, I see:

```
  "dependencies": {
    "history": "1.13.1",
    <snip>
    "react-router": "^1.0.0",
```

which seems to be the cause of the problem. `react-router` 1.0.3 needs a newer version of `history`.

I see that someone removed `react-router` completely from the package.json a few days ago in master; this would fix the problem, I believe, but of course it needs to be published to npm.

Note that this bug also makes the spectacle boilerplate fail when `npm install` is run.

**Comment by kenwheeler** [comment]
Fixing this now

**Comment by insin** [comment]
Looks like the [1.0.3 tarball](http://registry.npmjs.org/spectacle/-/spectacle-1.0.3.tgz) has been bitten by the npm history bug, which has only been fixed in npm2 at the time of writing: npm/npm#9642

Delete `node_modules\history` before running `npm publish` - here's how react-router does it, as it was recently re-bitten by this: https://github.com/rackt/react-router/commit/4e0a633c2741225e73c378d820bc126965cc6f8c

**Comment by kenwheeler** [comment]
Ok, I'm going to try to get 1.0.4 out tonight, can you check again after I push it out? @insin

**Comment by kenwheeler** [comment]
Just republished, thanks again

**Comment by aickin** [comment]
Awesome. Thanks so much, and thanks for creating cool stuff and putting it out into the world!

**Comment by kenwheeler** [comment]
@aickin youre welcome, and its my pleasure
