### ISSUE TITLE
Github/NPM disparity. Version 1.0.3

### ISSUE THREAD

**Issue by danielma** [FormidableLabs/spectacle#143]
I just started working with spectacle, and was trying to customize the color of the progress bar, so I set `colors.tertiary` using the built in `createTheme` function. I expected it to work based on [screen.js](https://github.com/FormidableLabs/spectacle/blob/master/src/themes/default/screen.js#L100), but it didn't.

When I went digging into the code of Spectacle 1.0.3 from NPM, I realized that the progress bar is actually set using an undocumented (and according to Github non-existent) property `colors.quartentary`. [ref](https://npmcdn.com/spectacle@1.0.3/lib/themes/default/screen.js)

The NPM version was pushed 3 days ago, but the GitHub project hasn't been updated in 6 days. Looks like things have fallen out of sync

Thanks for all the work on Spectacle. It's a great project!

**Comment by kenwheeler** [comment]
Pushed now, i'm dumb. Sorry!
