### ISSUE TITLE
npm install does not work - mdast-react is not a package (Windows)

### ISSUE THREAD

**Issue by BaumgartnerWilliam** [FormidableLabs/spectacle#150]
Hi, guys. I was trying to npm install spectacle. But the package.json uses a git url to mdast-react depedency. Since the url doesn't seem to be right to windows, it can't find the package, thus fails to install.

changing *mdast-react* depedency from *https://github.com/jjt/mdast-react#2ea3bcd* to **git://github.com/jjt/mdast-react.git#2ea3bcd** fixes the problem.

**Comment by kenwheeler** [comment]
Thanks for the heads up!

**Comment by kenwheeler** [comment]
Fixed in the last commit

**Comment by veggiemonk** [comment]
This change made impossible to `npm install` spectacle behind a company proxy.
ping @kenwheeler 
Why not publishing a package?

**Comment by BaumgartnerWilliam** [comment]
Hi @veggiemonk 

Have you configured <b>node</b> and <b>git</b> to use your company proxy ? If that's not the case [here's the how to](http://digitaldrummerj.me/proxy-configurations/)

I.E :
 `npm config list 
`
`git config --list`

I am behind a corporate proxy too and it does work...

PS: NPM seems to ignore .gitconfig in some cases so you can simply do

```
git config --global url."https://github.com/".insteadOf git@github.com:
git config --global url."https://".insteadOf git://
```
as mentionned [HERE](https://github.com/npm/npm/issues/5257#issuecomment-60441477) 

Hope it helps,

Cheers.

**Comment by veggiemonk** [comment]
@BaumgartnerWilliam IT WORKED!!! It changed everything for me!

Thank you very much!
