### ISSUE TITLE
[Feature request]: Routing/params for Appear identifiers

### ISSUE THREAD

**Issue by toddmotto** [FormidableLabs/spectacle#152]
I absolutely _love_ the `<Appear>` transitioning, however one thing I'd love to see is the following:

When I'm on slide 4 (for example), I might have 5 `<Appear>` blocks. When I reload, go forward or back a slide, the slide gets reloaded and I have to tab next, next, next to see all my `<Appear>` blocks to make sure text changes have happened. 

Just an idea, but perhaps from a routing perspective you could save the current "state" of the `<Appear>` blocks by using URL params or the router:
#### Current state

``` html
// has 5 appear blocks
http://localhost:3000/4
```

If I tab through my `<Appear>` blocks the state gets lost if I refresh. I'd find it super useful if the `<Appear>` state was persisted.
#### Proposed feature

Maybe I want to send people or "bookmark" access to an exact `<Appear>` block, so that I can refresh the slide and state is persisted:

``` html
// has 5 appear blocks, number 1 + 2 are visible
http://localhost:3000/4?appear=2
```

Or even better/clearer:

``` html
// has 5 appear blocks, number 1 + 2 are visible
http://localhost:3000/4/2
```

**Comment by pedrottimark** [comment]
Agree! That change would put all of the state in the URL so much logic can be brought together in Redux reducers.

As Michael Jackson and Ryan Florence say, “Make the URL your first thought, not an afterthought.”

A reason in favor of your second pattern (which unlike a query key, does not require an explicit name) is the pending proposal to add a Replace component, which would share that part of the state with Appear. In my mind, I am calling it the count of visible steps (in analogy with animation steps).

**Comment by kenwheeler** [comment]
In full agreement, I'll try to carve time out this weekend

**Comment by toddmotto** [comment]
@pedrottimark Thanks! Yes, I think the second pattern is much clearer - just wanted to provide potential options for discussion :dancer:

**Comment by kenwheeler** [comment]
I'm partial to the second syntax

**Comment by pedrottimark** [comment]
@kenwheeler If there's a way for me to help, let me know. For example, I have explored an alternative way to count the number of steps on a slide by passing callbacks to instances via context instead of querying rendered elements in the DOM.

**Comment by kenwheeler** [comment]
got a branch?

**Comment by pedrottimark** [comment]
Can push a branch with just that part on my fork before the weekend.

**Comment by kenwheeler** [comment]
splendid

**Comment by pedrottimark** [comment]
@kenwheeler Here is a warm-up act. Looking forward to what you do in the main attraction.

- Needed to update version of Radium because of bug which prevented childContextType in Slide
- Several console.log to let you see the data flow and verify stepCount is equivalent to fragment count.
- Didn't touch fragments logic in Slide or Deck. You can change it as little as you need or as much as you want.

https://github.com/pedrottimark/spectacle/tree/step-visitor
