### ISSUE TITLE
npm run build:dist fails

### ISSUE THREAD

**Issue by oliviertassinari** [FormidableLabs/spectacle#153]
Why is `transform-decorators-legacy` only enable in development? https://github.com/FormidableLabs/spectacle/blob/cdfd5c458deb9c6ea15f51df0fac91f52bac8fb6/.babelrc#L6

**Comment by knowbody** [comment]
yeah, could be just:

```json
{
  "presets": ["es2015", "stage-0", "react"],
  "plugins": [
    ["transform-decorators-legacy"],
  ]
}
```

**Comment by oliviertassinari** [comment]
I wanted to submit a PR another topic. Looks like it will be a two in one :).
