### ISSUE TITLE
[Feature request] - Preload images of the next slide while showing the previous one

### ISSUE THREAD

**Issue by bebraw** [FormidableLabs/spectacle#155]
It would be neat if spectacle could preload the images of the next slide as you are viewing your current one. I'm aware of the current preloading mechanism, but it doesn't seem to cut it on slower connections.

**Comment by knowbody** [comment]
great idea!

**Comment by kenwheeler** [comment]
Awesome idea indeed

**Comment by ebrillhart** [comment]
Hi! In an effort to focus on more recent bugs and requests, we're closing all open issues more than a year old, with some exceptions. If your issue is closed, and you still feel strongly about it, please feel free to reopen it or submit a PR with the change!
