### ISSUE TITLE
CodePane cannot handle `children`?

### ISSUE THREAD

**Issue by iansinnott** [FormidableLabs/spectacle#157]
Hey team, it seems that the `<CodePane />` component cannot handle being passed child nodes as the `format` function assumes it is passed a string.

## To Reproduce

Try to render the following slide within a presentation:

```js
<Slide transition={['zoom', 'fade']}>
  <CodePane lang='jsx' margin='20px auto'>
    <div></div>
  </CodePane>
</Slide>
```

Here is the line of code in question: https://github.com/FormidableLabs/spectacle/blob/master/src/components/code-pane.js#L16

---

So was `CodePane` ever meant to accept children and render them? If so it seems that this is a bug.

**Comment by kenwheeler** [comment]
What would children necessarily do? Are you trying to feed that as renderable source, or as renderable elements?

**Comment by iansinnott** [comment]
I may have misunderstood the intended use of `children` in this component, but I was hoping to render those children onto the screen as a formatted text block, just like `CodePane` does when passed a `source` prop.

I'm guessing the following would work fine:

```js
<Slide transition={['zoom', 'fade']}>
  <CodePane lang='jsx' margin='20px auto'>
    {`<div></div>`}
  </CodePane>
</Slide>
```

**Comment by kenwheeler** [comment]
If you want to PR, I'd be more than happy to accept that feature

**Comment by iansinnott** [comment]
Cool, I'll close this out then and reference if in PR if i end up making one
