### ISSUE TITLE
hot reload does not work

### ISSUE THREAD

**Issue by agdolla** [FormidableLabs/spectacle#158]
I'm using Spectacle Boilerplate on Windows and hot reload does not work, I receive:
[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to...
[HMR]  - ./presentation/index.js

(win10, node 5.6.0, spectacle 1.0.4, chrome)

**Comment by luisrudge** [comment]
I'm seeing the same issue as well

**Comment by kenwheeler** [comment]
@luisrudge are you seeing this on OSX as well, or just on windows?

**Comment by luisrudge** [comment]
I don't have a mac, so I can't say anything about osx :(

**Comment by kenwheeler** [comment]
Wondering if this is a windows specific thing. Can anyone with both env's set up confirm?

**Comment by dumbNickname** [comment]
Is your issue present after building pure spectacle on master branch, or have you already changed something? I am asking because I had the same issue on Widows, which (in my case) was related to improper export of presentation component and hmr was getting lost. Currently everything works fine,

**Comment by agdolla** [comment]
Did a fresh install of spectacle boilerplate and now it works
sorry for the noise
