### ISSUE TITLE
Make history configurable; Support decks in non-root URLs.

### ISSUE THREAD

**Issue by scottnonnenberg** [FormidableLabs/spectacle#160]
I'd really like to make url scheme consistent between development and production mode.

https://github.com/FormidableLabs/spectacle/blob/2c45ea6b5cb2c567cf13a9aa69d6cce68893bee9/src/utils/controller.js#L10

**Comment by ryan-roemer** [comment]
And if we could also make the resulting history scheme "pluggable" for my case of already having a react router in the middle of a route when I hit a spectacle deck that would be super-awesome!!!

**Comment by scottnonnenberg** [comment]
Development mode today requires a custom server backend, because reloads result in 404 responses. It also demands that the deck be served at the root URL of the website, because new slides, no matter where the presentation is hosted, result in a rewritten URL of '/1', '/2' and so on.

**Comment by kenwheeler** [comment]
what do you guys think for the API? A prop on the <Spectacle/> or <Deck/> tags?

**Comment by ericclemmons** [comment]
@kenwheeler That'd work great for me!  Either that, or using whatever `window.location.path` (or whatever `/my-presentation` is) and using `hashHistory` (e.g. `/my-presentation#0`).

**Comment by kenwheeler** [comment]
History is now configurable
