### ISSUE TITLE
Can't Import children to Deck to Component

### ISSUE THREAD

**Issue by bencripps** [FormidableLabs/spectacle#164]
I wanted to modularize my presentation so I did something like this:

```
<Deck { ...deckProps }>
    <CustomSlideComponent />  // a wrapper for <Slide />
</Deck>
```

But this throws an error: warning.js:45 Warning: Failed propType: Invalid prop `children` supplied to `Deck`, expected a ReactNode. Check the render method of `Connect(Deck)`.

I'm using `Redux` but it doesn't seem like thats the issue.

If I simply nest a `Slide` and accopmanying children, there is no error.

**Comment by kenwheeler** [comment]
Can you post a gist? That error is usually indicative of an error in the imported component.

**Comment by bencripps** [comment]
Slide Wrapper
```

import { Slide, Text } from 'spectacle';
export const SlideWrapper = ({ text }) => {
    const slideProps = {};
    return (
         <Slide { ...slideProps }>
             <Text>{ text }</Text>
         </Slide>
         );
}
```

Deck

```
import { Deck } from 'spectacle';
import { SlideWrapper } from './SlideWrapper';

const app = () => {

    return (
              <Deck><SlideWrapper text="hello /></Deck>
         );

}

```

**Comment by kenwheeler** [comment]
Yeah, its looking for the children themselves, not wrapped children, which is why there is a problem. Let me see if I can set something up to look another level deep if necessary

**Comment by dumbNickname** [comment]
I wanted to cut my presentation into smaller parts as well and bumped from the same problem. I found a nice solution here: https://github.com/MarkRedeman/mutation-testing-in-php/blob/master/src/slidify.js (all the credits go to @MarkRedeman)  and used it in my presentation as well:  https://github.com/dumbNickname/summit2016-react-redux . Maybe spactacle could expose such a utils function (probably it would be easier to maintain than some children lookup logic). Hope it helps!

**Comment by tdmckinn** [comment]
Put together this gist something like this seems to work for me  when trying to import children slides and or grouping slide section together.
https://gist.github.com/tdmckinn/7d47bf5e088457a571fdcfa043f684e8 

Once my presentation past 200+ lines I immediately started trying to make the presentation more modular. React can pretty much figure out the elements in that array form which are children of Deck.

**Comment by gpltaylor** [comment]
I had the same issue. Was surprised that someone was able to make React Components not support Components. This is not an easy thing to break! :insert smiley face here:

The following allows you to split up the code base and include where required. As the code needs a given Type (For example a Slide) if the Component is not of this type (or implements the expected members) then the code dies. It doesn't handle this gracefully. 

This is a little poor as I would like to use this for a lot of presentations as the idea is sound. However, I don't want lots of JS projects with slides copied and pasted.
 
https://gist.github.com/gpltaylor/d0e6a25bcacc00dddda19295a7eb2dd1

**Comment by kenwheeler** [comment]
Couldn't you just export an array of slides? It's the external wrapper that causes the problem because Deck is expecting a valid slide component as a direct child.
