### ISSUE TITLE
dependency install problem: mdast-react 

### ISSUE THREAD

**Issue by veggiemonk** [FormidableLabs/spectacle#167]
Hi everyone,

Thanks for making this awesome project. 

This is not a duplicate of #150 : npm install does not work - mdast-react is not a package (Windows)

I work in a linux VM and this is not related to OS environment.

Apparently changing mdast-react depedency from https://github.com/jjt/mdast-react#2ea3bcd to git://github.com/jjt/mdast-react.git#2ea3bcd fixes the problem on windows but This change made impossible to `npm install` spectacle behind a **company proxy**.

Does anybody has a workaround this?
How about making a simple package from mdast-react ?

**Comment by kenwheeler** [comment]
The reason it's pointed at github is because this pull request is pending https://github.com/mapbox/remark-react/pull/11

**Comment by veggiemonk** [comment]
@kenwheeler Thanks for the quick answer. I'll close this as soon as the PR is merged.

**Comment by veggiemonk** [comment]
There is a workaround here #150 for those who are behind a proxy. Thanks to @BaumgartnerWilliam

    git config --global url."https://github.com/".insteadOf git@github.com:
    git config --global url."https://".insteadOf git://

Issue can be closed since this issue is searchable.
