### ISSUE TITLE
Add Overview Mode

### ISSUE THREAD

**Issue by waywaaard** [FormidableLabs/spectacle#17]
Basically, the same as implemented in reveal.js.

**Comment by kenwheeler** [comment]
Spectacle doesn't do vertical navigation so I'm thinking a grid might be a better option. What do you think @waywaaard?

**Comment by waywaaard** [comment]
Yes, a grid is completely sufficient, I do not use vertical slides. This would also reduce the required scrolling in order to reach a slide.
