### ISSUE TITLE
Not possible to change renderer for html nodes

### ISSUE THREAD

**Issue by waywaaard** [FormidableLabs/spectacle#176]
It seems that specifiing `mdastReactComponents.html = ...` with a custom renderer is not working. Is this intended? It never gets called, though there is inline HTML, that is then output as normal text.

Regards

**Comment by kenwheeler** [comment]
Got a gist of what you're trying to do so I can verify?

**Comment by waywaaard** [comment]
I want to render the inline HTML nodes in Markdown. I am using spectacle to dynamically create presentations from Juypter Notebooks.

Try rendering following markdown with inline HTML.
```markdown
You can use <kbd>Shift</kbd>+<kbd>Tab</kbd> to ....
```

The HTML nodes are rendered as pure Text, though I've added an HTML renderer for handling those. Of course there is an difference between inline and block nodes.

For now, I've written a completely new Markdown Component, that can render those nodes. That component is based on the `markdown-it` parser and does also build up a tree of React-Nodes, which can be rendered.

Setting a custom renderer for the built-in Markdown-Component did not work for me.

**Comment by kenwheeler** [comment]
Any interest in PR'ing an improved markdown component?

**Comment by kenwheeler** [comment]
Closing because we're switching away from mdast, and moving to markdown-it

**Comment by waywaaard** [comment]
Just a quick question. I've implemented a my own Markdown Tag using `markdown-it`, though it is quite difficult to support inline HTML. I try to make a PR, when I've got more time.
