### ISSUE TITLE
Pluggable Animation Solution for Transitions?

### ISSUE THREAD

**Issue by joshburgess** [FormidableLabs/spectacle#179]
Have you all thought about maybe offering the ability to swap out what's used for animatiing transitions? I think it would be cool to be able to easily plug in something like velocity-react (velocity.js), Greensock GSAP, maybe animateplus, etc.... I've noticed stuttering at times during animation, and I think some of these libraries could help to achieve better performance/smoother transitions.

**Comment by kenwheeler** [comment]
That would be pretty cool. What would an ideal API look like for you?

**Comment by joshburgess** [comment]
I'm not sure. I'd have to think about it. I'd be down to collaborate on this/contribute also if you want. 

Oh, and just to be clear, I wasn't bashinh the transitions. I've noticed they're actually quite smooth if you're on a pretty recent computer with a strong CPU, but they were a bit laggy/choppy when I was testing on older laptops & phones. I thought that they might have been CSS3-powered until I looked and saw they were using react-tween-state.

I'm not 100% sure if something like velocity or GSAP would provide a performance boost there, as I don't have much experience with react-tween-state, but I think there's a good chance they would. I have a lot of experience with velocity and have seen it do really complex animations on some of these same older laptops/phones I've tested with and they were really smooth. I know GSAP is also really, really good, but I'm not sure if there's a React wrapper/integration library for it yet.

**Comment by kenwheeler** [comment]
Right now its tween state based, but I'd love to switch to react motion and expose the transition hooks so that you can make your own. I tried to cover the most requested ones, but yeah depending upon cpu some can get a bit choppy. Most of my presos I turn transitions off and instead have interactive react stuff inside the slides, so it might not be as visible to me personally.

**Comment by joshburgess** [comment]
Besides being based on spring physics, does react-motion have any performance advantages over react-tween-state?

**Comment by kenwheeler** [comment]
Not positive on that. Both are rAF based IIRC. I'd have to check to see what kind of optimizations are included in the motion wrappers.

**Comment by markerikson** [comment]
Would also be nice to at least set duration for stuff like `<Appear>`.  With Powerpoint, I usually just want my appears to be instant-on-next.

**Comment by waywaaard** [comment]
The duration is currently hardcoded, though it would be easy to move to the prop types. But I think, that the overall animation stuff needs and overhaul.

**Comment by kenwheeler** [comment]
Animation is indeed due for an overhaul and will be probably completely rewritten

**Comment by kenwheeler** [comment]
Added!
