### ISSUE TITLE
[Feature Request] Add CJSX and SASS support

### ISSUE THREAD

**Issue by ryanrogalski** [FormidableLabs/spectacle#180]
Any chance you will add CJSX (or less importantly sass) support anytime soon? 

Spectacle is awesome, thanks for building it.

**Comment by ryanrogalski** [comment]
Closing this as I added my own cjsx support, if you want me to make a PR just say the word.

**Comment by kenwheeler** [comment]
Not sure it merits core support, but a cjsx boilerplate would be cool if you want to share it. Its just loaders right?
