### ISSUE TITLE
Roadmap Discussion: Feedback Wanted

### ISSUE THREAD

**Issue by kenwheeler** [FormidableLabs/spectacle#183]
Here is the proposed Spectacle roadmap. Any input, suggestions or feedback would be greatly appreciated!
# Spectacle Roadmap
## 1.1.0
- Update core and boilerplate to React v15
- Update code to ES6 & stateless functional components where possible
- Update dependencies
- Move off of markdown fork

Here is the current proposed roadmap for Spectacle development moving forward. Any input, suggestions or feedback would be greatly appreciated.
## 1.2.0
- Pluggable animations for transitions
- Externalize history with wrapper
- Routing for Appear
- Slide sets
## 2.0.0
- Selection of base themes
- Better export (w/ notes)
- Better overview mode
- Better presenter mode
- Overhaul presenter notes
- Plugin/Middleware API
## Spectacle@next
- 3D Slide navigation (left right up and down, like Reveal)
- Remote sync of slides
- Remote control App w/ React Native
- Enhanced Markdown parsing to expose prop based features

**Comment by waywaaard** [comment]
What do you mean by moving of the markdown fork? I try to put a new PR together with a markdown-it based solution for the markdown to spectacle element creation with inline html support.

I think the current routing which always uses the base url is quiet annoying.

**Comment by kenwheeler** [comment]
Right now we take a hard dep on "mdast-react": "git://github.com/jjt/mdast-react.git#2ea3bcd", I'd like to move off a repo based dep for this.

Re: routing using the base URL, in total agreement.

**Comment by pawel2105** [comment]
Hey @kenwheeler 

Nice feature proposals. One thing I'd maybe add as a suggestion for 2.0.0 or future is the ability to replace the Pacman animation. Perhaps options for a simpler dot navigation style similar to this pen: https://codepen.io/larrygeams/pen/filjt

**Comment by pawel2105** [comment]
One more thing:

@bebraw kindly linked [one of his presentations](https://survivejs.github.io/how-to-write-a-book-and-survivejs-it/#/5?_k=7gdlwo) in the examples issue. There seems to be a FOUC for slides that have image elements underneath text. Notice the Module Counts slide - once the image loads it repaints and moves the text up. See attached gif*:

![example gif](https://media.giphy.com/media/alwHYEbHVumnm/giphy.gif)

Possible solution would be to maybe inject a transparent gif with the same dimensions that gets replaced when the asset loads. Or is this overthinking a pain point that isn't really a pain point? For reference I'm in 🇿🇦 browsing on a 4G connection and unfortunately still suffer from poor latency.

* The gif doesn't do a good job of portraying the severity of the jolt, but it's very noticeable.

**Comment by ssssssssssss** [comment]
What about having a presentation render for React Native?

**Comment by 0xR** [comment]
I think it should be possible to run your entire presentation offline. So no more CDN's in the bootstrap. Maybe download the custom fonts during `postinstall`. It would also make the problem with slow images less visible.

**Comment by jo12bar** [comment]
Is the autoplay feature discussed in #42 still of interest? If it is, and no one else is working on it, I'd be willing to give it a crack.
