### ISSUE TITLE
Discussion: Ability to run a Jupyter notebook code block inside a Spectacle slide

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/spectacle#184]
Can we integrate [thebe](https://github.com/oreillymedia/thebe) to support Jupyter Notebook nodes inside Spectacle?

Whomever wants to run a presentation like this would have to provide an ipython notebook server endpoint via some configuration.

What would be needed to pull this together? What are the complexities that I'm overlooking? Can we bring even more Jupyter functionality into Spectacle?

**Comment by kenwheeler** [comment]
I'll look into this.

**Comment by coopy** [comment]
I'm thinking this type of feature should be provided as a separate installable component much like https://github.com/thejameskyle/spectacle-code-slide

**Comment by captainsafia** [comment]
Hello! I'm a contributor on the [nteract](https://github.com/nteract/nteract) project and I think I might have some pertinent info. nteract is a desktop-based version of the Jupyter interactive notebook that is built using React. One of our initiatives is separating some of the React components used in the application and making them importable in other contexts ([link](https://github.com/nteract/initiatives/tree/master/react-components)). Another is the ability to connect a Notebook or a cell to a remote kernel ([link](https://github.com/nteract/initiatives/tree/master/remote-kernels)).

These are all on the roadmap, but the idea is that hopefully you'll be able to bring an executable code cell into any React-based application. I can't promise you anything immediate or in the near future but it is definitely possible and doable with some people power on it.

**Comment by kenwheeler** [comment]
Closing for now, keeping on the table as a separate addon component
