### ISSUE TITLE
Using facebookincubator/create-react-app instead of boilerplate

### ISSUE THREAD

**Issue by mrpatiwi** [FormidableLabs/spectacle#188]
Even when https://github.com/FormidableLabs/spectacle-boilerplate seems to be a good starting point, it has a lot of code for a simple presentation.

I was able to make [`presentation/index.js`](https://github.com/FormidableLabs/spectacle-boilerplate/blob/master/presentation/index.js) from `spectacle-boilerplate` work with https://github.com/facebookincubator/create-react-app and now the presentation source code is much more compact and easy to follow.

Currently there is [problem when loading external css code](https://github.com/facebookincubator/create-react-app/issues/103), but it has been patched and maybe it will come with the next release.

Steps (when `create-react-app` gets updated):

``` sh
npm install -g create-react-app

create-react-app my-app
cd my-app

npm install --save normalize.css spectacle
```
- Copy `spectacle-boilerplate/presentation/index.js` to `my-app/src/App.js`
- Copy `spectacle-boilerplate/assets/interactive.js` to `my-app/src/interactive.js`
  - Change `import Interactive from "../assets/interactive";` to `import Interactive from "./interactive";` in `my-app/src/App.js`.
- Copy the rest of `spectacle-boilerplate/assets` to `my-app/assets`.

I had to remove `raw-loader` because it's not bundled by default

``` js
{/*
          <CodePane
              lang="jsx"
              source={require("raw!../assets/deck.example")} // :(
              margin="20px auto"
            />
*/}
```

Run `my-app` with `npm start`.

![image](https://cloud.githubusercontent.com/assets/7570744/17123622/d95e97ca-52b2-11e6-931f-f922e4d22ca1.png)

**Comment by kenwheeler** [comment]
We are working on a CLI tool much like CRA, but that also includes presentation specific features like remote sync.

**Comment by jonasws** [comment]
Any update on the progress of said CLI tool, @kenwheeler?

**Comment by kenwheeler** [comment]
@jonasws expect it pretty soon. It will likely be based off of https://github.com/FormidableLabs/builder-init/

**Comment by karlhorky** [comment]
Now that [`create-react-app` is going away](https://github.com/reactjs/react.dev/pull/5487#issuecomment-1409720741) (it's turning into a launcher), I opened an issue to remove the `create-react-app` option from [the tutorial in the docs](https://formidable.com/open-source/spectacle/docs/tutorial) and consider moving to Next.js:

- https://github.com/FormidableLabs/spectacle/issues/1260
