### ISSUE TITLE
Adding a video

### ISSUE THREAD

**Issue by davej** [FormidableLabs/spectacle#19]
What's the best way to go about adding a video to a slide?

**Comment by kenwheeler** [comment]
You can just throw one in. You mean like YouTube or locally hosted video tag?

**Comment by davej** [comment]
Locally, specifically how do I make it available to dev server? If I require it then I get a parse error.

**Comment by kenwheeler** [comment]
Hmm, I might try using https://github.com/webpack/file-loader for this

**Comment by kenwheeler** [comment]
Let me know if that works out for you

**Comment by davej** [comment]
Couldn't get it working :-/

**Comment by kenwheeler** [comment]
@davej got a repo I can look at? Is the video 404'ing?

**Comment by davej** [comment]
Got it working with `ogv` for some reason it wasn't working with `mp4`. Issue I'm having now is that the style attribute on the `video` is getting parsed weirdly. I'm not familiar with react/jsx so that is probably obvious

jsx: `<video src={video} style="height:70vh;"></video>`
Compiling to ->
html: `<video src="3959600e6c93efcb28ee0d6f798eff69.ogv" style="0:h;1:e;2:i;3:g;4:h;5:t;6::;7:7px;8:0px;9:v;10:h;11:;;"></video>`

**Comment by kenwheeler** [comment]
You are gonna wanna write:

```
style={height: '70vh'}
```

**Comment by kenwheeler** [comment]
Sorry on mobile:
```
style={{height: '70vh'}}
```

**Comment by davej** [comment]
Thanks!

For posterity: `var video = require('file!./my-video.webm');`

**Comment by kenwheeler** [comment]
Np!

**Comment by shreyasbharath** [comment]
Another newbie here, can you provide a full example of how to embed a video in a slide?

I can add it to the docs.

**Comment by jlbribeiro** [comment]
Slightly related to this is the idea of a full-width video/background video (optionally in loop). Not sure if it would make sense supporting this as first class citizen (couldn't find another issue mentioning this) or if it should be achieved only through a `<video>` tag, but I'm having some difficulty getting it to work seamlessly in full screen (without paddings/margins), stretched to fit like background images do. Any thoughts?

**Comment by marcysutton** [comment]
I am also looking for full-screen video just like images, FWIW
