### ISSUE TITLE
Granular themes

### ISSUE THREAD

**Issue by pawel2105** [FormidableLabs/spectacle#190]
Hey team 👋🏼

Currently themes are injected into the Spectable element `<Spectacle theme={theme}>`. Was there a previous discussion that concluded that slide-level themes would be a bad idea? Subtle color alterations provide great emotional impact for presentations with a strong narrative thread.

Would something like `<Slide theme={theme}>` be out of the question? If so, what recommendations would be proposed to best hack around slide based theme attribute editing?

**Comment by kenwheeler** [comment]
I can add that.

**Comment by kenwheeler** [comment]
This will be easier the new theme API, but not done this way
