### ISSUE TITLE
Expose prop to drive current slide

### ISSUE THREAD

**Issue by Koleok** [FormidableLabs/spectacle#192]
Is there a _best/existing_ way to pass a prop _(from my top level redux store)_ To `<Spectacle/>` or `<Deck/>` that would drive which slide is shown?

I have attempted to pass a mock `route` object computed from my redux store that contains a `slide` key, which doesn't quite do the trick.

Passing history works ok, but that necessitates that I use a custom middleware to drive `history.push`'s at the top level in response to my own inc/dec slide hooks, which is both a little messy, and breaks the ability to rewind using the redux devtools.

Any thoughts?

**Comment by Koleok** [comment]
It seems like the context key [`slide`](https://github.com/FormidableLabs/spectacle/blob/master/src/components/deck.js#L52) is present to provide this functionality, but it is never used anywhere else in the component.

**Comment by ebrillhart** [comment]
Hi! In an effort to focus on more recent bugs and requests, we're closing all open issues more than a year old, with some exceptions. If your issue is closed, and you still feel strongly about it, please feel free to reopen it or submit a PR with the change!
