### ISSUE TITLE
Z-index issue on slide transitions

### ISSUE THREAD

**Issue by davidkpiano** [FormidableLabs/spectacle#20]
I noticed that when going from one slide to another in the reverse direction, the previous slide overlaps the current slide being transitioned, resulting in an undesired (?) visual effect.

Steps to reproduce:
1. Transition from 1st slide to 2nd slide.
2. Transition from 2nd slide back to 1st slide. Notice how the 1st slide is above the 2nd slide in transition, even though it was below on initial transition (which I assume is the desired visual effect).

<img width="1397" alt="screen shot 2015-07-04 at 3 51 41 pm" src="https://cloud.githubusercontent.com/assets/1093738/8509205/cc3e3994-2264-11e5-801c-3180babce1f9.png">

Tested on Chrome latest.

**Comment by kenwheeler** [comment]
Nice catch. I'll put logic in to determine direction and set that correctly.

**Comment by kenwheeler** [comment]
I actually think this behavior is correct. Any time a slide is being transitioned _to_ , it takes z precedence, while transitioning out always drops a level. Right?

**Comment by kenwheeler** [comment]
Ok I'm seeing some zIndex inconsistency, fixing now.

**Comment by davidkpiano** [comment]
@kenwheeler much thanks, great work!

**Comment by kenwheeler** [comment]
Hey, while we're here, I switched from left to translate, seeing improved perf on your phone?

**Comment by davidkpiano** [comment]
Yeah, it feels a bit smoother, although (and you might notice this too) sometimes there's still a little bit of jank, though this is probably the fault of `react-tween-state`. I can take a deeper look and see if any optimizations can be made to give it a super smooth transition.

**Comment by kenwheeler** [comment]
I might try and switch to batching the updates, might speed things up

**Comment by kenwheeler** [comment]
Ok Z's should be all set on master
