### ISSUE TITLE
Changing lineHeight for Text is not possible

### ISSUE THREAD

**Issue by waywaaard** [FormidableLabs/spectacle#202]
I am not sure if I've understood everything, but it seems that it is impossible to set the `lineHeight` to another values inside the `screen.js` for `text` or a heading.

The `lineHeight` will be always `1`. I think, the problem is the `noneFit` style that gets the `lineHeight` from the parent. In my case the parent does not have any `lineHeight` and hence it always overrides the styles set in the `screen.js`.

**Comment by kenwheeler** [comment]
I'll check it out. For the Fit text, the lineHeight is important. for non-fitText, it doesn't really matter.

**Comment by kenwheeler** [comment]
@waywaaard the `style` prop should take precendence here?

https://github.com/FormidableLabs/spectacle/blob/master/src/components/text.js#L77

**Comment by waywaaard** [comment]
But the styles from `screen.js` are retrieved by `getStyles()`, right?

**Comment by sebald** [comment]
Ran into the same problem :-/ Would be nice to have a default `lineHeight` for `<Text>` and `<Markdown>`.

**Comment by waywaaard** [comment]
@sebald You have to pass it as a property in order to override it (works only if you do not use the `fit` prop).

**Comment by sebald** [comment]
@waywaaard Thx, I actually just checked the source code and found it :) **But** this only works for `<Text>` not for `<Markdown>` :-/
