### ISSUE TITLE
Invariant Violation: Hash history needs a DOM

### ISSUE THREAD

**Issue by costaoeste** [FormidableLabs/spectacle#203]
Im trying to use this cool lib on my react-meteor app but im getting this error.
Any idea? :)

W20160921-14:26:28.671(2)? (STDERR) Invariant Violation: Hash history needs a DOM
W20160921-14:26:28.671(2)? (STDERR)     at invariant (webpack:///~/invariant/invariant.js:45:1)
W20160921-14:26:28.671(2)? (STDERR)     at createHashHistory (webpack:///~/history/lib/createHashHistory.js:64:1)
W20160921-14:26:28.672(2)? (STDERR)     at Object.defineProperty.value (webpack:///imports/src/utils/controller.js:11:1)
W20160921-14:26:28.672(2)? (STDERR)     at **webpack_require** (webpack:/webpack/bootstrap b8af76864007666401ee:22:1)
W20160921-14:26:28.672(2)? (STDERR)     at Object.defineProperty.value (webpack:///imports/src/components/spectacle.js:7:1)
W20160921-14:26:28.672(2)? (STDERR)     at **webpack_require** (webpack:/webpack/bootstrap b8af76864007666401ee:22:1)
W20160921-14:26:28.673(2)? (STDERR)     at Object.defineProperty.value (webpack:///imports/src/index.js:20:1)
W20160921-14:26:28.673(2)? (STDERR)     at **webpack_require** (webpack:/webpack/bootstrap b8af76864007666401ee:22:1)
W20160921-14:26:28.674(2)? (STDERR)     at Object.defineProperty.value (webpack:///imports/routes/WizardForClients.js:5:1)
W20160921-14:26:28.674(2)? (STDERR)     at **webpack_require** (webpack:/webpack/bootstrap b8af76864007666401ee:22:1)

**Comment by kenwheeler** [comment]
Hmm. are you trying to render it server side or something?

**Comment by costaoeste** [comment]
No, im importing the elements to a single page

**Comment by kenwheeler** [comment]
Looks like ReactRouterSSR is indeed trying to server render it. Server rendering is not available for spectacle at this time.
