### ISSUE TITLE
Setting Custom Downloaded Fonts??

### ISSUE THREAD

**Issue by jakesorce** [FormidableLabs/spectacle#204]
Having issues trying to figure out how to set custom fonts for the whole theme. Any guidance would be helpful.

Thanks!

**Comment by kenwheeler** [comment]
Right now you can add them in the boilerplate index as shown here: https://github.com/FormidableLabs/spectacle-boilerplate/blob/master/index.html#L7 , and then edit your theme to set primary/secondary fonts https://github.com/FormidableLabs/spectacle/blob/master/src/themes/default/screen.js#L11
