### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by 0xR** [FormidableLabs/spectacle#207]
Relying on conference wifi for your presentation is a risk I can do without. Are there any plans to remove the reliance on CDN's to run your presentation?

**Comment by kenwheeler** [comment]
Absolutely. This is a P1 feature that will be resolved soon.

**Comment by kenwheeler** [comment]
Offline support is possible by using local versions of prism

**Comment by 0xR** [comment]
Thanks for looking into it!
