### ISSUE TITLE
Vector Icon Support

### ISSUE THREAD

**Issue by BrandonBoone** [FormidableLabs/spectacle#209]
I'm looking into adding the [fontawesome](http://fontawesome.io/icons/) vector icon set to my presentation. It would be great if [vector icon](http://tagliala.github.io/vectoriconsroundup/) support was built and configurable (perhaps as part of the theme option). If I get it working I'll submit a pull request.

**Comment by kenwheeler** [comment]
Is there a configuration preventing it from working properly? I'm wary to add it to core, but totally open to removing any friction to adding it.

**Comment by BrandonBoone** [comment]
There wasn't anything in the project that was actually blocking me from accomplishing this. For whatever reason, my initial thinking was that I needed to have an `<Icon>` component to render `<i class=""></i>` baked into the library. I actually [did create this component](https://gist.github.com/BrandonBoone/fb8d3d7e7bf813f8f75e0e789c4b34d1) (*basically a copy and past of another component*), and using the [boilerplate](https://github.com/FormidableLabs/spectacle-boilerplate/) as a template, I added [font-awesome](https://www.npmjs.com/package/font-awesome) and [font-awesome-webpack](https://www.npmjs.com/package/font-awesome-webpack). In hindsight, this was probably overkill as I could have just used an `<i className=""></i>` directly and perhaps even just pulled fontawesome from a CDN.... :-/

Oh, well... It's working nonetheless, and the presentation [went over well!](https://twitter.com/brandonjboone/status/784208567058432001). 

Anyway, fontawesome does pair rather nicely. While it may be overkill for the core library, you could consider it for the boilerplate.

![image](https://cloud.githubusercontent.com/assets/5246918/19313483/9e05444a-9064-11e6-83ac-b95baa52c8ec.png)
