### ISSUE TITLE
Increase font-size for CodePane

### ISSUE THREAD

**Issue by just-boris** [FormidableLabs/spectacle#211]
Usually, I don't put a lot of code on my slides because nobody cares to read this all.
So there are only essentials, and code looks very small and hard to read:

![image](https://cloud.githubusercontent.com/assets/812240/19129824/00c94bc4-8b49-11e6-931f-ed16c50129fe.png)

So far I couldn't find any property to customize this. Maybe I missed something? If not, that would be nice to have an ability to adjust font-size.

**Comment by alexandercbooth** [comment]
Hi @just-boris,

Spectacle uses prism for code highlighting so you could just override the defaults in the way they recommend. 

For example, in your index.html file you could include:
```html
  <style>
  .language-jsx,
  .style {
    font-size: 4em;
  }
  </style>
```

with the following slide, 
```jsx
<Slide bgColor="black">
          <Text fit textColor="secondary">
            With default font size
          </Text>
          <CodePane lang="jsx">
             import React from "react";
          </CodePane>
</Slide>
```
which by default looks like this:
<img width="1186" alt="screen shot 2016-10-11 at 10 01 49 am" src="https://cloud.githubusercontent.com/assets/15242567/19273467/9fb08f54-8f9a-11e6-9d5c-8d45ffde138f.png">

And once you add in the css to the html file:
<img width="1188" alt="screen shot 2016-10-11 at 10 02 36 am" src="https://cloud.githubusercontent.com/assets/15242567/19273504/c87b2fd4-8f9a-11e6-9967-05c4f670882d.png">

I am sure there are other (probably better) ways to do it, but that was what seemed the most straightforward to me. 

Here's a link to prism's faq where they mention this: http://prismjs.com/faq.html

Hope it helps.

**Comment by just-boris** [comment]
@alexandercbooth well, that works, I have used some similar workaround in my presentation.

But the concept of component-based presentation means that you should not touch styles directly. For example, now you can specify `Heading` size with the respective prop, so I'd like to do the same for code block.

This is why I created this issue.

**Comment by kenwheeler** [comment]
You should be able to adjust it at the theme level like you see here: https://github.com/FormidableLabs/spectacle/blob/master/src/themes/default/screen.js#L170-L192

**Comment by just-boris** [comment]
@kenwheeler should I create a new theme for that?

So far I am using default and I pretty happy with it, except code examples, as I showed on screenshot in my initial comment.

**Comment by kenwheeler** [comment]
you could just extend the current one and pass it explicitly via `{...theme, code: {}}` or something to that effect.

**Comment by just-boris** [comment]
Well, that solves the question how to change code font size at one place and apply this everywhere.

But there is one more question: are you happy with current defaults? Now the code looks very small comparing to other texts size.

Also, you can look at [Shower](https://shwr.me/#7) – another presentation framework, that has better text/code size ratio, IMO.

**Comment by kenwheeler** [comment]
We're planning a ton of improvements to land before the new year, and a better default theme + more theme selection is definitely on that list.

**Comment by just-boris** [comment]
Now that's clear, thank you for elaboration!

**Comment by NicholasAaronBrady** [comment]
old thread.. but I looked here while trying to find the answer. You can pass `textSize={20}`
```
          <CodePane
            textSize={20}
            className="code-blocks"
            lang="javascript"
            source={code}
          />
```
