### ISSUE TITLE
How to test our PR ?

### ISSUE THREAD

**Issue by chabou** [FormidableLabs/spectacle#213]
I'd like to push some PRs, but it is hard to test my changes.
After commit f49af61 and b6658d0, we can't run example anymore.

webpack's config is looking for an index file which has been deleted...

What is your workflow ?
Can you add a Contribute section to the doc or explain me how to run spectacle itself (with an example) in order to test my spectacle's code changes ?

**Comment by kenwheeler** [comment]
Just reverted the commit that borked that, `npm start` should be all set now
