### ISSUE TITLE
Support for footers

### ISSUE THREAD

**Issue by Naoto-Ida** [FormidableLabs/spectacle#215]
Hi, are there any plans for supporting footers, i.e. company logo, copyright, etc.?
I'd love to use this for an upcoming developers event in Tokyo.

**Comment by chabou** [comment]
Workaround : 
You can try to put this in index.html file.
I did this, to put my company logo on top left (position absolute) on every slide.

**Comment by Naoto-Ida** [comment]
@chabou Thanks for the simple solution!

**Comment by dbendy** [comment]
@chabou: can you please share your solution again?  I don't see it in your comment above.  Thanks!

**Comment by chabou** [comment]
I didn't share code. Only the idea that putting whatever in index.html will make it visible on all slides :)
