### ISSUE TITLE
Custom presenter styling

### ISSUE THREAD

**Issue by jonasws** [FormidableLabs/spectacle#216]
A concern stated in #214: People have different needs on how they rely on the presenting mode.

@kenwheeler Has there been any discussions on whether to add the ability to override the way the `Presenter` component is styled? Perhaps something like this:

``` jsx
// In a presentation
 <Deck presenterStyles={someStyleObject}>
...
</Deck>
```

Doesn't Radium have some sort of support for this, in that one can pass a list to the `styles` prop in a decorated component?

Potentially even adding a number of "presets", that focuses on which part of the presenting mode should be focused (One example is to enlarge the presenting notes, if present).

**Comment by kenwheeler** [comment]
Refactoring the theme system in 3.0 which will take this into account
