### ISSUE TITLE
Can only export first page of slides to PDF

### ISSUE THREAD

**Issue by hkrutzer** [FormidableLabs/spectacle#218]
I cloned the boilerplate repo, and went to http://localhost:3000/?export, which redirects to http://localhost:3000/?export#/?_k=smh7pe. If I try to export this to PDF using the Print dialog (Chrome on OSX), I only get the first slide.

![image](https://cloud.githubusercontent.com/assets/3464899/19559510/83c02736-96d0-11e6-9a13-7a58d644c419.png)

**Comment by flexzuu** [comment]
Instead go to `http://localhost:3000` and hit enter. 
You will get redirected to something like `http://localhost:3000/#/?_k=wu0uco`.
Now add `?export` like: `http://localhost:3000/#/?_k=wu0uco?export` and you are ready to print. You can even add `&print` to get `http://localhost:3000/#/?_k=wu0uco?export&print` for a black white version.

**Comment by hkrutzer** [comment]
Thanks! That worked
I feel like the docs can be improved here, there is a direct link to http://localhost:3000/?export in README.md, and one to http://localhost:3000/?presenter which doesn't work either.

**Comment by flexzuu** [comment]
Yeah ?presenter is the same again you need to add it after the hash. 
Maybe we need to make that more clear in the docs.

**Comment by hkrutzer** [comment]
Someone in Gitter was having this problem as well, so I made a PR. Redirecting might be better though.

**Comment by kenwheeler** [comment]
Closing pending merged PR
