### ISSUE TITLE
[Feature Request] Live Editing / Preview

### ISSUE THREAD

**Issue by FrancisMurillo** [FormidableLabs/spectacle#219]
I'm using this tool to make a presentation about react and I usually show a code snippets about components. Just to impress people while talking, it would be nice to edit the displayed snippet and an updated component is displayed.

I have tried without success getting live preview to work but I only have so much time, so I am stuck showing a slide of the code then a slide of the component.

This may be more of a external component but it would be nice if it were easy to show or some links in pointing how to do this. This is similar to #184 I think.

**Comment by kenwheeler** [comment]
We do that using https://github.com/FormidableLabs/component-playground . That said, this will be built into core in the very near future.
