### ISSUE TITLE
background color slightly lighter for some elements

### ISSUE THREAD

**Issue by albertbuchard** [FormidableLabs/spectacle#222]
Hi, 

I can't find the reason why the background for some of the elements I am using has a slightly lighter color. It can't pinpoint the reason for it.
[Screenshot](http://imgur.com/a/srcYl)

The code is the same as the boilerplate exept for this part : 

```
const theme = createTheme({
  primary: "blue"
});
export default class Presentation extends React.Component {
  render() {
    return (
      <Spectacle theme={theme}>
        <Deck transition={["slide"]} transitionDuration={500} progress="none">
          <Slide transition={["slide"]} bgColor="primary">
            <Heading size={1} fit caps textColor="black">
              Lab Meeting - Round Table
            </Heading>
            <Heading size={1} fill caps textColor="white">
              26.10.2016
            </Heading>
          </Slide>
```

**Comment by kenwheeler** [comment]
I can't see it in the screenshot? Although I know what you mean.

**Comment by rawrmonstar** [comment]
I think this is an optical illusion? Using a color picker all of the blue in the screenshot is `#1024fa`
