### ISSUE TITLE
Convert to Markdown-It

### ISSUE THREAD

**Issue by kenwheeler** [FormidableLabs/spectacle#224]
Currently spectacle relies on a fork of mdast. We should convert our markdown stuff to use https://github.com/markdown-it/markdown-it , in preparation for further fleshing out the markdown experience.

**Comment by kenwheeler** [comment]
cc @carlospaelinck

**Comment by waywaaard** [comment]
I've added a first draft of a markdown-it component for spectacle that supports inline html. See #235
