### ISSUE TITLE
Remove Redux dependency

### ISSUE THREAD

**Issue by kenwheeler** [FormidableLabs/spectacle#227]
We should remove redux, and instead pass a fragment registration function down via context, which can then modify a context driven fragment state.

**Comment by JonathanCooperD** [comment]
After digging into this a while, it appears that Redux is pretty heavily integrated into the app. To strip it out will require some fairly heavy rewriting. I am a bit reluctant to go down that path unless future releases/updates will never need any of the features Redux has to offer. Let me know what you think, I am happy to discus more.
