### ISSUE TITLE
Call For Input: Theming

### ISSUE THREAD

**Issue by kenwheeler** [FormidableLabs/spectacle#229]
Hey EVERYONE. Been debating the merits of switching from inline styles back to a stylesheet based theming approach. Would love to hear what people have to say about that. Thumbs up for CSS, thumbs down for inline styles.

**Comment by kwelch** [comment]
Is there a specific CSS solution in mind to use?

**Comment by kenwheeler** [comment]
not yet, certainly open to suggestions

**Comment by kwelch** [comment]
One thing I really liked with react-toobox is that they apply styling using an HOC and also export the unstyled components. That is one flexible way to handle it, but I am not sure how well that concept would apply to spectacle. Just an idea.

**Comment by kenwheeler** [comment]
I mean, inline styles are an inevitability for things like fragments and transitions. I was thinking more along the lines of class names on markdown generated components and having a style sheet

**Comment by kenwheeler** [comment]
Probably some kind of PostCSS setup

**Comment by kenwheeler** [comment]
I want to keep the main API external API the same though
