### ISSUE TITLE
Feature: Autofit Text with maximum (general limits)

### ISSUE THREAD

**Issue by ebertmi** [FormidableLabs/spectacle#242]
One problem that, I've encountered by generating slides from a jupyter notebook, is that I would like to use autofit (smaller and bigger) on elements but with a maximum/minmum (limits), so that I can assure that my content will always be readable.

**Comment by ebrillhart** [comment]
Hi! In an effort to focus on more recent bugs and requests, we're closing all open issues more than a year old, with some exceptions. If your issue is closed, and you still feel strongly about it, please feel free to reopen it or submit a PR with the change!
