### ISSUE TITLE
Transitionable not working on slides when being composed dynamically.

### ISSUE THREAD

**Issue by ebertmi** [FormidableLabs/spectacle#243]
I am composing a slide deck dynamically by creating `<Slide></Slide>` and passing in the children. After upgrading to the latest version with the new transitions, I could not change slides or use fragments.

My code failed when trying to access the https://github.com/FormidableLabs/spectacle/blob/master/src/components/deck.js#L335 `_renderSlide()` function in `deck.js`. My slides that I created **do not have the transition props** and therefore it fails when trying to access those.

In order to fix this, I had to knock my head on the keyboard and then add the transition prop to my slides like `<Slide transition={[]} ...>...</Slide>` to get it to work.

I am using the `/lib` folder in my application to access the various elements.

**Comment by waywaaard** [comment]
I got a different but maybe related error. The `<Appear>` tag seems to be not working correctly. The state gets updated to be active but the opacity is always `0`. -.-

**Comment by kenwheeler** [comment]
Removed transitionable
