### ISSUE TITLE
Publishing boilerplate build to gh-pages via /docs

### ISSUE THREAD

**Issue by QuantumInformation** [FormidableLabs/spectacle#251]
What is the best way to get this to gh-pages? Ideally I would have a single folder with all the stuff I need in`/docs`.

Just for clarity this relates to boilerplate.

**Comment by kenwheeler** [comment]
You could do something like `git subtree push --prefix docs origin gh-pages`

**Comment by QuantumInformation** [comment]
Thx, what is the easiest way to create the `/docs` folder as an output? All the references point to `/dist`

**Comment by kenwheeler** [comment]
right in the output section of the webpack config
