### ISSUE TITLE
add styling to <S> tag

### ISSUE THREAD

**Issue by NitsanBaleli** [FormidableLabs/spectacle#253]
I seem to not be able to pass Base Props although it is followed by a (Base),

as mentioned [In the docs](https://github.com/FormidableLabs/spectacle#base-props)

Am I missing something?

**Comment by carlospaelinck** [comment]
I am able to base base props into the `<S />` tag. It does require a `type` however.

Here is what I am seeing:
`<S type="bold" italic caps textColor="#ff0" bgColor="#000">Hello</S>`

<img width="86" alt="screen shot 2017-01-26 at 2 41 21 pm" src="https://cloud.githubusercontent.com/assets/1738349/22349498/85a472a8-e3d5-11e6-9c7d-f70732376813.png">
