### ISSUE TITLE
How do I center an image on a slide?

### ISSUE THREAD

**Issue by hackingbeauty** [FormidableLabs/spectacle#254]
Hello, I can't center an image inserted into a slide.  Is there a way to do this?  This is what I'm doing.

```
<Slide transition={["zoom"]} bgDarken={0.75} bgColor="tertiary">
  <Image src={images.myImage} />
</Slide>
```

**Comment by kenwheeler** [comment]
It should be centered by default. If not, you can always add additional styles via the style prop, use Layout/Fit/Fill tags, or just wrap it with regular html like a div with inline styles.
