### ISSUE TITLE
Computable Document | General Document Creation Beyond Just Presentations and Slides

### ISSUE THREAD

**Issue by sirinath** [FormidableLabs/spectacle#259]
Spectacle is a great product! I am hoping you would extend this so that this can be used to represent any Live and Real Time Computational Document akin to [Computable Document Format™(CDF)](http://www.wolfram.com/cdf/)

**Comment by kenwheeler** [comment]
Whoah thats nuts. How would one go about integration? We've discussed having a tool that converts Jupyter notebooks to slides. Is that sort of similar?

**Comment by sirinath** [comment]
Jupyter integration may be similar by Jupyter does not support much user interaction and live data.
