### ISSUE TITLE
When no className is specified in the Slide component, "undefined" is added

### ISSUE THREAD

**Issue by elazzabi** [FormidableLabs/spectacle#261]
Hi,

When using the Slide component without specifying a className prop (code bellow), undefined is added automatically to the div:
``` jsx
<Slide transition={["zoom"]} bgColor="primary">
        // Something    
</Slide>
```
Result:
![](http://i.imgur.com/w0bzRlR.png "Without className")

**Comment by elazzabi** [comment]
The check is done [here](../blob/master/src/components/slide.js#L123), but looks like it's not working :question:

**Comment by rawrmonstar** [comment]
This appears to be resolved.

![image](https://cloud.githubusercontent.com/assets/13814048/26370868/fe5c9da4-3fad-11e7-88b4-1ccd55b7abd0.png)
