### ISSUE TITLE
Codepane syntax colouring not working for certain langages.

### ISSUE THREAD

**Issue by QuantumInformation** [FormidableLabs/spectacle#267]
Tried using bash, typescript and json, but I get no colours:

![image](https://cloud.githubusercontent.com/assets/216566/21645312/71f88fda-d289-11e6-95e3-27a2a4b7b2a0.png)
![image](https://cloud.githubusercontent.com/assets/216566/21645320/7a8eb610-d289-11e6-87e5-26ef1673f92c.png)

**Comment by kenwheeler** [comment]
Are you including the prism css for that language?

**Comment by kenwheeler** [comment]
https://github.com/FormidableLabs/spectacle/blob/master/index.html#L14

**Comment by QuantumInformation** [comment]
that worked!
