### ISSUE TITLE
is there any example of how to test a presentation?

### ISSUE THREAD

**Issue by sibelius** [FormidableLabs/spectacle#270]
I'm writing a presentation about testing using Jest, and I would like to test the presentation slides using spectacle.

I have some trouble with this:

```jsx
Cannot find module 'raw!../assets/code/sum.js' from 'index.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:151:17)
      at Presentation.render (presentation/index.js:165:29)
```

I've tried to have a custom moduleNameMapper, but it did not solved my problem:

```json
"moduleNameMapper": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/fileTransformer.js",
      "\\.(css|less)$": "<rootDir>/__mocks__/styleMock.js",
      "\\raw!": "<rootDir>/__mocks__/fileMock.js"
    }
```

**Comment by kenwheeler** [comment]
Still having this issue? Do you have raw-loader installed?

**Comment by sibelius** [comment]
yep

this is the breaking test: https://github.com/sibelius/jest-everywhere/blob/master/presentation/__tests__/presentation.spec.js#L8

**Comment by kenwheeler** [comment]
whats the failure

**Comment by sibelius** [comment]
the failure is described above: https://github.com/FormidableLabs/spectacle/issues/270#issue-201531580

you can test using `yarn test`

my guess is that this is a problem with jest and raw-loader

**Comment by sibelius** [comment]
I've tried this https://github.com/sibelius/jest-everywhere/blob/master/package.json#L56

but didn't worked it

**Comment by rawrmonstar** [comment]
This doesn't seem to be an issue with Spectacle itself.
