### ISSUE TITLE
Move 'display' to base

### ISSUE THREAD

**Issue by ndelangen** [FormidableLabs/spectacle#273]
I'd like to use `S` and have it `display-block`. Currently I add `style={{display:'inline-block'}}`.

 The `Image` component has a prop to tweak it's css`display`-property.

Maybe `S` should receive the same ability?

Either through adding it specificly to `S` or by moving the `display` prop to `Base`.
I think the latter makes sense.

I haven't made any contributions to spectacle before, but am interested in adding/tweaking this. Would you be interested in a PR, and if so which solution would you prefer?

**Comment by kenwheeler** [comment]
I'm going to remove prop based styling in favor of style tag/styled-components/glamorous type styling, so Base is going away
