### ISSUE TITLE
Update mdast-react dependency?

### ISSUE THREAD

**Issue by markerikson** [FormidableLabs/spectacle#282]
I'm behind a corporate proxy, and it interferes with a lot of stuff.  I was working on a presentation over the weekend, and was able to install Spectacle and all dependencies fine.  However, at work, installing dependencies for my presentation initially failed, because Spectacle currently depends on `"mdast-react": "git://github.com/jjt/mdast-react.git#2ea3bcd"`, and Git/Yarn didn't want to download anything from Github via SSH.

After wasting several hours making random edits to config files, I somehow finally convinced Yarn and Git to actually successfully download the `mdast-react` dependency, but I'm curious why Spectacle currently depends on that specific revision of a fork, rather than the current NPM package.  Looking at the history, the commit is e37fe8f5bb94683b7b9380d0108d7c411881727b , which says "Make mdast dep windows friendly".  Is there any further background on that?  Is there still actually a need for that fork, or can this be updated to point to the current package instead?

**Comment by kenwheeler** [comment]
got rid of it

**Comment by markerikson** [comment]
Cool. Looking forward to the next version of the awesome! :)
