### ISSUE TITLE
How do you run it on a different port than 3000?

### ISSUE THREAD

**Issue by QuantumInformation** [FormidableLabs/spectacle#283]

**Comment by alexrussell** [comment]
Assuming you're using the boilerplate, open up `server.js` and look at [line 11](https://github.com/FormidableLabs/spectacle-boilerplate/blob/e63f846f19cfa2e4525fcd161b9b7319cbcde95a/server.js#L11). Either change it there or pass `PORT` in as an env variable.

If you're not using the boilerplate, then as far as I gather from the docs, you have to write your own dev/build scripts anyway, so change it there.

**Comment by rsp2k** [comment]
Good explanation, this "issue" should be closed.
