### ISSUE TITLE
[question] Can the presentation run without node?

### ISSUE THREAD

**Issue by QuantumInformation** [FormidableLabs/spectacle#287]
Is there a way to export the presentation to a static format that doesn't need to run over node?

**Comment by AlanFoster** [comment]
@QuantumInformation Yes - you can build/deploy your presentation - shown [here](https://github.com/FormidableLabs/spectacle#build--deployment).

For instance, I generally build my static presentation, then upload it to a `gh-pages` branch on github, or place it into the `docs` folder.

**Comment by QuantumInformation** [comment]
thanks!
