### ISSUE TITLE
Problems with require([styles])

### ISSUE THREAD

**Issue by denysdovhan** [FormidableLabs/spectacle#291]
I'm building spectacle presentation with [Brunch](github.com/brunch/brunch). There are problem here. Brunch can't handle `require`ing of styles properly, so I get an error:

![image](https://cloud.githubusercontent.com/assets/3459374/24051430/bbd2b68c-0b3a-11e7-8436-ab7ac6e2aca9.png)

The cause of problem is that `spectacle/lib/components/component-playground.js` require styles, Brunch doesn't `require.register`s them as modules, so error occurs. [Here's where we have problems](https://github.com/FormidableLabs/spectacle/blob/master/src/components/component-playground.js#L26-L30):

```js
import "../themes/default/playground.css";
import "../themes/default/codemirror.css";

// ...

  if (useDarkTheme) {
    require("../themes/default/dark.codemirror.css");
  } else {
    require("../themes/default/light.codemirror.css");
  }
```

These problems present with `spectacle@^2`, in case with `^1` everything works fine because of Radium.

Could you, please, consider replacement of these require by simple `<style>` tags in HTML or with some kind of css-in-js library (Radium in your case)? Keep in mind that this problem weren't present prior to `^2`, so people that use Spectacle with other build systems can't upgrade to new fancy version because of that.

Also, I understand, particularly this is problem with Brunch itself since it doesn't consider css files as modules. We, at Brunch team, are considering it. Here are related issues: brunch/brunch#1684 and brunch/brunch#1473.

Besides, thanks for amazing presentation framework! Really awesome job!

**Comment by philpl** [comment]
@denysdovhan another solution would be to use our prebundled UMD build. So instead of just importing spectacle directly, you could try to alias it to `spectacle/dist/spectacle.js`

The bundle in there is prebuilt using Webpack, so it doesn't actually call require to mount the CSS sheet.

**Comment by ryan-roemer** [comment]
@denysdovhan -- Can brunch just "include" them manually via a config? I'm pretty sure webpack can do that...

@philpl -- Is the order of those CSS files coming in significant?

**Comment by philpl** [comment]
@ryan-roemer it shouldn't no. Those files only add classes that we switch to for prism themes. In fact, we should also just inject them globally.

**Comment by ryan-roemer** [comment]
@philpl -- The emotion-based solution does seem a little cleaner to me.  (We're still in for the `import` problem of the two CSS files at the top though, so not a clean solution here -- does perhaps make it easier to external import in / resolve them maybe if brunch works like webpack alias/externals do). Please ticket out if you like the idea!

**Comment by philpl** [comment]
@ryan-roemer those other CSS imports are gone in the new react-live based version :wink:

**Comment by denysdovhan** [comment]
Seems like legit. Thanks for great support!
