### ISSUE TITLE
Add  support for presentation mode - elapsed time

### ISSUE THREAD

**Issue by shaunwallace** [FormidableLabs/spectacle#292]
It would be a nice feature to see the elapsed time that a presenter is presenting. This is especially helpful when you have been given a limit on the actual time to present. Would be good to get your feedback on the ux @kenwheeler as discussed previously before dev.

**Comment by kenwheeler** [comment]
This looks great. @stefvhuynh can you check this out, and if its all good pull it in?

**Comment by otorrillas** [comment]
@kenwheeler I guess the issue can be closed, as the PR has been merged to master. Cheers!
