### ISSUE TITLE
<Appear> tags will never render in presenter mode

### ISSUE THREAD

**Issue by kstratis** [FormidableLabs/spectacle#293]
It seems that when in presenter mode, the `<Appear>` tags within a `<Slide>` don't properly render. 

After some research, it turns out that the issue occurs only in the version of the master branch. The latest release (2.0.0) is free of such glitch.

<img width="1243" alt="screenshot 2017-04-03 10 13 28" src="https://cloud.githubusercontent.com/assets/1859806/24598893/77864f24-1856-11e7-9160-e7798fef0c85.png">

Related to #294 and maybe #243.

**Comment by rawrmonstar** [comment]
I'm closing this in favor of #294 since #294 includes more discussion on the issue.
