### ISSUE TITLE
Cannot traverse ranges with spectacle-code-slide. Missing slideIndex prop

### ISSUE THREAD

**Issue by ericvicenti** [FormidableLabs/spectacle#310]
I'm playing around with spectacle and @thejameskyle's [spectacle-code-slide](https://github.com/thejameskyle/spectacle-code-slide), but it doesn't entirely work. Its not possible to go 'up' and 'down' between the ranges on a code slide.

I was able to debug and see that CodeSlide's`isSlideActive` method is broken because the `slideIndex` prop is not passed down: https://github.com/thejameskyle/spectacle-code-slide/blob/master/src/CodeSlide.js#L122

So in order to get the ability to go "up" and "down" within the ranges of a CodeSlide, you can return true from isSlideActive, but then as you'd expect, the up and down affects every slide and not just the active one.

@kenwheeler, I can send a PR for the fix, but I'd like to hear how you think it should be addressed.

**Comment by kenwheeler** [comment]
What versions are you using? I've been able to go up and down without a problem?

**Comment by ericvicenti** [comment]
I just used the boilerplate + `npm i --save spectacle-code-slide`

```
    "spectacle": "^2.0.0",
    "spectacle-code-slide": "^0.4.0"
```

**Comment by kenwheeler** [comment]
Interesting, it should be getting passed here https://github.com/FormidableLabs/spectacle/blob/master/src/components/manager.js#L365-L385

Got a gist I can check out?

**Comment by ericvicenti** [comment]
Oh, I see whats happening. I was trying to do this:

```js
class CustomCodeSlide extends Component {
  render() { return <CodeSlide ... />; }
}

export default class Presentation extends Component {
  render() {
    return (
      <Deck>
        <CustomCodeSlide />
      </Deck>
    );
  }
}
```

The fix was easy, but how was I supposed to know that I had to pass this `slideIndex` prop through?? This is why element copying can result in super confusing APIs

```js
class CustomCodeSlide extends Component {
  render() { return <CodeSlide slideIndex={this.props.slideIndex} ... />; }
}
```

**Comment by kenwheeler** [comment]
@ericvicenti yeah wrapping slides has historically been a problem. I should probably get the next version to supply all this with context.

**Comment by amaity** [comment]
@ericvicenti how do I include spectacle-code-slide in spectacle-boilerplate? I am a complete noob.and struggling to get codeslide up and running since the last two days.
