### ISSUE TITLE
Properly display heading + full page gif?

### ISSUE THREAD

**Issue by FezVrasta** [FormidableLabs/spectacle#311]
So, I would like to have a slide with a big heading and below, a gif as large as possible to cover the available space.

If I simply add an `<image />` component this is what I get:

![image](https://cloud.githubusercontent.com/assets/5382443/25772401/54b05dcc-326a-11e7-90c0-8cb6b53cfaae.png)

The image simply takes the size of its original dimensions.

If I set `height="100%` nothing changes.

Is there a suggested way to handle this (I think common) case or do I have to use the `vh` size and subtract manually the size of the heading?

**Comment by kenwheeler** [comment]
You want to use the bgImage prop on Slide for that

**Comment by kenwheeler** [comment]
Oh wait, you want the header not on top of it?

**Comment by FezVrasta** [comment]
Yup I want header + image below.
I created this to do so: https://fezvrasta.github.io/spectacle-image-slide/

**Comment by kenwheeler** [comment]
Oh cool, PR it to the README

**Comment by FezVrasta** [comment]
https://github.com/FormidableLabs/spectacle/pull/321
