### ISSUE TITLE
Custom bullet character in unordered ListItem

### ISSUE THREAD

**Issue by glennreyes** [FormidableLabs/spectacle#312]
Is there a way to specify a custom bullet character in an unordered `ListItem`? It would be nice to replace the circle with a dash or even with an emoji. If we want that, I would be happy to send a PR that adds that!

Thank you for this project! ❤️

**Comment by kenwheeler** [comment]
You can add a list-style-type via a style prop

**Comment by glennreyes** [comment]
`list-style-type` is great for default bullet characters like square, circle, etc. but it doesn't allow me to replace it with custom characters eg. an emoji. For emoji's for example, I would need either an image or workaround with pseudo selectors.

It would be awesome if we had something like `<List type="✅">` instead 👍
