### ISSUE TITLE
Notes Component

### ISSUE THREAD

**Issue by kwelch** [FormidableLabs/spectacle#322]
Are you open to the idea of a `Notes` component that would allow adding notes within the slide instead of as a prop. This would allow for leveraging JSX for the notes. 

I would expect that the `Slide` would use (something like) `React.Children.toArray().filter(c=> c!=Notes)`

**Comment by codepunkt** [comment]
#kwelch any chance my PR does what you need? :)

**Comment by kwelch** [comment]
Will review Monday. Thanks!

**Comment by kwelch** [comment]
My bad for forgetting to review, but this is exactly what I was hoping for. Awesome 🎉
