### ISSUE TITLE
image paths don't play nice with deployment to GitHub Pages

### ISSUE THREAD

**Issue by jebeck** [FormidableLabs/spectacle#326]
With recent Spectacle (version 4.6.1), the image paths are now `/dist/...` rather than `./dist/...` (as they were in ^1.0.0, which I guess is the last time I published a Spectacle deck to GitHub pages... 😮 ) This path change resulted in all broken images when I deployed via GitHub pages.

I fixed manually by changing directly in the bundle(!) (because (a) slide deck, not production software, and (b) lazy):
<img width="1000" alt="screenshot 2017-06-02 21 52 36" src="https://cloud.githubusercontent.com/assets/1588547/26742414/e05511d2-47dd-11e7-8595-60818f17c2bc.png">

Perhaps something to think about as a configuration option for next version? Or I could open a PR on the docs to add info/a warning about this if you like.

**Comment by kenwheeler** [comment]
Can you PR this?

**Comment by jebeck** [comment]
PRed in #334!

**Comment by MikeDabrowski** [comment]
I'm affraid this fixes only <Image>. Images added as Slide background become broken after such fix.
