### ISSUE TITLE
Make CodePane support vertical scroll bars

### ISSUE THREAD

**Issue by shreyasbharath** [FormidableLabs/spectacle#327]
First of all, let me say I love Spectacle! 

I have switched over from PowerPoint to Spectacle and I am now using it to author a technical presentation with lots of code examples.

One of the issues I noticed with CodePane was rendering when the examples don't fit vertically on a slide. It doesn't seem to add a vertical scrollbar. However, it does add a horizontal scrollbar for examples that don't fit horizontally.

A vertical scroll bar would be pretty neat!

**Comment by kenwheeler** [comment]
Care to PR with a max height and overflow scroll?

**Comment by shreyasbharath** [comment]
Sure I can give it a shot. I am new to JS/NodeJS/React so please bear with me.
