### ISSUE TITLE
Progress bar not visible when background white

### ISSUE THREAD

**Issue by shreyasbharath** [FormidableLabs/spectacle#328]
None of the progress indicators (pacman, bar, number) are visible when the slide background colour is white.

Maybe let the user pick the colour of the progress indicators too?

**Comment by kenwheeler** [comment]
You can override it with a theme
https://github.com/FormidableLabs/spectacle/blob/master/src/themes/default/screen.js#L138-L142

**Comment by shreyasbharath** [comment]
Thanks, it would be great if this was documented too.
