### ISSUE TITLE
Presenter Mode

### ISSUE THREAD

**Issue by waywaaard** [FormidableLabs/spectacle#33]
The interactive slides do not sync in the presenter mode.

Open up the demo and go to the slide with the button. Open another tab and click in the preview on the button. The two states are not being synced.

**Comment by kenwheeler** [comment]
Technically, they are two instances of the same slide, but the embedded component is using component local state. Not sure if it would be possible or worth it to try to sync the two.

**Comment by waywaaard** [comment]
I am not really profound with react and flux. Do the slide share a common context? When they do, then it would be easy to change the behavior. It is not really required, I just noticed this while playing around.

**Comment by kenwheeler** [comment]
If you look at the `interactive` component, the click count variable is stored in the component local state via `setState`. So each new instance of that component, for example in presenter mode or overview,  or after mount/unmount, will have its own instance specific internal state. You could sync them up if you wanted to, by storing that data in a flux store and pushing the data to the other window in the localStorage callbacks.
