### ISSUE TITLE
analytics

### ISSUE THREAD

**Issue by travi** [FormidableLabs/spectacle#331]
I'd like to track how far visitors get through slides for presentations that I've hosted online with something like [react-ga](https://github.com/react-ga/react-ga), but I'm having a hard time figuring out how to detect when a transition happens between slides. 

Is there a simple way to bind to the slide transition and determine the slide number that I'm overlooking?

**Comment by kenwheeler** [comment]
the on-active prop in the other issue should solve this, closing as a dupe

**Comment by travi** [comment]
is #324 the other issue you're referring to? seems like that could do the trick
