### ISSUE TITLE
`transition` doesn't work when slide is in subcomponent

### ISSUE THREAD

**Issue by mAAdhaTTah** [FormidableLabs/spectacle#340]
If I have a Deck like this:

```jsx
    <Deck transition={['slide']} transitionDuration={500} theme={theme}>
        <Slide transition={['slide']}>
            <Heading size={1} fit lineHeight={1}>
                About Me
            </Heading>
        </Slide>
    </Deck>
```

it works fine, but if I extract the `Slide` into a separate component:

```jsx
export class AboutMe extends React.Component {
    render() {
        return (
            <Slide transition={['slide']}>
                <Heading size={1} fit lineHeight={1}>
                    About Me
                </Heading>
            </Slide>
        );
    }
}
```

the transition stops working and the slide never... slides in. If I remove the transition, the slide appears in the correct place, but no animation.

**Comment by mAAdhaTTah** [comment]
Hacky workaround: convert the slide from a ES6 class component to a stateless function component and render it by calling the function, rather than passing the function around as a component:

```jsx
    <Deck transition={['slide']} transitionDuration={500} theme={theme}>
        <Slide transition={['slide']}>
            <Heading size={1} fit lineHeight={1}>
                Meet
            </Heading>
            <Heading size={1} fit lineHeight={1}>
                <code>brookjs</code>
            </Heading>
            <Text textSize={'40px'}>
                A framework for building streaming web applications.
            </Text>
        </Slide>
        {AboutMe()} <--- here
    </Deck>
```

**Comment by kenwheeler** [comment]
yeah, there isn't a good way around that right now. working through this category of issues, trying to find a good way to not have to recurse too far.

**Comment by mAAdhaTTah** [comment]
Heuristically, 2 or 3 levels should probably be enough. I'm mostly extracting a single slide into a separate component or a group of slides into a component. It hasn't gotten deeper than that in my experience.

**Comment by mAAdhaTTah** [comment]
This is not resolved in 4.0.0. Is this intended to work?

**Comment by philpl** [comment]
@mAAdhaTTah No, it's still not resolved. I've actually started to think about this and how we can solve it, but it's unfortunately really tricky. We're trying to bridge the gap between the transition group in the Manager and the Slide component. So right now there must not be any wrapping components in-between those, so the transition methods can be called on the slide, which then manages its own transition.

**Comment by ahfarmer** [comment]
@kenwheeler 

> trying to find a good way to not have to recurse too far

Can't you recurse until you hit a `<Slide>`?
I'm new to Spectacle but it looks like these are the only components that ever exist within `<Deck>`:

* Slide
* SlideSet
* Intermediate component that renders Slide components or other intermediate components

First thing I tried to do when I got the boilerplate was to put my slides into separate files and it was pretty frustrating.
