### ISSUE TITLE
Slides in Overview Mode are not clickable

### ISSUE THREAD

**Issue by waywaaard** [FormidableLabs/spectacle#35]
I would expect that I can click on the desired slide that i want to switch to.

**Comment by kenwheeler** [comment]
So those slides are real slides, and with that, are actually clickable. So clicking won't happen, but what do you think about hitting enter to exit?

**Comment by waywaaard** [comment]
Can't we just put an overlay over the slides? Or at least make them selectable?

**Comment by knowbody** [comment]
I'm not really sure about this feature. You don't really use your mouse when you are presenting, do you? Is there any specific use case I'm not seeing here @waywaaard?

**Comment by MarkRedeman** [comment]
@knowbody it can be nice to use an overview when answering questions after the presentation (instead of having to either remember the slide number or having to "scroll" to some slide mentioned during the question).

**Comment by kenwheeler** [comment]
Overview mode sucks right now. For 1.0.0, lets do a scrollable grid of slides that are clickable.

**Comment by pedrottimark** [comment]
@kenwheeler Similar to Light Table view in Keynote or Slide Sorter view in PowerPoint?

@MarkRedeman In Keynote, if you double-click a slide in Light Table view it displays that slide in whichever single-slide view was active most recently (for example, Navigator, Slide Only, or Outline). How would you apply that analogy to Spectacle for the use case you describe?

And worth thinking what simple-minded fall-back might occur to a flustered presenter? When I needed to do answer a question several weeks ago, what occurred to me in the moment was switch to Navigator view, scroll up the single column of thumbnails, click the slide, and then play the presentation at that point.

**Comment by kenwheeler** [comment]
Fixed on master
