### ISSUE TITLE
Slides with content aligned to top get pushed down in presenter mode

### ISSUE THREAD

**Issue by ceckenrode** [FormidableLabs/spectacle#351]
Whenever you set the vertical align of a Slide to "flex-start", everything gets pushed down out of the preview pane in presenter mode, usually off the screen if there's more than a little content. At first I thought it was maybe something to do with CSS I added, but the same thing happens in the spectacle boilerplate without changing anything else.

It's easy to see if you add the following prop to slide 9 in the [spectacle boilerplate](https://github.com/FormidableLabs/spectacle-boilerplate/): `align="center flex-start"`.

<img width="784" alt="screen shot 2017-08-14 at 2 33 14 am" src="https://user-images.githubusercontent.com/9385814/29260631-f8257600-8098-11e7-9d6f-f8d9d4aba2fa.png">

**Comment by kenwheeler** [comment]
fixed upstream
