### ISSUE TITLE
Programmatically export to PDF

### ISSUE THREAD

**Issue by cmckni3** [FormidableLabs/spectacle#355]
I want to programmatically export to PDF. Maybe something like [react-pdf](https://github.com/diegomura/react-pdf) could be leveraged in the future?

**Comment by kenwheeler** [comment]
I'll take a look at that and see what it entails. Might have to abstract some primitives out to make it work

**Comment by cmckni3** [comment]
Was this not feasible, @kenwheeler?

**Comment by kenwheeler** [comment]
I closed this as a dupe of this other ticket where its proposed to do it with headless chrome, planning on giving that a spin
