### ISSUE TITLE
Marksy incorrect usage in Markdown Component

### ISSUE THREAD

**Issue by f5io** [FormidableLabs/spectacle#356]
I have been running into an issue where the `Markdown` component does not correctly inherit styles, but I have managed to narrow down the cause.

The `marksy` package is currently defined as [`^0.4.2`](https://github.com/FormidableLabs/spectacle/blob/master/package.json#L28) in the package.json, however it's [usage](https://github.com/FormidableLabs/spectacle/blob/master/src/components/markdown.js#L42-L68), does not match the `marksy` API for that version.

There are a couple of options:

- Use `marksy@0.4.2` and change the usage so that the tags are not nested in an `elements` prop in the options object passed to `marksy`
- Use latest `marksy@5` and add in the `createElement` option to the options object, which would need to point to `React.createElement`

I am happy to open up a PR for either option, let me know how you'd like me to proceed.

**Comment by kenwheeler** [comment]
Would love a PR
