### ISSUE TITLE
Slide organization

### ISSUE THREAD

**Issue by adamgruber** [FormidableLabs/spectacle#358]
Just wondering if there's a good pattern for organizing slides for larger presentations. Seems like putting them all into the `presentation.js` file can become cumbersome.

**Comment by kenwheeler** [comment]
When I've had to do it, I've set up a file like:

```js
export const slideGroup = [
   <Slide>...</Slide>,
   <Slide>...</Slide>
];
```

Is there a different API for this that you think would be cool?

**Comment by adamgruber** [comment]
Not too sure what API I'd want but here's what I did based on your suggestion. I'm grouping slides based on section so I've got a `slides` folder inside `src` and a folder for each section and inside that. Each section folder contains an `index.js` file and a `notes.js` file, plus markdown files for notes and any code examples for that section.

```
── src
  └── slides
      ├── 01_intro
      │   ├── code.example
      │   ├── index.js
      │   ├── notes.js
      │   └── notes_1.md
      └── index.js
```

 The index file exports an array of `<Slide>` components like you suggest:
```jsx
// 01_intro/index.js
import React from 'react';
import { Slide } from 'spectacle';
import notes from './notes';

export default [
  <Slide>
    {notes.one}
    ...
  </Slide>,
  <Slide>
    {notes.two}
    ...
  </Slide>,
];
```

My notes are written in markdown and then I export `<Notes>` components using [react-markdown](https://github.com/rexxars/react-markdown):
```jsx
// 01_intro/notes.js
import React from 'react';
import { Notes } from 'spectacle'
import ReactMarkdown from 'react-markdown';
import notes1 from './notes_1.md';

const one = <Notes><ReactMarkdown source={notes1} /></Notes>;

export default { one };
```

The main `presentation.js` file imports all the slides:
```jsx
// src/presentation.js
import React from "react";
import { Deck } from 'spectacle';
import createTheme from "spectacle/lib/themes/default";
import Slides from './slides';

// Require CSS
require("normalize.css");
require("spectacle/lib/themes/default/index.css");

// Define theme
const theme = createTheme({
  primary: "#fff",
  secondary: "#505e67",
  tertiary: "#00b478",
  quarternary: "#2e7ad1",
});

const Presentation = () => (
  <Deck
    transitionDuration={500}
    theme={theme}
    progress="bar"
    controls={false}>
    { Slides }
  </Deck>
);

export default Presentation;
```

And the slides are exported like this:
```js
// src/slides/index.js
import { cloneElement } from 'react';

import Intro from './01_intro';
import OtherSection from './02_section';

const slides = [].concat(
  Intro,
  OtherSection
);

export default slides.map((slide, i) => cloneElement(slide, { key: i }));
```

I'm not saying this is ideal, there's still a bit too much code repetition in each slide and section, but it worked for me. There's a decent level of organization and it's easy to add more sections or reorder things.

**Comment by bbaaxx** [comment]
I've created a pull request with a proposed new organization and optional auto-import of slide components please review it here: https://github.com/FormidableLabs/spectacle-boilerplate/pull/49
It allows to compose each slide in its own file and either import them separately and insert them into `<Deck>` or order the slide files in alphabetical order and let the auto import handle the rest.

**Comment by kenwheeler** [comment]
this is fixed with the hasSlideChildren prop
