### ISSUE TITLE
Suggestion: CLI PDF Export with Headless Chrome

### ISSUE THREAD

**Issue by knpwrs** [FormidableLabs/spectacle#359]
Headless Chrome is capable of exporting PDFs. I haven't tried it with spectacle yet but it appears to work: https://developers.google.com/web/updates/2017/04/headless-chrome#create_a_pdf_dom

**Comment by joelgriffith** [comment]
I'd recommend https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions for this as the chrome-remote-interface is a bit complex to setup for a simple thing like this.

**Comment by DSchau** [comment]
@knpwrs @joelgriffith I _kinda_ started working on this.

https://github.com/DSchau/screenie

I have it working for a past Spectacle presentation I've given; thinking about making it a library or tool or something to make it easy to integrate and use with Spectacle (and other slide decks).

It's kinda hacky now; requires waiting for 2500 ms before and after taking a screenshot (so it's painfully slow) but hey, it works!

**Comment by kenwheeler** [comment]
Fixed with this right here https://github.com/FormidableLabs/spectacle-renderer
