### ISSUE TITLE
Slides don't change when using the new create-react-app script to build my-presentation

### ISSUE THREAD

**Issue by robeau** [FormidableLabs/spectacle#362]
I've used ```create-react-app my-presentation --scripts-version spectacle-scripts``` to build my-presentation, and immediately ran it using `yarn start`. It seems that, right out of the box, slide changes aren't working in the browser. The url changes, but the view stays the same unless I refresh the page.

I am using node v6.11.3 and yarn v0.27.5. I get the same results in both Chrome and Firefox.

**Comment by kenwheeler** [comment]
Do you mean slide changes like navigation, or like slide hot reload edits?

**Comment by kenwheeler** [comment]
I just gave this a shot and it worked for, any other details you can provide? what you changed, what happened, what you expected to happen? OS?

**Comment by robeau** [comment]
Hi Ken. I mean the navigation. The address bar changes, but the view doesn't. This is only on the create-react-app version (I didn't make any changes) -- the boilerplate works fine.

This is on macOS Sierra 10.12.6 I tried clearing everything and rerunning the generator a few times with the same result. I'll try it out on a windows computer tonight and let you know if I get the same result.

And I'll try on my mac from home as well -- now that I think about it, my work network might be blocking something essential. I'll let you know how it goes.

**Comment by kenwheeler** [comment]
Let me know if you were able to reproduce, closing for now, but will reopen if necessary
