### ISSUE TITLE
ComponentPlayground broken in Spectacle with React 16.0

### ISSUE THREAD

**Issue by spiderbites** [FormidableLabs/spectacle#364]
Hello,

I've set up a Spectacle presentation use create-react-app with spectacle-scripts, using react and react-dom 16.0.0.

When I try to render a ComponentPlayground I get the following error:

```
Element ref was specified as a string (editor) but no owner was set. You may have multiple copies of React loaded. (details: https://fb.me/react-refs-must-have-owner).
```

with the error being traced back to the `<Editor>` component.  This does not seem to be a problem if i revert to react 15.6

**Comment by ebertmi** [comment]
This is caused by the non-peer-dependency of react-15.6 in component-playground. spectacle needs to update the dependency to component-playground v3.0.0. Or just manually delete react in the node_modules inside component_playground to get rid of this error.
