### ISSUE TITLE
Add new fragment types

### ISSUE THREAD

**Issue by kenwheeler** [FormidableLabs/spectacle#37]
There should be more fragment types. For starters, one that switches content instead of just making it appear. Maybe a magic move? Anybody got any ideas?

**Comment by mathieudutour** [comment]
this would be awesome: https://github.com/Rich-Harris/ramjet

**Comment by kenwheeler** [comment]
Hell yeah it would be.

**Comment by kenwheeler** [comment]
Closing in favor of specific issues
