### ISSUE TITLE
feature request: deep link to specific Appears

### ISSUE THREAD

**Issue by AndersDJohnson** [FormidableLabs/spectacle#396]
Feature request to support deep-linking to specific Appear states, auto-advancing through the appears on the targeted Slide.

Something like:
* http://localhost:3000/#/4-1 or `4.1`
* http://localhost:3000/#/4-2
* etc.

Possibly also support giving `Appear`s an `id` prop, and let use refer to those in URLs as named deep-links, e.g.:

* http://localhost:3000/#/4-joke
* http://localhost:3000/#/4-punchline

Implementation could either make IDs local to each `Slide`, or global. If global, could support named global deep-links, e.g.:

* http://localhost:3000/#/joke
* http://localhost:3000/#/punchline

**Comment by kenwheeler** [comment]
Closing as a dupe of #152 , definitely on deck

**Comment by AndersDJohnson** [comment]
Haha, not on `<Deck>`...
