### ISSUE TITLE
Support inline Text

### ISSUE THREAD

**Issue by AndersDJohnson** [FormidableLabs/spectacle#402]
When nesting `Text` components, there's a line break due to use of `<p>` tags. So we have to revert to native React styles to fix or entirely to style our nested text, e.g.:

```js
<Text italic textColor="lime" textSize={56} style={{ display: 'inline' }}>...</Text>
```

It might good to support an `inline` prop on `Text` that does this or even uses a `<span>` rather than a `<p>`.

**Comment by kenwheeler** [comment]
We use the <S> tag for that. It inherits from Base so you can do anything you could do on a Text with it.
