### ISSUE TITLE
'Fit is not defined' error

### ISSUE THREAD

**Issue by code-chimp** [FormidableLabs/spectacle#41]
I am attempting to use the Layout tag with both 'Fit' and 'Fill' elements but Chrome is throwing an 'Uncaught ReferenceError' for the 'Fit' element.

My slide definition is:

    <Slide
      transition={['zoom', 'fade']}
      bgColor="primary"
      notes="Polymer example"
    >
      <Layout>
        <Fit>
          <Text>Definition:</Text>
        </Fit>
        <Fill>
          <CodePane
            lang="html"
            source={require("raw!./snippets/polymer-1.html")}
            margin="20px auto"/>
        </Fill>
      </Layout>
    </Slide>

The rendered code for the slide looks like:

        _reactAddons2["default"].createElement(
          _srcSpectacle.Slide,
          {
            transition: ["zoom", "fade"],
            bgColor: "primary",
            notes: "Polymer example"
          },
          _reactAddons2["default"].createElement(
            _srcSpectacle.Layout,
            null,
            _reactAddons2["default"].createElement(
              Fit,
              null,
              _reactAddons2["default"].createElement(
                _srcSpectacle.Text,
                null,
                "Definition:"
              )
            ),
            _reactAddons2["default"].createElement(
              _srcSpectacle.Fill,
              null,
              _reactAddons2["default"].createElement(_srcSpectacle.CodePane, {
                lang: "html",
                source: __webpack_require__(473),
                margin: "20px auto" })
            )
          )
        ),

The file fit.jsx looks okay to me and it is being included in the spectacle.jsx file as far as I can tell, so I am having trouble figuring out where the issue is.

**Comment by mathieudutour** [comment]
Did you import it at the beginning of your file?

**Comment by code-chimp** [comment]
I missed the imports at the beginning of the deck.jsx file, thanks.
