### ISSUE TITLE
Separate Manager and Slide concerns

### ISSUE THREAD

**Issue by kitten** [FormidableLabs/spectacle#412]
I've started experimenting with an alternative Manager <-> Slide architecture here: https://github.com/FormidableLabs/spectacle/compare/refactor/slide-transition

It involves:

- [x] storing the `slideReference` inside the Redux state
- [x] remove `cloneElement` props from Manager
- [x] inject all needed props inside the Slide from Redux
- [ ] Remove TransitionGroup
- [ ] Implement transitions using Redux state and fully trigger them from the Slide
- [ ] Render last and current slide in Manager

This will allow us to nest slides in components for example

**Comment by ebrillhart** [comment]
hey @kitten I'm going through and cleaning up the backlog - was this feature ever implemented/can this issue be closed?

**Comment by kitten** [comment]
@ebrillhart It was started by Ken before he left. Not sure if any more cleanup work is needed :)

**Comment by kale-stew** [comment]
Closing as we're now rewriting the library. 🙂
