### ISSUE TITLE
Fullscreen Button is not visiable and hard to find

### ISSUE THREAD

**Issue by BerkanSezer** [FormidableLabs/spectacle#413]
Fullscreen  button is not visiable, I fix it but I didn't fix mobile responsive problem. It mustn't see in mobile devices

**Comment by marcysutton** [comment]
It also needs discernible text, like the previous and next buttons. Something like `aria-label="Fullscreen"`

**Comment by hyunwoona** [comment]
It also needs a keyboard shortcut
