### ISSUE TITLE
Update spectacle-code-slide to work with Spectacle 4.0 and React 16

### ISSUE THREAD

**Issue by nwaywood** [FormidableLabs/spectacle#415]
Atm spectacle-code-slide is broken using Spectacle 4 and React 16

![image](https://user-images.githubusercontent.com/3773641/32764379-3de9ba44-c959-11e7-8d43-f8264aff4a3f.png)

Steps to reproduce:

1. Clone the spectacle boilerplate
2. `yarn add spectacle-code-slide`
3. Try and use `CodeSlide` component
4. Get the error shown above

**Comment by philpl** [comment]
Since this is not our library we can’t do much to fix it ASAP, but there’s a PR open over at the spectacle-code-slide repo: https://github.com/thejameskyle/spectacle-code-slide/pull/45

**Comment by nwaywood** [comment]
Ok thanks, I'll keep an eye on that PR. cc @thejameskyle

**Comment by kenwheeler** [comment]
Done
