### ISSUE TITLE
`fit` option removes semantic heading tags

### ISSUE THREAD

**Issue by marcysutton** [FormidableLabs/spectacle#416]
I just got started with Spectacle, and I noticed that the boilerplate project had a DIV and SPAN for an h1 heading. After doing some digging, I found it was the `fit` option that changed it from a semantic h1-h6 heading to a generic tag. This impacts accessibility, since it is removing semantic structure in favor of styling.

Expected behavior: the `fit` option should use styling on an h1-h6 tag, not a DIV/SPAN.

**Comment by ryan-roemer** [comment]
@kenwheeler -- Is there something specific about `fit` that won't work with h1-h6 and if not, how much work would it be to keep the h1-h6 originally specified when `fit` is applied? Thanks!

**Comment by kenwheeler** [comment]
@ryan-roemer it probably just needs a browser defaults reset for heading elements, I'll give it a go
