### ISSUE TITLE
Support for autoplay 

### ISSUE THREAD

**Issue by ankit** [FormidableLabs/spectacle#42]
Something like:

```
<Slide slideDuration={1000}>
  ...
</Slide>
```

**Comment by kenwheeler** [comment]
Would anyone else use this?

**Comment by MarkRedeman** [comment]
I could see myself using this when creating a small slideshow app. In this case it would also be useful if we could set the presentation to `loop` (similar to how Reveal.js has support for loop & autoplay).

**Comment by opensourcegeek** [comment]
+1
