### ISSUE TITLE
Magic Move doesn't align text properly

### ISSUE THREAD

**Issue by jlongster** [FormidableLabs/spectacle#422]
In the announcement tweet, https://twitter.com/FormidableLabs/status/930457800832094209, it's not quite a smooth transition. You can tell that the text doesn't match up at the beginning of the transition. I did a screen recording and stepped through the frames so you can really see it.

Unfortunately github doesn't support .mov files so you'll have to download it: http://jlongster.com/s/magic-move.mov

I haven't actually used it yet, just noticed it in that video, so I'm not sure if it happens in all cases or not.

(btw this is a very cool feature)

**Comment by philpl** [comment]
cc @kenwheeler: Could it be that the portal messes up its own position, or maybe `getBoundingClientRect` is not quite doing the right thing we want it to do on the magic element?
