### ISSUE TITLE
Feature: 2d grid like Reveal

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/spectacle#425]
Bringing this out as a separate feature from old `SlideSet` ticket: #57

Notes:

* We have an old WIP from Zach that never quite got finished at: https://github.com/FormidableLabs/spectacle/pull/285

Strawman action items: (totally up for brainstorming!)

* [ ] Basically, just like reveal for http://cascadiajs2014.formidablelabs.com/#/title
    - [ ] Esc: Overview and arrows navigate grid
    - [ ] Up / Down / Left / Right normally navigate grid
    - [ ] Space / Shift Space: Replace normal "forward" / "back" capability going through slides in actual order.

**Comment by ebrillhart** [comment]
Hi! In an effort to focus on more recent bugs and requests, we're closing all open issues more than a year old, with some exceptions. If your issue is closed, and you still feel strongly about it, please feel free to reopen it or submit a PR with the change!
