### ISSUE TITLE
bgImage prop should also support gradients

### ISSUE THREAD

**Issue by kyleshevlin** [FormidableLabs/spectacle#428]
I was working on a slide deck when I realized that the `bgImage` prop assumes that the value will be a path to be used with the `url()` function. In many cases, this is a nice assumption, but `background-image` also happens to be the CSS property that gradients are added with.

I would like to add support for being able to add gradients to slides. I think this can be done one of two ways.

1) We modify `bgImage` prop to expect a string without automatically wrapping the string in a `url()` call. The challenge with this approach is coming up with a way to handle the use case where a user may purposefully, though more likely inadvertently, use the `bgDarken` prop as well. We could ignore `bgDarken` if the string supplied to `bgImage` has a gradient in it.

2) Another option is to add a new prop, `bgGradient` that handles this one use case. Challenges with this will be deciding how to handle situations where all of the props (`bgImage`, `bgDarken`, and `bgGradient`) are simultaneously present, but we could come to a decision on that. This might be the cleaner of the two implementations.

I'm open to other ideas as well and happy to do the work of the PR, but wanted to get some input before going down one path or another.

**Comment by Hypnosphi** [comment]
What's the recommended workaround for it? `className` property on `Slide` sets className for slide inner content not for slide itself
