### ISSUE TITLE
Issues using <Appear> + emotion/styled components

### ISSUE THREAD

**Issue by himynameisdave** [FormidableLabs/spectacle#431]
Hi. I have trying to get `<Appear>` to work for the past few days, and am consistently running into problems. I've tried tweaking my code a bunch, but nothing works, so I thought I would post some examples of what I mean.

I think it has something to do with elements that are `styled` with [`emotion`](https://github.com/emotion-js/emotion) being children of `<Appear />`, but I am not 100% sure. I also tried _all_ of the following cases with `styled-components` as well and ran into the same problems. It may also be because I've broken off all my slides into their own stateless function components...?

---

### Attempt 1: "Cannot read property 'dataset' of null"

[This appears to be the origin of this error](https://github.com/FormidableLabs/spectacle/blob/master/src/components/appear.js#L27). I have a styled heading that I'm exporting from this one file...

**`main-heading.jsx`**
```jsx
import React from 'react';
import styled from 'react-emotion';
import { Heading } from 'spectacle';

const MainHeading = ({ children }) => {
    //  I have to wrap it all in "& { }" because otherwise the font-weight gets overwritten... -_- (see: #426)
    const StyledHeading = styled(Heading)`
        & {
            font-weight: 300;
            text-transform: lowercase;
        }
    `;
    return (
        <StyledHeading
            size={3}
            textColor="secondary"
            textAlign="left"
        >
            {children}
        </StyledHeading>
    );
};

export default MainHeading;

```

...and then I go to use it in my slide, which I've chosen to separate into it's own file ([as was outlined in the FAQs](https://github.com/FormidableLabs/spectacle#faq)):

**`slide-one.jsx`**

```jsx
import React from 'react';
import { Appear, Slide } from 'spectacle';
import MainHeading from '../../components/main-heading.jsx';


const SlideIntroOne = () => (
    <Slide
        bgColor="primary"
        align="flex-start"
    >
        <Appear>
            <MainHeading>
                my presentation that's never going to be finished in time...
            </MainHeading>
        </Appear>
    </Slide>
);


export default SlideIntroOne;

```

### Attempt 2: "React.Children.only expected to receive a single React element child."

So next I tried wrapping the child content of the styled `MainHeading` with the `<Appear>`.

**`slide-one.jsx`**

```jsx
const SlideIntroOne = () => (
    <Slide
        bgColor="primary"
        align="flex-start"
    >
        <Appear>
            <MainHeading>
                my presentation that's never going to be finished in time...
            </MainHeading>
        </Appear>
    </Slide>
);
```

This resutls in that `Invariant Violation: React.Children.only expected to receive a single React element child.` error. Here is the error message:

![image](https://user-images.githubusercontent.com/4298089/33057144-39e291f2-ce3e-11e7-8f2c-a5a2408478c2.png)

### Attempt 3: Ghost elements

Next I figured that I had to use `<Appear>` inside of the styled component itself. I removed the use of it in `slide-one.jsx`, and included it in the heading like so:

**`main-heading.jsx`**
```jsx
import React from 'react';
import styled from 'react-emotion';
import { Appear, Heading } from 'spectacle';

const MainHeading = ({ children }) => {
    const StyledHeading = styled(Heading)`
        & {
            font-weight: 300;
            text-transform: lowercase;
        }
    `;
    return (
        <Appear>
            <StyledHeading
                size={3}
                textColor="secondary"
                textAlign="left"
            >
                    {children}
            </StyledHeading>
        </Appear>
    );
};


export default MainHeading;

```

This results in "ghost" elements, where the styled heading component will render, but it's `opacity` will be set to `0`. I've tried adding an `order` prop, but nothing seems to work.

![image](https://user-images.githubusercontent.com/4298089/33057321-193be010-ce3f-11e7-9f16-c9c0c974ae8e.png)

### Attempt 4: Ghost elements again

Before giving up entirely, I decided to try wrapping the `styled` part of that in a div or something to see if that would do anything. Same thing as mentioned above.

**`main-heading.jsx`**
```jsx
return (
    <Appear>
        <div>
            <StyledHeading
                size={3}
                textColor="secondary"
                textAlign="left"
            >
                    {children}
            </StyledHeading>
        </div>
    </Appear>
);
```

I even tried wrapping `children`, but that results in the same "React.Children.only expected" issue mentioned above.

---

So I gave up on the styled components, and still cannot get `<Appear>` to work with the `Heading>`. The following also gives me ghost elements that do not appear.

**`main-heading.jsx`**
```jsx
return (
    <Slide
        bgColor="primary"
        align="flex-start"
    >
        <Appear>
            <Heading
                size={3}
                textColor="secondary"
                textAlign="left"
            >
                this presentation is gunna suck now
            </Heading>
        </Appear>
    </Slide>
);
```

Not sure why or what exactly I'm doing wrong, but anyway this has been a pretty frustrating experience, and I hope this info will help relieve some of these pain points.

![giphub](https://media1.giphy.com/media/v0eHX3n28wvoQ/giphy-downsized-medium.gif)

**Comment by mAAdhaTTah** [comment]
> It may also be because I've broken off all my slides into their own stateless function components...?

This is the issue. See #340.

**Comment by ebrillhart** [comment]
Hi! In an effort to focus on more recent bugs and requests, we're closing all open issues more than a year old, with some exceptions. If your issue is closed, and you still feel strongly about it, please feel free to reopen it or submit a PR with the change!
