### ISSUE TITLE
Autoplay with slide-duration

### ISSUE THREAD

**Issue by oxydum** [FormidableLabs/spectacle#433]
> How to make a formidable autoplay spectacle with a slide duration for each slide?

      <Deck controls={false} autoplay={true} autoplayDuration={4000} progress="none" >
        <Slide duration={1200}>
          <Text>Hello</Text>
        </Slide>
        <Slide duration={2300}>
          <Text>World!</Text>
        </Slide>
      </Deck>

thx

**Comment by ebrillhart** [comment]
Hi! In an effort to focus on more recent bugs and requests, we're closing all open issues more than a year old, with some exceptions. If your issue is closed, and you still feel strongly about it, please feel free to reopen it or submit a PR with the change!
