### ISSUE TITLE
Outdated documentation for CodePane

### ISSUE THREAD

**Issue by nwaywood** [FormidableLabs/spectacle#435]
The documentation says:

```
You can change your syntax highlighting theme by swapping the prism.js CSS file in index.html
```

but there is no `link` tag in the `index.html` that imports prism (I'm using the spectacle-boilerplate). 

To try and change the prism theme I have tried:

- Adding a CSS import into `index.html`, this has no effect
- Using `emotion`s `injectGlobal` method to inject my desired prism theme, this clashes with other global css which is imported somewhere by spectacle (I can't figure out where)

**Comment by philpl** [comment]
Hm, adding a prism theme css file should still work. Can you post a small snippet of your index.html and maybe a screenshot of the codepane’s styles in the devtools please?

**Comment by nwaywood** [comment]
Ok I did a bit more debugging and I think the issue is that the webpack config in the spectacle-boilerplate is not handling the css file properly.

My `index.html`:

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width initial-scale=1 user-scalable=no" />
  <title>Modern JavaScript</title>
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
  <link href="./prism-atom-dark.css" rel="stylesheet">
</head>
<body>
  <div id="root"></div>
  <script src="./dist/bundle.js"></script>
</body>
</html>
```

Webpack css loader config:

```
      {
        test: /\.css$/,
        loaders: ["style-loader", "raw-loader"],
        include: __dirname
      },
```

But the css doesn't seem to be being served:

![image](https://user-images.githubusercontent.com/3773641/33294770-3be26fb6-d426-11e7-8387-ab51fd5739a7.png)

So many the issue is with the boilerplate webpack config? I don't understand webpack enough to really debug this any further without your assistance

**Comment by mAAdhaTTah** [comment]
You're pointing `prism-atom-dark.css` to a path on disk that doesn't exist. `webpack-dev-server` falls back to the `index.html` file on a 404, so that's what you're seeing. You may not have the css file in the correct location.

**Comment by philpl** [comment]
That looks like the solution here :)

I’ll close this issue for now, but feel free to comment and ask more questions if you need more help :)

**Comment by nwaywood** [comment]
Here is the path I am using from `index.html`:

`<link href="./prism-atom-dark.css" rel="stylesheet">`

and `prism-atom-dark.css` is in the same directory as the `index.html` file:

![image](https://user-images.githubusercontent.com/3773641/33295677-221a6fe8-d42b-11e7-80a2-2533087d7c47.png)

I am fairly sure that is correct right? Thats why it lead me to think that there must be something wrong with the boilerplates webpack config since the css file is not being served

**Comment by nwaywood** [comment]
oh and my webpack config is unchanged from the boilerplate https://github.com/FormidableLabs/spectacle-boilerplate/blob/master/webpack.config.js

**Comment by nwaywood** [comment]
@philpl Just a suggestion, but it also might be less confusing if the boilerplate included the default prism theme within the `index.html`. That would make it very easy to "swap" the prism themes as the documentation suggests.

Atm I can't even figure out where the default prism theme is being added from in the template

**Comment by mAAdhaTTah** [comment]
`webpack-dev-server` is serving the file out of the `dist` folder, so it needs to be in there. You can use the [copy-webpack-plugin](https://github.com/webpack-contrib/copy-webpack-plugin) to do this.

**Comment by kyleshevlin** [comment]
I think there's another problem with this, in that the styles built into Spectacle come after styles imported in a stylesheet. I have used the ExtractTextPlugin to import my custom Prism styles into a stylesheet, but Emotion declares all their styles below my stylesheet, and thus are the styles used by the app. I can't affect the order of these.

That being said, it's not as simple as the docs suggest. They need to be updated once a solution is determined.
