### ISSUE TITLE
[Feature request] How to add spectacle-code-slide in one-page mode?

### ISSUE THREAD

**Issue by aravindhsampath** [FormidableLabs/spectacle#439]
First, Spectacle is excellent! Thanks! 

I'm a Javascript illiterate who stumbled on this project and would love to make use of it for a presentation I'm giving soon. I'm using the one-page mode as described [here](https://github.com/FormidableLabs/spectacle#one-page) to get my presentation done. 

Any way I could use [spectacle-code-slide](https://github.com/NicholasGWK/spectacle-code-slide) in this mode?

I tried adding the following line to my one-page html:
<script src="https://unpkg.com/spectacle-code-slide/lib/CodeSlide.js"></script>

But, don't know how to supply my code to present and use the extension.
Any help would be very much appreciated!

**Comment by ryan-roemer** [comment]
`spectacle-code-slide` needs to produce a UMD build that you can then `<script` tag include into a one-page deck. Suggest opening an upsteam issue / PR at https://github.com/thejameskyle/spectacle-code-slide/pulls
