### ISSUE TITLE
Security issue in marksy -> marked

### ISSUE THREAD

**Issue by marcysutton** [FormidableLabs/spectacle#447]
I was notified by Github that a repo I made using Spectacle has a moderate security vulnerability coming from the `marked` package, a dependency of `marksy`. 

>Known moderate severity security vulnerability detected in marked < 0.3.9
> defined in package-lock.json.package-lock.json update suggested: marked ~> 0.3.9.

I opened an issue against marksy, since they need to do the update: https://github.com/storybooks/marksy/issues/52

**Comment by jbovenschen** [comment]
This is resolved now, the marksy package is updated to the latest release of marked, which includes fixes for both vulnerabilities.

**Comment by marcysutton** [comment]
Nice, that was quick!

**Comment by marcysutton** [comment]
When will this be released?

**Comment by kenwheeler** [comment]
Today

**Comment by kenwheeler** [comment]
Fixed in 4.0.5
