### ISSUE TITLE
running on a different domain breaks hot reloading

### ISSUE THREAD

**Issue by saelfaer** [FormidableLabs/spectacle#45]
While probably more a configuration issue, I was exploring how to run the local dev instance on something else than localhost:3000

so, I went looking in the webpack configuration docs and found that I could run a differnt port (or even domain) all together by adding the following to my `webpack.config.js`

```
webpackConfig.devServer = {
  colors: true,
  host: 'mypresentation.local',
  port: 3333,
  hot: true
}
```

works perfectly but breaks something as the console gets flooded with error messages from some script trying to open a socket.io connection on  `localhost:3000`

**update: I was wrong to assume HMR was broken, since that seems to work, I'm not sure which script either webpack or spectacle is trying to  open that socket connection**

any ideas?

**Comment by kenwheeler** [comment]
I am refactoring the webpack config so that this will be easier to do without overriding imports
