### ISSUE TITLE
Confusion around hasSlideChildren doc

### ISSUE THREAD

**Issue by Phoenixmatrix** [FormidableLabs/spectacle#450]
I've been fighting with this for a bit, and even debugging through the code, I'm a little confused as to how hasSlideChildren is supposed to work.

It looks from the code, as well as the doc, that if an element has hasSlideChildren set, it will look at that element's children. That works well enough if I do something like (though it kinds of defeat the purpose):

```js
      <Deck
        transition={['zoom', 'slide']}
        transitionDuration={500}
        theme={theme}
      >
        <MySlides hasSlideChildren>
          <Slide>1</Slide>
          <Slide>2</Slide>
        </MySlides>
      </Deck>
```

But if I make a `MySlides` components that return the 2 slides, and put hasSlideChildren as per the doc:

```js
class MySlides extends Component {
  render() {
    return (
      <div hasSlideChildren>
        <Slide>1</Slide>
         <Slide>2</Slide>
      </div>
    )
  }
}
```

And then, in my Presentation component, I import MySlides and use it as a child of Deck, there's two issues:

First, if using a div, React will complain that I'm using a non-supported property. Easily fixed by using the SlideSet component that I found looking through the code.

Second and more importantly: the hasSlideChildren prop is now on a child of MySlides, and Spectacles will never see it.

So I'm a bit confused: did I just completely misunderstand how it's meant to be used?

**Comment by Phoenixmatrix** [comment]
ok, if I have a module that exports (notice this is not a component, just a bunch of JSX):

```js
export default (
   <SlideSet>
       <Slide>1</Slide>
       <Slide>2</Slide>
   </SlideSet>
)
```

and then I consume this, eg:

```js
import Foo from './foo'

/* lower down*/
render() {
   return   (<Deck
     transition={['zoom', 'slide']}
     transitionDuration={500}
     theme={theme}
      >
        {Intro}
    </Deck>
  );
}
```

That works. But somehow I expect that's not the intended usage.

**Comment by mAAdhaTTah** [comment]
I had a similar problem (see #340). While that one was closed, the issue wasn't fully resolved, although the workaround you present is basically what I'm doing today.

**Comment by baptooo** [comment]
Hello, same issue here, it works with `<SlideSet />` component but not with `hashasSlideChildren`, does the doc needs to be updated ?

**Comment by siakaramalegos** [comment]
What is `<SlideSet>`? I don't see it in the docs. My guess is for when you want to group a bunch of slides, but does it have special behaviors? I also have this problem with importing slides so doing one of the workarounds above. Just wanted more info on SlideSet

**Comment by markerikson** [comment]
Yeah, I'm rather confused by all this too.  I think I"ll have to stick with my existing workaround of doing a bunch of array exporting and concating.

**Comment by g3r4n** [comment]
I've just started to use the library and here the template i used to start:
https://stackblitz.com/edit/react-kgu6gt
This solution do not use SlideSet or hasSlideChildren, it's more a concatenation of JSX (maybe the same solution than yours @markerikson ).
This solution let's you have one Slide per file to organise your presentation. You can also easily re-organise your presentation as you go just by changing the Slides/index.js  
What do you think about the solution ? 
Do you see any limitation of this solution ? I'm just starting to create my presentation, I don't have any experience with this library that's why it's hard for me to tell.
Should i make a PR as a second example for users who would like to have a single file per Slide?
By the way, i found that using the [stackblitz](https://stackblitz.com) site to start experimenting with the library is easier than the create-react-app or boilerplate solution, what do you think about proposing it as a alternative ? A potential user of the library will just fork the project and start doing the slides. A plus of this solution : your slides are already on the cloud, no need to deploy them again and again 😃

**Comment by markerikson** [comment]
Yeah, that's almost exactly what I'm doing myself.

I'd still like to be able to render a `<MyCustomSlide />` that itself renders a `<Slide />`, but I've been busy and haven't had time to play around with that idea further.

**Comment by tim-soft** [comment]
@markerikson I tried doing just that and everything appeared to work... except for the transitions. 

There must be some databinding underneath that isn't getting passed related to animations. Hopefully someone can dig deeper, as this is the obvious and best way to organise the slides.

**Comment by greeeg** [comment]
@markerikson @tim-soft I finally found a way to organize custom slides and pass them data.

A custom slide might look like this:
```js
import React from 'react';
import { Heading, Slide, Text, Layout, Appear } from 'spectacle';

class HeadingSlide {
  constructor(data) {
    this.data = data;
  }

  render() {
    return (
      <Slide bgColor="black">
        <Appear>
          <Heading textColor="white" size={1}>
            {this.data.title}
          </Heading>
        </Appear>
        <Appear>
          <Heading
            textFont="secondary"
            textColor="white"
            size={5}
            style={{ paddingBottom: 40, paddingTop: 10 }}
          >
            This is a description
          </Heading>
        </Appear>
      </Slide>
    );
  }
}

export default HeadingSlide;
```

And then comes the tricky way to use this slide:
```js
import React, { Component } from 'react';
import {
  BlockQuote,
  Cite,
  Deck,
  Heading,
  ListItem,
  List,
  Quote,
  Slide,
  Text
} from 'spectacle';
import createTheme from 'spectacle/lib/themes/default';

import 'normalize.css';

const theme = createTheme(
  {
    white: '#f7f7f7',
    black: '#080808',
    blue: '#2752ff',
    grey: '#CECECE'
  },
  {
    primary: 'Larsseit',
    secondary: 'LarsseitLight'
  }
);

const slidesImports = [
  {
    name: 'HeadingSlide',
    import: import('./slides/HeadingSlide')
  },
  {
    name: '2',
    import: import('./slides/2')
  }
];

export default class Presentation extends Component {
  constructor(props) {
    super(props);

    this.state = {
      slides: Array(slidesImports.length).fill(<Slide key="loading" />)
    };
  }

  componentDidMount() {
    const importedSlides = [];
    const imports = slidesImports.map(slideImport => slideImport.import);

    Promise.all(imports).then(slidesImportsResolved => {
      slidesImportsResolved.forEach((slide, index) => {
        console.log(slide, slidesImports[index].name);
        const _slide = new slide.default({
          title: 'Hello World'
        });
        importedSlides.push(_slide.render());
      });
      this.setState({ slides: importedSlides });
    });
  }

  render() {
    const { slides } = this.state;
    return (
      <Deck
        transition={['fade']}
        transitionDuration={500}
        contentWidth={1700}
        contentHeight={window.innerHeight}
        controls={false}
        progress="none"
        theme={theme}
      >
        {slides.map((slide, index) => {
          return React.cloneElement(slide, { key: index });
        })}
      </Deck>
    );
  }
}
```

**Comment by ebrillhart** [comment]
Hey everyone, this issue is related to a known bug that we're in the process of fixing! Just wanted to give an update.

**Comment by kale-stew** [comment]
Closing as outdated - please see our pinned issue for all things relevant to the rewrite, roadmap, etc.
