### ISSUE TITLE
Slide maxWidth seems to not work

### ISSUE THREAD

**Issue by MikeDabrowski** [FormidableLabs/spectacle#457]
Great job with spectacle. Really appreciate it!

I got a problem with long title words not being centered. They just overflow container and disappear to the right. I tried to set maxWidth on Slide tag as said in the docs but it does nothing. I had to change contentWidth of Deck to workaround this issue. 

What is the correct to handle long title words? 1000px is ok but text should stay centered after wrap no matter what.

![image](https://user-images.githubusercontent.com/17836911/35198584-3e91bf0a-fef1-11e7-821b-2ecaa1c54e13.png)

**Comment by samwhale** [comment]
Hi @MikeDabrowski, could you give me a small pen that I could take a look at to reproduce the problem?

**Comment by ebrillhart** [comment]
Closed - maxWidth is no longer a prop, see #667 for suggestion of what to use instead
