### ISSUE TITLE
CodePane doesn't respect custom Prism theme

### ISSUE THREAD

**Issue by peggyrayzis** [FormidableLabs/spectacle#458]
Hi! I'm using the most recent version of Spectacle via CRA. Unfortunately, CodePane isn't respecting my custom Prism theme.

I've tried:
1. Adding `<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/prismjs@1.10.0/themes/prism-okaidia.css">` to the <head> of my `index.html` file
2. Importing the theme in my `presentation.js` file: `import 'prismjs/themes/prism-okaidia.css';`

In Chrome dev tools, you can see the css for the theme has loaded, but it's being overridden by whatever theme Spectacle includes by default.

Thanks for your help!

**Comment by philpl** [comment]
Hm, weird 🤔 I previously made sure that this is working, but I've read in some other issue before that it isn't 😢 

Our theme's specificity should be the same as the theme you're importing https://github.com/FormidableLabs/spectacle/blob/master/src/themes/default/prism.dark.js

I guess it'd work if you could add the stylesheet after emotion's sheet, but that's not possible I suppose 😅 I'll see if I can put together a quick reproduction to try and fix it

**Comment by philpl** [comment]
Wait, I just tried it and it worked... I'm a little confused, am I doing something non-obvious that we need to clarify in the docs 😕 😿 

is it maybe the location of the `<link>` tag? I think, in case it is, that'd definitely be something we'd need to add to the readme 😅 (hope it's not too hard to recognise what's going on in the gif, but I'm adding the tag to the end of the head there)

![2018-01-22 22_51_58](https://user-images.githubusercontent.com/2041385/35248705-11e3cc6a-ffc7-11e7-8b93-9e77507c98db.gif)

**Comment by peggyrayzis** [comment]
Thanks for the prompt reply! 😀 I tried uncommenting out the stylesheet like in your gif and was able to confirm that the stylesheet is changing the font color. What's weird is that the syntax highlighting looks nothing like it does when you visit [Prism's homepage](http://prismjs.com/#languages-list) and click on Okaidia.

Is it possible the language is not being properly applied here? I'm doing `<CodePane lang="javascript" /> in this example:
![spectacle](https://user-images.githubusercontent.com/18017067/35250271-bea9c482-ffa3-11e7-9e9f-a593ac9f4d8e.gif)

Here, you can see that `const` should be blue (consistent with what's on the Prism homepage), but the font color is being overridden by another rule w/ greater specificity.
<img width="1602" alt="write_queries__not_code_by__peggyrayzis_-_agentconf_2018" src="https://user-images.githubusercontent.com/18017067/35250348-28c4a4ae-ffa4-11e7-87e0-6e37b98b55be.png">

**Comment by philpl** [comment]
@peggyrayzis oh dear, that explains it. The themes are being mixed...

We’re back to my original dilemma then I guess. I’d like to prevent the built-in prism themes from being dynamically imported when they’re being used.

Maybe I can add a “.builtin” class to them and the CodePane so that they don’t match at all when they’re not in use. But that in turn would require us to introduce a new prop to disable the builtin themes 🤔

**Comment by peggyrayzis** [comment]
Maybe you could disable the built in themes by passing in `theme="none"`? It's not the best solution, but it would at least save you from having to introduce a new prop.

**Comment by philpl** [comment]
@peggyrayzis That's an amazing idea ✨I'm working on a quick PR now, but I'm thinking of calling it `theme="external"` to make it more explicit. (hope that makes sense)

Also adding a `oneOf` prop-types validation, which was long overdue

**Comment by peggyrayzis** [comment]
Sounds great! 🎉 Thanks again for making this fix so quickly :)
