### ISSUE TITLE
Port:3000 doesn't work on EC2/Ubuntu

### ISSUE THREAD

**Issue by saralkochar** [FormidableLabs/spectacle#46]
I can run this on EC2 without any troubles but can't access through port 3000? I tried to locate on how to configure the port but couldn't figure it out.

**Comment by kenwheeler** [comment]
Wouldn't you want to deploy the built/dist version to EC2 rather than running it off of a dev server? In the event that you actually do, I use hjs-webpack for the webpack config, and you can change the port using these options https://github.com/henrikjoreteg/hjs-webpack#devserver-optional-object

**Comment by saralkochar** [comment]
Thanks Ken. I’m sorry that I didn’t reply until now as I forgot. But your suggestion solved my problem and I simply took the build and deployed. We made an awesome presentation and won the most disruptive idea award…all thanks to your amazing innovation. :)

**Comment by kenwheeler** [comment]
Dude that's rad! Any chance I can see i?

**Comment by saralkochar** [comment]
sure, I will forward you as I get to the office later. (writing from HK). Also, I see great things you guys do…wondering if you have time to chat sometime tomorrow? Our application is build on MEAN however we foresee issues with conquerency as we move towards collaboration so would like to start discussions early on.

**Comment by kenwheeler** [comment]
Sure, ping me at ken.wheeler@formidablelabs.com
