### ISSUE TITLE
Content of the slides gets not updated

### ISSUE THREAD

**Issue by Phalanstere** [FormidableLabs/spectacle#461]
We are using spectacle in a React.js project - and till recently everything worked fine. Now we have run into problems that are very hard to decipher. The interface works as expected, but the content of the slides gets not updated. No error messages whatsoever. Trying to locate the problem we imported boilerplate code - but event that did not work. Could it be that there are idiosyncrasies to other packages?  Could it that the history component is problematic?

**Comment by kale-stew** [comment]
Hi @Phalanstere! Are you still having this issue? I would love to help, but I think I'm going to need a little more information to dig into this problem deeper.

- What do you mean by 'content of the slides gets not updated'? Is the presentation not hot-reloading the way you are expecting it to? Is the slide content not displaying as expected?
- What are some steps to reproduce what you are seeing on your machine? Could you take a screenshot or share some of your code?

As soon as I get a better idea of what's going on, I can help troubleshoot the error. 🙂

**Comment by kale-stew** [comment]
Closing because of lack of response from original reporter
