### ISSUE TITLE
Use images in css

### ISSUE THREAD

**Issue by MikeDabrowski** [FormidableLabs/spectacle#462]
I want to use custom bullet point images so I'd like to have my assets/imgs/ exported from server so I can use `url('...')` in css. How to do that? 

I tried : 

```
new CopyWebpackPlugin([
      { from: './assets' }
    ]),
```

but it didn't work at all

This also prevents me from using other stuff like css, or js imported in index.html.

**Comment by prakharcipher** [comment]
@MikeDabrowski Is it not working in the manner like this - 

`url('./example/assets/{image-name}')`

**Comment by MikeDabrowski** [comment]
No it does not. Images are not available on such url.

**Comment by kenwheeler** [comment]
Are you using spectacle-scripts or the boilerplate?

**Comment by MikeDabrowski** [comment]
I used boilerplate, but bear in mind that was in jan/feb so things could change since then.

**Comment by kale-stew** [comment]
As of #652, custom enumerators are supported in Spectacle 🎉
