### ISSUE TITLE
Sourced markdown file has bad formatting

### ISSUE THREAD

**Issue by ryantuck** [FormidableLabs/spectacle#467]
I have a markdown file called `stuff.md`:

```

# Some markdown

Here's a markdown file to import.

> And a quote

`oh and some code`
```

I attempt to source it:

```
        <Slide>
            <Markdown source={require("../assets/stuff.md")}></Markdown>
        </Slide>
```

And it shows up like so:

![screen shot 2018-02-08 at 12 58 06 pm](https://user-images.githubusercontent.com/1762274/35992382-c03dc120-0ccf-11e8-9142-8896eb9b8707.png)

I imagine I'm missing something trivial. I'd be happy to check out some working examples but can't seem to find any.

**Comment by ryantuck** [comment]
Ah, that's even worse :)

Both suggestions yield the following:

![screen shot 2018-02-08 at 1 45 39 pm](https://user-images.githubusercontent.com/1762274/35994563-64c19dce-0cd6-11e8-9b90-a98a8c3351c1.png)

**Comment by mAAdhaTTah** [comment]
You probably have a loader compiling your Markdown to html.

**Comment by ryan-roemer** [comment]
This is a total guess, but IIRC, you can do something like `require("!raw-loader!../assets/stuff.md")` to make the raw-loader win over everything else?

(That might be 100% wrong, but worth a character of testing :P )

**Comment by ryantuck** [comment]
### Steps to replicate

1. Clone boilerplate: https://github.com/FormidableLabs/spectacle-boilerplate/
2. Replace `presentation/index.js` with code below, and add `assets/stuff.md` with example above.
3. `npm install && npm start`

```javascript
// Import React
import React from "react";

// Import Spectacle Core tags
import {
  BlockQuote,
  Cite,
  Deck,
  Heading,
  ListItem,
  List,
  Quote,
  Slide,
  Text,
  CodePane,
  Code,
  Markdown
} from "spectacle";

// Import theme
import createTheme from "spectacle/lib/themes/default";

// Require CSS
require("normalize.css");

const theme = createTheme({
  primary: "white",
  secondary: "#1F2022",
  tertiary: "#03A9FC",
  quarternary: "#CECECE"
}, {
  primary: "Montserrat",
  secondary: "Helvetica"
});

export default class Presentation extends React.Component {
  render() {
    return (
      <Deck transition={["zoom", "slide"]} transitionDuration={500} theme={theme}>
        <Slide transition={["fade"]} bgColor="primary">
            <Markdown source={require("raw-loader!../assets/stuff.md")} />
        </Slide>
      </Deck>
    );
  }
}
```

**Comment by ryan-roemer** [comment]
@ryantuck -- Can you try `require("!raw-loader!../assets/stuff.md")` since you've already got it downloaded and ready? Thanks!

**Comment by ryantuck** [comment]
@ryan-roemer thanks! looks like adding that line anywhere above the `export` of the presentation component works! 

I'll be adopting the following strategy - would add to the docs myself but not sure where they live. 

```javascript
...

var stuff = require("!raw-loader!../assets/stuff.md");

export default class Presentation extends React.Component {
  render() {
    return (
      <Deck transition={["zoom", "slide"]} transitionDuration={500} theme={theme}>
        <Slide transition={["fade"]} bgColor="primary">
            <Markdown source={stuff} />
        </Slide>
      </Deck>
    );
  }
}
```

**Comment by ryantuck** [comment]
Oh wait, I see the subtlety now. 

The `!` at the very beginning of the string is the thing that matters. No need to do anything higher up in the file or anything. 

```javascript
// works
<Markdown source={require("!raw-loader!../assets/stuff.md")} />

// doesn't work
<Markdown source={require("raw-loader!../assets/stuff.md")} />
```

**Comment by ryan-roemer** [comment]
Yeah, as I (very poorly) understand it, the leading `!` says "whatever comes next *WINS*" or something :)

**Comment by ryan-roemer** [comment]
For documentation sake, here is the part of the webpack config causing problems (it's higher priority than raw-loader without the `!raw-loader` hack): https://github.com/FormidableLabs/spectacle-boilerplate/blob/master/webpack.config.js#L24-L27
