### ISSUE TITLE
Import Spectacle in server-side

### ISSUE THREAD

**Issue by romelperez** [FormidableLabs/spectacle#469]
I want to use [next.js](https://github.com/zeit/next.js/) to render a presentation with spectacle, but I get an error because the hash history is used.

```js
Hash history needs a DOM
Invariant Violation: Hash history needs a DOM
    at invariant (/home/romelperez/projects/prhone/romelperez.com/node_modules/invariant/invariant.js:42:15)
    at createHashHistory (/home/romelperez/projects/prhone/romelperez.com/node_modules/history/createHashHistory.js:69:27)
    at Object.<anonymous> (/home/romelperez/projects/prhone/romelperez.com/node_modules/spectacle/lib/utils/controller.js:50:47)
    at Module._compile (module.js:643:30)
    at Module._compile (/home/romelperez/projects/prhone/romelperez.com/node_modules/source-map-support/source-map-support.js:492:25)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
```

I don't mind not rendering it from the server, but I need it to work in the client.

Is there any workaround?

**Comment by romelperez** [comment]
In case there is no workaround, it used a [conditional import](https://github.com/zeit/next.js/issues/219) of Spectacle in the client side.

But it would be great to have server-side support, at least to "import" them not use them.

**Comment by tim-soft** [comment]
SSR support would be excellent, conditional require in componentDidMount is obviously not great on performance

**Comment by kenwheeler** [comment]
The Deck tag takes a custom history. This should allow you to pass in different histories more suited for the server.

**Comment by iamstarkov** [comment]
@kenwheeler indeed `Deck` takes custom history, but you have no chance to get that far: somehow any import from spectacle throws `Invariant Violation: Hash history needs a DOM`

**Comment by iamstarkov** [comment]
i had to write special component to load spectacle only on client side

```js
// prettier-ignore
const spectacleExports = [ "Anim", "Appear", "BlockQuote", "Cite", "CodePane", "Code", "ComponentPlayground", "Deck", "Fill", "Fit", "Heading", "Image", "GoToAction", "Layout", "Link", "ListItem", "List", "Magic", "Markdown", "MarkdownSlides", "Notes", "Quote", "S", "Slide", "SlideSet", "TableBody", "TableHeader", "TableHeaderItem", "TableItem", "TableRow", "Table", "Text", "Typeface", "themes" ];

const setToFalse = (state, key) => ({ ...state, [key]: false });
const setTo = spectacle => (state, key) => ({
  ...state,
  [key]: spectacle[key]
});
const isReady = o => Object.values(o).every(x => !!x);

class WithSpectacle extends React.Component {
  constructor(props) {
    super(props);

    this.state = spectacleExports.reduce(setToFalse, {});
  }
  componentDidMount() {
    const spectacle = require("spectacle");

    this.setState(spectacleExports.reduce(setTo(spectacle), {}));
  }
  render() {
    if (!isReady(this.state)) return null;

    return this.props.render(this.state);
  }
}
```

@romelperez

**Comment by iamstarkov** [comment]
it is due to this line in in [controller.js](https://github.com/FormidableLabs/spectacle/blob/9391dfb003bba53a4230e73d699333c679b197fe/src/utils/controller.js#L10)

```js
const history = createHistory();
```

which is invoked straight away, so it will be invoked whenever this file is imported. And it happens in [`deck.js`](https://github.com/FormidableLabs/spectacle/blob/9391dfb003bba53a4230e73d699333c679b197fe/src/components/deck.js#L7). And deck is imported in [index.js](https://github.com/FormidableLabs/spectacle/blob/9391dfb003bba53a4230e73d699333c679b197fe/src/index.js#L8)

**Comment by iamstarkov** [comment]
@dharmeshkakadia have you tried it? I use dynamic import in client-side only react lifecycle method

**Comment by iamstarkov** [comment]
@dharmeshkakadia  you do not import anything from spectacle manually, you should utilise (like I use `Deck` from the callback argument) render prop's callback's arguments which reflects [spectacle's exports](https://github.com/FormidableLabs/spectacle/blob/master/src/index.js#L43-L76) and they are:

```js
const spectacleExports = [
  "Anim",
  "Appear",
  "BlockQuote",
  "Cite",
  "CodePane",
  "Code",
  "ComponentPlayground",
  "Deck",
  "Fill",
  "Fit",
  "Heading",
  "Image",
  "GoToAction",
  "Layout",
  "Link",
  "ListItem",
  "List",
  "Magic",
  "Markdown",
  "MarkdownSlides",
  "Notes",
  "Quote",
  "S",
  "Slide",
  "SlideSet",
  "TableBody",
  "TableHeader",
  "TableHeaderItem",
  "TableItem",
  "TableRow",
  "Table",
  "Text",
  "Typeface",
  "themes"
];
```

and I dont see `createTheme` in this list
