### ISSUE TITLE
align doesn't seem to work - all browsers

### ISSUE THREAD

**Issue by emcenrue** [FormidableLabs/spectacle#47]
Perhaps I'm mistaken in the use case, but should the prop for slides, 'align', when set to flex-start or flex-end position the content such that it's placed in one of the corners of the area of the deck or slide or something? When I used align in multiple different spaces, it didn't change anything. Likewise, I ended up replacing the code in slide.jsx with flex-start instead of the default center, and it still didn't do anything. All content was still center justified both vertically and horizontally within the slide. Text align did justify the text properly within their box (the box that stayed in the center no matter what). Again, I'm not sure if I'm misinterpreting the purpose or not, but it's definitely not working if it's meant to justify the content box in a region of the slide/deck/dom. Otherwise, cool project!

**Comment by kenwheeler** [comment]
Can I see a code example @emcenrue ?
