### ISSUE TITLE
Add styling to specific set of slides

### ISSUE THREAD

**Issue by dbendy** [FormidableLabs/spectacle#470]
Let's create a fictitious example: if I have a 10 slide presentation, and I want slides 4 through 7 to have a different background color than the rest of them,  is there a way to do that without setting `bgColor` on all the slides that I want overridden?   Is there a way to possibly wrap those slides in a component, such as `SlideSet` or some alternative, to set styles on all of them?

**Comment by kale-stew** [comment]
There are a couple ways you could go about this currently, but we are open to changing the API and updating the docs to make this more easily accomplished! 

Would you rather
- import an entirely separate `<Deck/>` component to your main index.js that would need to be wrapped in a pair of `<SlideSet>` tags? (this is already possible but not outlined in our docs)
- wrap slides inline of your main `<Deck/>` with a set of `<StyleGroup>` tags that would apply a designated theme (similar to `<span>`)? 
- a third API type of your recommendation that I haven't considered?

**Comment by kale-stew** [comment]
Closing as outdated. We will be handling themes, styling, and templates very differently in the [new spectacle](https://github.com/FormidableLabs/spectacle/issues/716). 🙂
