### ISSUE TITLE
Extends Manager to allow overriding of _handleKeyPress

### ISSUE THREAD

**Issue by welcoMattic** [FormidableLabs/spectacle#472]
Hi, I've opened this [PR](https://github.com/FormidableLabs/spectacle/pull/196) long time ago about keys control.

It is still a need for us to control Spectacle with up and down keys (because most of bluetooth remote are mapped to up and down keys and not to left an right ones).

If it's not possible to add this feature in spectacle core, may be it's possible to let people extends spectacle to add this feature?

Thanks ;)

**Comment by kitten** [comment]
Unfortunately a couple of third party libraries depend on up/down keys for their own transitions, e.g spectacle-code-slide

@kenwheeler is it worth adding a prop enabling this optionally?

**Comment by welcoMattic** [comment]
+1 for a prop to allow `horizontal-nav` or `vertical-nav` ;)

**Comment by kenwheeler** [comment]
Closing in favor of #476, where we'll likely make the key map override-able.
