### ISSUE TITLE
Fix some documentation inconsistencies.

### ISSUE THREAD

**Issue by siakaramalegos** [FormidableLabs/spectacle#475]
I'm creating this issue because I intend to make a PR to fix - I just wanted to get some feedback on a few things first.

- [x] The [table example](http://formidable.com/open-source/spectacle/docs/tag-api/#table-tablerow-tableheaderitem-and-tableitem-base) results in errors. Add TableHeading and TableBody so that the example works.
- [x] [Getting Started](https://github.com/FormidableLabs/spectacle#getting-started) seems to suggest that it's better to not use the boilerplate anymore, but the docs site doesn't mention this. It's also a bit confusing - "This however, doesn't include publish scripts, and ejecting is required for fancy stuff." So what are the exact differences? I don't mind writing this up to change both docs and readme.
- [ ] The [hasSlideChildren](https://github.com/FormidableLabs/spectacle#faq) example in the readme currently doesn't work. [This example](https://github.com/FormidableLabs/spectacle/issues/450#issuecomment-356395447) from the open issue worked for me. Is it ok for me to change the docs to use this as the way to separate slides into different files?
- [ ] `<SlideSet />` is not listed in the docs. I can add it if you give me a blurb about it. My guess is "a way to group slides together", but that seems like a lame explanation. 

If you think of more little things, I'm happy to put them all in this issue (and my PR).

**Comment by kenwheeler** [comment]
I would love these updates!

**Comment by kale-stew** [comment]
@siakaramalegos thank you for pointing these inconsistencies out! we are addressing these in #577 and working to update `<SlideSet />` so it actually functions as documented 😅
