### ISSUE TITLE
Feature Request: Shortcut black hole

### ISSUE THREAD

**Issue by AjkP** [FormidableLabs/spectacle#476]
This might be beyond the scope of spectacle, but I think it would be neat to just override certain shortcuts to go into a black hole (do nothing).

**Comment by AlanFoster** [comment]
As an example use case:

I wish to embed a video into my slides, and the existing functionality is to play/pause the video based on the space bar being pressed. However, currently Spectacle instead goes to the next Slide.

**Comment by kenwheeler** [comment]
Whats the ideal API here? Like a config on Deck that allows overrides by event key?

**Comment by AlanFoster** [comment]
For my particular use case I wished to provide my own implementation for the key shortcuts on a particular set of slides, but I believe @AjkP may have wanted a global handler implementation.

Perhaps the config could be implemented at the slide level, and follow the normal event bubbling mechanism that developers would expect. i.e. If a slide doesn't specify a handler, it will reach the Deck handler which may have the default implementation available 🤔

**Comment by AjkP** [comment]
I really want a set of hotkeys to be overridden by spectacle into doing nothing.

I.e. in the preferences have a `disable hotkeys`, where I can input a bunch of hotkeys I want to do NOTHING ever.

As an explanation about why... it's because I already do it.
Spectacle hotkeys take precedence over all other apps. I use this fact to hack some hotkeys into spectacle hotkeys that I don't care about, so I do not accidentally do something unintended in other apps.

**Comment by kale-stew** [comment]
Closing as outdated - we can re-evaluate this as a feature request against the rewrite when it is released. 🙂
