### ISSUE TITLE
CodePane language highlight not working

### ISSUE THREAD

**Issue by MikeDabrowski** [FormidableLabs/spectacle#480]
CodePane accepts lang as a parameter, which is supposed to be prism compatibile language. Yet after rendering, in chrome dev tools I see `<pre>` tag with language-prism class, and my code is monochrome. 

Why is that?

**Comment by kitten** [comment]
Can you provide a reproduction please? it could simply be that the language you're trying is not supported or that something is going wrong with either the theming or a custom prism CSS file.

> in chrome dev tools I see <pre> tag with language-prism class

Spectacle performs highlighting using the react-live editor, which doesn't use global classes but highlights by generating html using prism's utility functions.

**Comment by MikeDabrowski** [comment]
Ok, so I tried to clean my project of prism js and css bring it back to unmodified state. It didn't work. Then I created new projects using CRA and boilerplate - both works for jsx, java and javascript. 

I think its a matter of my corrupted project.

**Comment by kitten** [comment]
@MikeDabrowski Weird! Maybe someone else will surface some more details at some point so we can document some gotchas :)
