### ISSUE TITLE
Custom history for Deck. Does it work?

### ISSUE THREAD

**Issue by gagarski** [FormidableLabs/spectacle#485]
Hi!

I am not big fan of URLs with hashes (for example, it's hard to type `?presenter` parameter with hashes) and it seems like both development server from standard boilerplate project and surge.sh allow us to serve on "*" url, so we can use `createBrowserHistory` instead of standard spectacle's `createHashHistory`, so I modified index file from boilerplate project as follows:

```tsx
// ...
import createHistory from 'history/createBrowserHistory'
const history = createHistory();
// ...
export default class Presentation extends React.Component {
    render() {
        let props = {
            transition: ["zoom", "slide"],
            transitionDuration: 500,
            theme,
            history
        };
        return (
            <Deck {...props}>
                {/* My slides */}
            </Deck>
        );
    }
}
```

Then I run `yarn start` and go to `http://localhost:3000/3`. It opens third slide which is correct but converts URL to `http://localhost:3000/3#/` Then, when I am navigating through my slides it adds slide number after hash, so URL looks as follows: `http://localhost:3000/3#/2`. 

It seems like a bug: routing works right with `createBrowsingHistory` but it seems like hash history is used when I navigate through slides.

**Comment by gagarski** [comment]
Here is my complete example: `git clone https://github.com/gagarski/spectacle-boilerplate.git && cd spectacle-boilerplate && git checkout no-hash-history`

**Comment by tim-soft** [comment]
I see references to "Add your own history config" but no examples of what that would actually look like

**Comment by gagarski** [comment]
It suddenly started working after upgrading to 4.2.2. 

It still adds `#/` to URL when I open the page in browser but now navigation works normally.
