### ISSUE TITLE
Redux conflict

### ISSUE THREAD

**Issue by shuminyang** [FormidableLabs/spectacle#486]
Hey guys,

I am having some problems when I try to access my own redux store on the elements inside the `<Slide>` component.
For example 

`<Slide>
    <MyComponent />
</Slide>`

When I connect `MyComponent` into react-redux, I end up accessing Spectacle Redux-store.
Am I missing something? Is there a way to merge mine and yours redux store?

Thanks!

**Comment by kenwheeler** [comment]
Hmm. You might have to put your provider inside the slide. Other than that, not seeing a clear fix for this atm. We'll be migrating to use the new context API, so in the future this conflict wont exist.

**Comment by shuminyang** [comment]
Yeah, I see. I "solved" it by using the Context API on my side.
