### ISSUE TITLE
Feature Request: Deck Showcase

### ISSUE THREAD

**Issue by dileep-kishore** [FormidableLabs/spectacle#487]
First of all, thank you for this amazing project. I just recently started using `spectacle` and I like what I see so far. In the past, I have used [`eagle.js`](https://github.com/zulko/eagle.js/) which is pretty good in its own right. What I do miss is the deck showcase where you can get mini previews of all the decks in your slideshow (see [here](https://zulko.github.io/eaglejs-demo/#/)).
I think that this should be pretty straightforward to implement in `spectacle` and would be useful if you had multiple decks to show.

**Comment by kenwheeler** [comment]
I'm not sure I understand this request? Do you mean like when you press option-o in spectacle?

**Comment by dileep-kishore** [comment]
No, I was referring to the ability to show multiple `spectacle` slide decks in an index page. Something like a table of contents that would contain a grid or a table of all the slide decks that are part of the "project".

**Comment by sylvainar** [comment]
You mean overview ? http://stack.formidable.com/spectacle/#/?overview&_k=9k1bip

**Comment by dileep-kishore** [comment]
What I meant was an overview (just a preview of the first slide maybe) of a collection of `Deck`s not `Slide`s.

**Comment by kale-stew** [comment]
Closing as outdated - please see our pinned issue for info on the rewrite. 🙂
