### ISSUE TITLE
many spectacle dependencies bloats my bundle

### ISSUE THREAD

**Issue by hellochar** [FormidableLabs/spectacle#490]
Spectacle alone is doubling my total Webpack bundle size (from 6 -> 13mb in dev mode). There's a few things that I'm personally not using but that are still being included:

1. the code preview component pulls in react-live which pulls in buble which is about 800kb
2. all of d3, unsure why
3. redux and react-redux are pulled in because the appear component

It'd be great if spectacle supported tree shaking like lodash.

**Comment by ryan-roemer** [comment]
@kenwheeler can comment more, but Spectacle is usually targeted at making a presentation deck and not as part of something else. So we have "the kitchen sink" of things like:

- Victory: A visualization library (bringing in d3)
- React Live: For live code samples
- ... and lots of other stuff.

One thing we can do, is also export `es/` for our code with ESM (`import`/`export`). Then, if you are building with something like webpack or rollup, it should DCE anything unused.

I've filed #491 to provide this infrastructure feature. Once that lands, will that take care of all your use cases?

**Comment by ryan-roemer** [comment]
@hellochar -- Take a look at https://github.com/FormidableLabs/spectacle/pull/493 . If you're using modern webpack we now have an `es/` ESM output directory that should get picked up by webpack4 to efficiently include _only_ the files you really need.
