### ISSUE TITLE
BUG: `hjs-webpack` and the `data.css` property

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/spectacle#50]
## The `html.js` end of things.

https://github.com/FormidableLabs/spectacle/blob/master/themes/default/html.js#L12 does this:

```js
            '<link href="' + data.css + '" rel="stylesheet" type="text/css" />',
```

However, with inline styles, I think this is `undefined` which means we get an undefined for `href`. We should have this be a conditional instead before outputting this line.

## The Source Maps end

Apparently `hjs-webpack` does something naive for infering the CSS bundle output. When I override a config with this:

```js
webpackConfig.devtool = "source-map";
```

(Instead of default `eval-source-map`) The CSS link shows up as:

```html
<link href="app.js.map" rel="stylesheet" type="text/css" />
```

and the dumped config data looks like:

```js
 {
  "css": "app.js.map",
  "main": "app.js",
  // ...
```

When switching away from `hjs-webpack`, I'd suggest our dev webpack config use `source-map` right off the bat (because it makes inspecting the dev bundle so, so much easier...

Turning this off we get an `undefined` which I think is expected because we're doing inline styles...

**Comment by knowbody** [comment]
@kenwheeler this can be closed as we don't use hjs-webpack anymore (#110) and this is no longer an issue
