### ISSUE TITLE
Breaking out of the 1000x700 box

### ISSUE THREAD

**Issue by joshwcomeau** [FormidableLabs/spectacle#500]
I've been really loving using Spectacle, thanks so much to all the maintainers and contributors for creating such an amazing project :)

I find that I keep wishing to have a React element be "fullscreen", but I'm limited by `.spectacle-content`, with its max-width of 1000px and max-height of 700px. I know I can set `bgImage` on the `<Slide>` to have a fullscreen image, but the presentation I'm working on has stuff like a full-screen confetti overlay, and I can't figure out how to get that to work.

Because a `transform: scale` is applied to it, I can't break out of it using `position: fixed` as I would normally, because of how CSS transforms work. And I don't seem to be able to "override" the styles on `.spectacle-content` (I don't actually need that `transform: scale`, since all of my transitions are slides or fades).

Curious if there's a workaround I haven't seen? Happy to open a PR if not, just point me in the right direction.

Thanks!

**Comment by tim-soft** [comment]
You can add a className prop to the slide and use the `mySlideStyles::first-child` to override the size of your workable area

**Comment by joshwcomeau** [comment]
Awesome! Thanks @tim-soft.

Do you think it'd be good to add this to the docs somewhere? Happy to open a PR to add it (although I also imagine this isn't a common concern, so totally respect if you don't feel it's important enough to clutter up the README!)

**Comment by tim-soft** [comment]
I didn't build this thing ;)

I think it would make some sense to add a style prop to Slide for directly manipulating the flex container styles.

**Comment by joshwcomeau** [comment]
Ah, sorry for the assumption!

**Comment by kenwheeler** [comment]
This will go away in the near future

**Comment by vadimshvetsov** [comment]
Is it possible to solve width with `styled(Slide)`?
I'm trying to add styles to SlideContent with className from styled-components, but then animation of SlideContainers breaks.
Here is a code:
```
const StyledSlide = styled(Slide)`
  && {
    width: 1500px; // instead of 1000px
  }
`;
```
And the nothing is shown except background.

**Comment by westmark** [comment]
I worked around this problem like so

```import React from 'react';
import { Slide as SpectacleSlide } from 'spectacle';
import styled from 'styled-components';
import logoSrc from '../assets/logo.svg';

const Logo = styled.img`
  position: absolute;
  bottom: 5vw;
  right: 5vw;
  width: 5vw;
`;

const Content = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 100vw;
`;

export default function Slide({ children, className, ...props }) {
  return (
    <SpectacleSlide {...props}>
      <Content className={className}>
        {children}
        <Logo src={logoSrc} />
      </Content>
    </SpectacleSlide>
  );
}```

No idea if this will break things along the way. I only just started with Spectacle an hour ago :)
