### ISSUE TITLE
Is there a way to style MarkdownSlides?

### ISSUE THREAD

**Issue by romellogoodman** [FormidableLabs/spectacle#501]
I want to pass in some of the Base Props to the markdown slides and wondering how I would go about doing this?

I would imagine that something like this would work and the props would get applied to every slide
```
import slidesMarkdown from "raw-loader!markdown.md";

const props = {...someProps};

<Deck ...>
  {MarkdownSlides(slidesMarkdown, props)}
</Deck>
```

**Comment by kenwheeler** [comment]
You would have to either update the theme, or use the Markdown tag

**Comment by romellogoodman** [comment]
Thanks!
