### ISSUE TITLE
GoToSlide And GotoStep

### ISSUE THREAD

**Issue by ironmanromeo** [FormidableLabs/spectacle#503]
I love Spectacle!

But...

I'm looking for a way to "programmatically" go on a specific SLIDE and in particular on a specific STEP. I use Meteor-React and I would like to use Spectacle as a "broadcast" presentation system, but I can not find an "elegant" way to move inside the DECK and in particular into "steps". It would be great to have 2 specific commands (or one to pass the slide and one for the step).

Thanks so much to all the maintainers and contributors!

**Comment by kenwheeler** [comment]
Deck takes a configurable history prop that you could use to override it

**Comment by chowkapo** [comment]
> Deck takes a configurable history prop that you could use to override it

Could you provide more details how to implement this? I cannot find relevant documentation on this history prop. Thanks a lot!

**Comment by kale-stew** [comment]
@chowkapo we have rewritten the library since the comment you're referencing above. This is not currently a supported feature in v6, unfortunately.
