### ISSUE TITLE
Custom Staged Slides

### ISSUE THREAD

**Issue by winstonewert** [FormidableLabs/spectacle#504]
Spectacle is great!

It has a basic system for staged reveals with the <Appear/> but I sometimes want to do more complex things. For example, in my one presentation I have a <div/> which I use css transitions to move around.

I figured out how to make this work by reverse engineering how <Appear/> worked. I added <div className="fragment"/> and then inspect the state to figure which fragment should currently be rendered. But it feels a rather ugly hack. Is there a better way?

**Comment by kenwheeler** [comment]
There is an Anim component now that should suffice
