### ISSUE TITLE
Appear together

### ISSUE THREAD

**Issue by davidsusu** [FormidableLabs/spectacle#505]
I have a slide:

```jsx
<Slide>
  <Appear order={1}>
    <p>Hello 1!</p>
  </Appear>
  <Appear order={2}>
    <p>Hello 2.a!</p>
  </Appear>
  <Appear order={3}>
    <p>Hello 3!</p>
  </Appear>
  <Appear order={2}>
    <p>Hello 2.b!</p>
  </Appear>
</Slide>
```

My expectation is that second and fourth paragraph appear together, however each paragraph appears separately (first, second, fourth, third). Is this a specific design decision? How can I move two items together?

(Of course, I know that `order` is an additional feature added later after behavior of `Appear` originally designed. So, probably it can not be easily changed without breaking something.)

**Comment by kenwheeler** [comment]
That's currently not supported. Order is serial not parallel. Maybe wrap in a common parent?

**Comment by davidsusu** [comment]
@kenwheeler Most of the time common parent isn't applicable. See my example, for example. Furthermore, do you know a manageable workaround for a two-column layout, where text comes from left while image comes from right, at the same time?
