### ISSUE TITLE
X-axis/horizontal alignment property of slide doesn't align text to the left

### ISSUE THREAD

**Issue by thomasfarago** [FormidableLabs/spectacle#506]
I'm trying to get text to align to the left-hand side of the slide, and by looking at the documentation, it looks to me like it should be done like this:

<img width="499" alt="1" src="https://user-images.githubusercontent.com/8206050/38520096-c5434824-3c0f-11e8-844c-47f4b9775993.png">

However, only the second alignment property has any effect:

<img width="1225" alt="default" src="https://user-images.githubusercontent.com/8206050/38520126-d4f72fe2-3c0f-11e8-9441-f5117647a249.png">

It looks to me as if the text component takes up the entire width of the slide, and that's why it doesn't move. But - I did set the fill prop to `false`. Is there another way I should be doing this?

<img width="1234" alt="2" src="https://user-images.githubusercontent.com/8206050/38520170-fda22fd2-3c0f-11e8-9b25-6bbc5f8ff5fb.png">

**Comment by kenwheeler** [comment]
If thats a heading, its a block level element, you would have to change it to inline block or set the justification to left
