### ISSUE TITLE
endValue= { opacity: 0.5 } isn't working

### ISSUE THREAD

**Issue by thomasfarago** [FormidableLabs/spectacle#508]
No matter what kind of tag I put this prop into, it doesn't seem to work. It seems to indicate that there's an issue with the : character.

Is there something I'm missing?

<img width="774" alt="screen shot 2018-04-09 at 7 16 03 pm" src="https://user-images.githubusercontent.com/8206050/38578782-f734fe4a-3cd2-11e8-9899-5b22eab01f87.png">
<img width="697" alt="screen shot 2018-04-09 at 7 16 20 pm" src="https://user-images.githubusercontent.com/8206050/38578783-f745687a-3cd2-11e8-976b-53ac8525a14e.png">

**Comment by mAAdhaTTah** [comment]
That's invalid JSX. The format overall is as such:

```jsx
<Appear endValue={ /* put values in here */ } />
```

The values in there is the object, so you need two curlies:

```jsx
<Appear endValue={{opacity: 0.5}} />
```

**Comment by thomasfarago** [comment]
Cheers!
