### ISSUE TITLE
Question: IE 11 support

### ISSUE THREAD

**Issue by xmclark** [FormidableLabs/spectacle#513]
I noticed some weird behavior when using spectacle in Internet Explorer 11. Does the library aim to support IE11? Regardless, these are a few issues I found.

The demo app has a JavaScript error and fails to show anything. Looks like a babel or polyfill issue:

![2018-04-17 10 18 51](https://user-images.githubusercontent.com/1364747/38885756-e11b031a-4228-11e8-84cb-95d18192d312.gif)

I started the boilerplate app locally and it mostly works, except when you make the window larger. I was running this in parallels on my macbook pro.

![2018-04-17 10 20 24](https://user-images.githubusercontent.com/1364747/38885809-00d93b4a-4229-11e8-8c70-7c9edfc1a110.gif)

**Comment by ryan-roemer** [comment]
Can you try polyfilling `Object.assign` and see if that helps.

See, e.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill or https://www.npmjs.com/package/object.assign
