### ISSUE TITLE
<align> doesn't work on <BlockQuote>

### ISSUE THREAD

**Issue by thomasfarago** [FormidableLabs/spectacle#514]
Trying to assign align="flex-start center" to a BlockQuote.

Not working. Any way to fix this?

**Comment by manjula91** [comment]
Can take this up !!

**Comment by samwhale** [comment]
@thomasfarago Can you share a minimal repo with the bug?

**Comment by ebrillhart** [comment]
Hi @thomasfarago the `textAlign` prop seems to be working as intended when I test it out. Closing for now, but if I'm misunderstanding the issue or you're encountering another one, please feel free to open a new issue!
