### ISSUE TITLE
Importing `webpack.config.js` fails from Node cli

### ISSUE THREAD

**Issue by bebraw** [FormidableLabs/spectacle#52]
This is because you have a line like

> if (process.argv[1].indexOf('webpack-dev-server') !== -1) {

there. `argv` can be shorter than that.

Instead it would make sense to check the length before accessing

> if (process.argv.length > 1 && process.argv[1].indexOf('webpack-dev-server') !== -1) {

**Comment by kenwheeler** [comment]
I'm switching away from `hjs-webpack` in the very near future

**Comment by kenwheeler** [comment]
Closing as I'm refactoring the webpack config
