### ISSUE TITLE
API for control actions

### ISSUE THREAD

**Issue by goldhand** [FormidableLabs/spectacle#521]
I'd like to trigger slide changes pragmatically. I'm not sure if there is an api for this but it would be really helpful!

example to help clarify what I would like to do:
```js
import {controls} from 'spectacle';

controls.next(); // goes to next slide
```

Alternatively, exposing the `store` would allow me to do what I want as well. Or if I could pass an optional `store` value [somewhere in the `Deck` component](https://github.com/FormidableLabs/spectacle/blob/da099a02a73976c35d9f984f67493243abb980a7/src/components/deck.js#L25) and import the [root reducer](https://github.com/FormidableLabs/spectacle/blob/f578f8eab486bc4bc8f18243741a21c58d399ebf/src/store/index.js#L2) so I could do things with it.

**Comment by kale-stew** [comment]
Closing as outdated, but I have added this to our rewrite roadmap. Please see our pinned issue for more info
