### ISSUE TITLE
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3"

### ISSUE THREAD

**Issue by rccclr** [FormidableLabs/spectacle#522]
When 
npm start 
o 
yarn start

Thanks

**Comment by PT-Jessica** [comment]
Please any help ? I installed updated version for babel 7 but this error displays in console while I run npm start or npm install.

Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing preset: "C:\\Users\\japolinar\\Documents\\orion-github\\pt-orion-rh\\node_modules\\@babel\\preset-env\\lib\\index.js")

**Comment by joeLloyd** [comment]
@PT-Jessica try this

`yarn add babel-core@7.0.0-bridge.0`

it got rid of the error for me

src https://github.com/parcel-bundler/parcel/issues/868#issuecomment-386829133

**Comment by LeBenLeBen** [comment]
I have a similar issue on a fresh clone of the repository, here‘s more info:

```
ERROR in ./index.js
Module build failed: Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
    at throwVersionError (/Users/leben/Sites/spectacle/node_modules/@babel/helper-plugin-utils/lib/index.js:62:11)
    at Object.assertVersion (/Users/leben/Sites/spectacle/node_modules/@babel/helper-plugin-utils/lib/index.js:11:11)
    at /Users/leben/Sites/spectacle/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js:15:7
    at /Users/leben/Sites/spectacle/node_modules/@babel/helper-plugin-utils/lib/index.js:16:12
    at Function.memoisePluginContainer (/Users/leben/Sites/spectacle/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/Users/leben/Sites/spectacle/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /Users/leben/Sites/spectacle/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/leben/Sites/spectacle/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/leben/Sites/spectacle/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/leben/Sites/spectacle/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/leben/Sites/spectacle/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/leben/Sites/spectacle/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/leben/Sites/spectacle/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/leben/Sites/spectacle/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/leben/Sites/spectacle/node_modules/babel-loader/lib/index.js:173:20)
 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./index
```

**Comment by kenwheeler** [comment]
Can someone provide a repo that demonstrates this issue so that I can investigate further?

**Comment by horacioh** [comment]
I don't think this is related to the project but jest itself. this error happens to me with a plain javascript setup.. I can share my setup @kenwheeler but dunno if its relevant in this project

**Comment by artyomtrityak** [comment]
you can use `npm install babel-loader@next` if you're using webpack

**Comment by gogulanareshkw** [comment]
please help me to resolve compatibilty issue.

 "dependencies": {
    "@babel/core": "^7.0.0-beta.55",
    "@babel/preset-env": "^7.0.0-beta.55",
    "@babel/preset-react": "^7.0.0-beta.55",
    "native-base": "^2.6.1",
    "react": "^16.4.1",
    "react-native": "^0.55.4",
    "react-native-code-push": "^5.4.1",
    "react-native-vector-icons": "^4.6.0",
  },
  "devDependencies": {
    "babel-eslint": "^6.1.2",
    "babel-jest": "^23.4.2",
    "babel-preset-react-native": "^4.0.0",
    "chai": "^3.5.0",
    "eslint": "^3.5.0",
    "eslint-config-airbnb": "^11.1.0",
    "eslint-plugin-import": "^1.14.0",
    "eslint-plugin-jsx-a11y": "^2.2.1",
    "eslint-plugin-react": "^6.2.0",
    "eslint-plugin-react-native": "^2.0.0",
    "jest": "17.0.0",
    "jest-react-native": "17.0.0",
    "mocha": "^2.5.3",
  },



![image](https://user-images.githubusercontent.com/40063274/43506108-b598ba6e-9586-11e8-88c2-a5524d145435.png)

**Comment by rayj10** [comment]
@rmc33 tried ur solution, giving me this upon installation:

No matching version found for babel-loader@8.0.0-beta
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

any idea why?

**Comment by rmc33** [comment]
Hi @rayj10 
That is because you are using babel-loader**@**8.0.0-beta instead of babel-loader**@^**8.0.0-beta. There is no specific version 8.0.0-beta so if you wanted to reference a specific 8 version check https://www.npmjs.com/package/babel-loader, I see the latest is babel-loader@8.0.0-beta**.4**

**Comment by rayj10** [comment]
@rmc33 Ah yes i see thanks for the pointers! :smile:

**Comment by rmc33** [comment]
@rayj10 no problem, as you can see babel-core changed to @babel/core at version 7 which will cause these problems if you are still using loaders, plugins or presets that use babel-core, maybe you need to keep babel-core for some time or go ahead and upgrade if they are available for @babel/core.

**Comment by peterrattew** [comment]
I would recommend using [Babel Upgrade](https://github.com/babel/babel-upgrade) and let it update all your dependencies to whats needed.

**Comment by developer239** [comment]
@peterrattew thank you so much 🙂 that tool is priceless

**Comment by harrison-ifeanyichukwu** [comment]
@PT-Jessica, @LeBenLeBen , @joeLloyd 
in version 7, babel decided to implement their stuffs as **scoped packages**, whereby you simply replace `babel-` to `@babel/`.

**Examples:**
`babel-register` => `@babel/register`
`babel-core` => `@babel/core`.

if you are using babel 7, then you have to install all dependencies with the naming convention shown above. `babel-eslint` would be `@babel/eslint`, same applies to `babel-jest`, etc.

when referencing the packages, reference them as they are too.
e.g is shown in this `babelrc` below
```
{
    "presets": ["@babel/preset-env"]
}
```

[Read migration article at babel website](https://babeljs.io/docs/en/v7-migration)

**Comment by ccorcos** [comment]
I think the problem has to do with Jest using an older version of Babel.

**Comment by ccorcos** [comment]
Maybe try forcing Jest to use babel 7. 

https://github.com/babel/babel/issues/8206#issuecomment-399137890

```
"resolutions": {
	"babel-core": "7.0.0-bridge.0"
},
```

**Comment by elangovanshanthi** [comment]
Just add  `"@babel/cli": "^7.0.0"`  into your `package.json` file and `npm install.`
It will resolve this issue.

**Comment by za-ek** [comment]
Replacing all packages like 'babel-core', 'babel-cli' etc.. with '@babel/core', '@babel/cli' solve the problem.

**Comment by brybrophy** [comment]
I just dealt with this issue after upgrading all of the packages in react-progressive-image.

The problem there was with `babel-jest`.  The babel-jest repo has this note in it.
<img width="910" alt="screen shot 2018-09-19 at 7 31 29 pm" src="https://user-images.githubusercontent.com/16469185/45792476-b6784980-bc42-11e8-8db7-2eb57a51fb66.png">

**Comment by bhariyani** [comment]
install "@babel/core": "^7.1.0" that will fix.

**Comment by DZuz14** [comment]
For me it was as simple as:
```
"@babel/core": "^7.0.0",
"babel-core": "^7.0.0-bridge.0",
```
Jest was not working until I added the bridge package below @babel/core

**Comment by ruslankhh** [comment]
I fix this problem with them.
```
npm i -D jest babel-jest babel-core@^7.0.0-bridge.0 @babel/core regenerator-runtime
```
```js
// babel.config.js
'use strict';

module.exports = {
  presets: [
    '@babel/preset-env',
    '@babel/preset-react'
  ],
  plugins: [
    '@babel/plugin-transform-modules-commonjs',
    '@babel/plugin-transform-object-assign',
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-proposal-object-rest-spread'
  ]
};
```
```js
// jest.config.js
'use strict';

module.exports = {
    transform: {
        '^.+\\.jsx$': 'babel-jest',
        '^.+\\.js$': 'babel-jest'
    }
};
```

**Comment by GTOsss** [comment]
I have the same problem.

Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3"...

I tryed install 

Package.json:
```
"dependencies": {
    "colors": "^1.3.2",
    "stringify-object": "^3.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.1.2",
    "@babel/plugin-transform-modules-commonjs": "^7.1.0",
    "@babel/preset-env": "^7.1.0",
    "@babel/preset-react": "^7.0.0",
    "babel-cli": "^6.26.0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-loader": "^8.0.4",
    "cross-env": "^5.2.0",
    "webpack": "^4.23.1",
    "webpack-cli": "^3.1.2"
  }
```

.babelrc:
```
{
  "presets": ["@babel/preset-env", "@babel/preset-react"],
  "env": {
    "development": {
      "plugins": ["@babel/plugin-transform-modules-commonjs"]
    },
    "production": {
      "plugins": ["@babel/plugin-transform-modules-commonjs"]
    }
  }
}
```

**Comment by rmc33** [comment]
Oh I see you don’t need babel-core since you have @babel/core and replace babel-cli with @babel/cli

**Comment by GTOsss** [comment]
@rmc33 Thank you!

**Comment by harrison-ifeanyichukwu** [comment]
I am using jest with **babel 7**. here is how i did it and it is working very fine, install the following packages

```
npm install -D @babel/core @babel/preset-env babel-jest babel-core@^7.0.0-bridge.0 regenerator-runtime
```

**Comment by xuxinhang** [comment]
Please check carefully whether there is `babel-core` or other Babel7-styled npm package in your `node_modules`. Remove the whole `node_modules` and `yarn.lock`, then re-install all the packages again.
That works for my gulp configuration.

**Comment by sambarrowclough** [comment]
replace 
```
"babel-cli": "^6.26.0",
```

with 
```
"@babel/cli": "^7.1.2",
```

**Comment by yutianhaijiao** [comment]
I started with NPM and then I started with yarn ，so I use rm -rf node_moudules  and package_lock.json without work . at last  rm -rf yarn.lock and rm -rf node_moudules . and then  yarn install  .it is work fine.

**Comment by ashishdommety** [comment]
Installing `babel-core@^7.0.0-bridge.0` seems to work for me -- I already had `"@babel/core": "^7.1.6"` installed though.
Any pointers on why just `@babel-core` doesn't do the trick?

**Comment by SilentFlute** [comment]
hi guys, i occur this problem too, and i try many solve ways above these answers, `babel-core@7.0.0-bridge.0` even upgraded `babel-loader` from `8.0.0` to `8.0.4`, until i see @Harrison Ifeanyichukwu , he mentioned `@babel/register`, and i realized i had `babel-register`, so i install `@babel/register` to instead it, then the problem still there, and i search `babel-register`, i find there is a `js` use it, and i change it to `@babel/register`, so that's it, the problem is solved!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by SilentFlute** [comment]
@harrison-ifeanyichukwu i am sorry😂😂

**Comment by bruevin-paul** [comment]
"dependencies": {
    "express": "^4.16.4",
    "mongodb": "^3.1.10",
    "react": "^16.7.0",
    "react-dom": "^16.7.0"
  },
  "devDependencies": {
    "@babel/core": "^7.2.2",
    "@babel/preset-env": "^7.2.3",
    "@babel/preset-react": "^7.0.0",
    "@babel/preset-stage-2": "^7.0.0",
    "babel-core": "6.x || ^7.0.0-bridge.0",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^8.0.4",
    "eslint": "^5.11.0",
    "eslint-plugin-react": "^7.11.1",
    "nodemon": "^1.18.9",
    "webpack": "^4.28.2",
    "webpack-cli": "^3.1.2"
  }

Getting same error pls assist me to fix

**Comment by kevinsimper** [comment]
I made a working example of `babel-jest` after an hour of errors, so if any poor soul lands on this issue: https://github.com/kevinsimper/babel-jest-example

**Comment by igbominadeveloper** [comment]
> hi guys, i occur this problem too, and i try many solve ways above these answers, `babel-core@7.0.0-bridge.0` even upgraded `babel-loader` from `8.0.0` to `8.0.4`, until i see @harrison Ifeanyichukwu , he mentioned `@babel/register`, and i realized i had `babel-register`, so i install `@babel/register` to instead it, then the problem still there, and i search `babel-register`, i find there is a `js` use it, and i change it to `@babel/register`, so that's it, the problem is solved!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Did you edit your node_modules file?

**Comment by SilentFlute** [comment]
> > hi guys, i occur this problem too, and i try many solve ways above these answers, `babel-core@7.0.0-bridge.0` even upgraded `babel-loader` from `8.0.0` to `8.0.4`, until i see @harrison Ifeanyichukwu , he mentioned `@babel/register`, and i realized i had `babel-register`, so i install `@babel/register` to instead it, then the problem still there, and i search `babel-register`, i find there is a `js` use it, and i change it to `@babel/register`, so that's it, the problem is solved!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> Did you edit your node_modules file?

Nope!!!! Only the `webpack` config files, and now, I used a scaffold, it solved all the bundle and compile things, that I can focus on programming

**Comment by paulowski** [comment]
I searched on the internet and tried different solution (attempts). Nothing worked. Among others I also removed `package.json` and `node_modules`. What worked is to uninstall `babel-jest` with having jest as the only modules parsing my tests.
This confuses me because I thought the `jest` module's [responsibility](https://en.wikipedia.org/wiki/Single_responsibility_principle) is only parsing test (`\(...).+\.test.js\`) files. Or does babel the job? Would be a pleasure to enlighten me.
PS: Of course I tried the normal and officially documented way of [installation](https://jestjs.io/docs/en/getting-started#using-babel).
```js
{
  (...)
  "devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.2.2",
    "@babel/preset-env": "^7.2.3",
    "@babel/preset-typescript": "^7.1.0",
    "@types/jest": "^23.3.12",
    "babel-core": "^7.0.0-bridge.0",
    "jest": "^23.6.0",
    "regenerator-runtime": "^0.13.1",
    "tslint": "^5.12.0",
    "typescript": "^3.2.2"
  },
  "dependencies": {}
}
```

**Comment by blairbodnar** [comment]
> I made a working example of `babel-jest` after an hour of errors, so if any poor soul lands on this issue: https://github.com/kevinsimper/babel-jest-example

Thanks for this @kevinsimper !

**Comment by meanmachine22** [comment]
{
  "name": "babel_comp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "babel src --out-dir dist"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.4.0",
    "@babel/node": "^7.2.2",
    "@babel/preset-env": "^7.4.1",
    "nodemon": "^1.18.10"
  }
}


.babelrc
{
    "presets": [ "@babel/preset-env"]
  }

Still getting the same 
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. 

This is the error when I write a sample ES6 component and try to compile babel to ES5 with babel server/index.js -o server/index_comp.js

Is this problem still occurring or is it fixed??

**Comment by ebrillhart** [comment]
@meanmachine22 if you're using the latest version of Spectacle, the expectation is that this should be fixed!

**Comment by GavinMoreYoung** [comment]
maybe you could install global babel-cli, you can try command : npm uninstall -g babel-cli babel-node.you need install @babel/cli and @babel/node.
OR
you can uninstall node and remove npm file in C:\Users\Administrator\AppData\Roaming
i hope i can help you.good luck

**Comment by KKica** [comment]
If you are using babelify 7.3, update to 9.0
See my answer [on stackoverflow](https://stackoverflow.com/questions/55542042/error-after-upgrading-to-babel-7-requires-babel-7-0-0-0-but-was-loaded-with)

**Comment by pitaz** [comment]
Installing packages with `yarn` instead of `npm` solved this issue for me.

**Comment by chutzstudio** [comment]
> you can use `npm install babel-loader@next` if you're using webpack

OMG BRO, YOU SAVED MY DAY!

**Comment by stevendaye** [comment]
Very bizarre. Me rather, I npm uninstall babel-core: --save-dev, and it works like a charm.

PS: I mean the package babel-core: ^7.0.0-bridge.0"

**Comment by 97thjingba** [comment]
If it does not work still when you intall **babel-core ^7.0.0-bridge.0"**.
you can try change you .babelrc to babel.config.js 
it work for me

**Comment by maggiew61** [comment]
 I tried all the methods here until my colleague pointed out that I didn't remove another babel v6 package, and so it was still there in package.json. I removed it and installed a few babel v7 packages and it finally worked. 

this is my working .babelrc
`{
  "presets": [
    [
      "@babel/preset-env"
    ],
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-runtime"
  ]
}`

this is my working package.json
`{
  "name": "twshopping_frontend_webapp_reactredux_example",
  "version": "0.0.0",
  "description": "A starter project for react redux best practices.",
  "main": "index.js",
  "scripts": {
    "lint": "standard --env jest",
    "start": "nodemon",
    "test": "jest"
  },
  "repository": {
    "type": "git",
    "url": "git@git.ouroath.com:cwang06/twshopping_frontend_webapp.git"
  },
  "author": "chenen",
  "license": "MIT",
  "devDependencies": {
    "@babel/cli": "^7.0.0",
    "@babel/core": "^7.8.4",
    "@babel/node": "^7.8.4",
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/plugin-transform-runtime": "^7.8.3",
    "@babel/preset-env": "^7.8.4",
    "@babel/preset-react": "^7.8.3",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^25.1.0",
    "jest": "^25.1.0",
    "nodemon": "^2.0.2",
    "standard": "^14.3.1"
  },
  "dependencies": {
    "babel-upgrade": "^1.0.1",
    "express": "^4.17.1",
    "iso-redux": "^1.3.12",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-redux": "^7.1.3",
    "redux": "^4.0.5",
    "redux-actions": "^2.6.5"
  }
}
`

**Comment by LiMengyang990726** [comment]
> � �I tried all the methods here until my colleague pointed out that I didn't remove another babel v6 package, and so it was still there in package.json. I removed it and installed a few babel v7 packages and it finally worked.
> 
> this is my working .babelrc
> {
> "presets": [
> [
> "@babel/preset-env"
> ],
> "@babel/preset-react"
> ],
> "plugins": [
> "@babel/plugin-proposal-class-properties",
> "@babel/plugin-transform-runtime"
> ]
> }
> 
> this is a part of my working package.json
> "devDependencies": {
> "@babel/cli": "^7.0.0",
> "@babel/core": "^7.8.4",
> "@babel/node": "^7.8.4",
> "@babel/plugin-proposal-class-properties": "^7.8.3",
> "@babel/plugin-transform-runtime": "^7.8.3",
> "@babel/preset-env": "^7.8.4",
> "@babel/preset-react": "^7.8.3",
> "babel-core": "^7.0.0-bridge.0",
> "babel-jest": "^25.1.0",
> "jest": "^25.1.0",
> "nodemon": "^2.0.2",
> "standard": "^14.3.1"
> },
> "dependencies": {
> "babel-upgrade": "^1.0.1",
> "express": "^4.17.1",
> "iso-redux": "^1.3.12",
> "react": "^16.12.0",
> "react-dom": "^16.12.0",
> "react-redux": "^7.1.3",
> "redux": "^4.0.5",
> "redux-actions": "^2.6.5"
> }
> 
> the key working factor for me was that I didn't remove all babel v6 related packages and so it was still conflicting with the new babel v7 stuff.
> 
> I hope it will help out someone.

Hi do you know how to remove all babel v6 related packages?

**Comment by maggiew61** [comment]
hi @LiMengyang990726  check out [this stackoverflow ](https://stackoverflow.com/questions/52157996/how-to-upgrade-to-babel-7)response regarding to package changes. 

> Most of the packages in Babel has been renamed to follow the pattern @babel/PACKAGE_NAME

I had 3 babel packages installed while also having babel v7 installed that caused the conflict. I removed all 3 babel packages that didn't have the `@` prefix. hope it helps

**Comment by LiMengyang990726** [comment]
> hi @LiMengyang990726 check out [this stackoverflow ](https://stackoverflow.com/questions/52157996/how-to-upgrade-to-babel-7)response regarding to package changes.
> 
> > Most of the packages in Babel has been renamed to follow the pattern @babel/PACKAGE_NAME
> 
> I removed all 3 babel packages that didn't have the `@` prefix, which meant they are older versions and are v6 packages. hope it helps

Thank you! I have solved it by changing all the babel related packages in "x-x" into "@x/x"

**Comment by vintagexav** [comment]
> Replacing all packages like 'babel-core', 'babel-cli' etc.. with '@babel/core', '@babel/cli' solve the problem.

You deserve a medal <3
