### ISSUE TITLE
Can't yarn install due to npm.ematix.org timeout

### ISSUE THREAD

**Issue by jfirebaugh** [FormidableLabs/spectacle#523]
Trying to clone and install so I can make a change to spectacle:

```
~/Development/spectacle $ yarn
yarn install v1.6.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "http://npm.ematix.org:5000/prettier/-/prettier-1.11.1.tgz: ETIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/Users/john/Development/spectacle/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

This is due to the following entry in yarn.lock:

https://github.com/FormidableLabs/spectacle/blob/80a8445ba41231594f7c1fc88f127ec8cd47d879/yarn.lock#L7491-L7493

I think this is somebody's private npm mirror that got committed accidentally (in #511, it looks like).

**Comment by joshuacrass** [comment]
This was my bad. Sorry. This PR needs to be merged or the build will continue to fail as the mirror no longer exists.
