### ISSUE TITLE
`CodePane` throws when using `lang="java"`

### ISSUE THREAD

**Issue by rainboxx** [FormidableLabs/spectacle#526]
Repository to reproduce: https://github.com/rainboxx/spectacle-issue

It seems that loading all language files, as of now, doesn't have any impact because `react-live` [loads Prism itself and only 4 language](https://github.com/FormidableLabs/react-live/blob/d71d13d079fc99cafcb65ec19ec057fc54a3492a/src/utils/prism.js.) files. The language files ([see Java for example](https://github.com/PrismJS/prism/blob/master/components/prism-java.js)) itself expects a global called `Prism`, so I interpret that reloading Prism removes all previously loaded language files.

**Comment by sevenfoxes** [comment]
I have this problem with Dart too.

**Comment by rainboxx** [comment]
@sevenfoxes #528 should fix this, too.

**Comment by rawrmonstar** [comment]
This was fixed in #546
