### ISSUE TITLE
Feature Request: Master Slide / Slide Templates

### ISSUE THREAD

**Issue by adamgruber** [FormidableLabs/spectacle#529]
A big feature in other presentation software is the ability to define a master / template slide that has some styling on it or maybe a background image. This slide can become the basis for all other slides in the deck.

Maybe something like this:

```jsx
const MasterSlide = () => <Slide bgImage="something" />;

// ...

<Deck masterSlide={masterSlide}>
    <Slide>...</Slide>
</Deck>
```

Or it could be a prop on the `<Slide>` itself. Something like
```jsx
<Slide template={slideTemplateA}>
    //...
</Slide>
```

**Comment by sylvainar** [comment]
I personally use : 
```jsx
const slideDefaults = {
  bgColor: "primary",
…
};

…

<Slide {...slideDefaults}>

</Slide>
```

HOCs can help you too.

**Comment by kale-stew** [comment]
We will be handling slide templates and themes differently in [new spectacle](https://github.com/FormidableLabs/spectacle/issues/716), so I am closing this issue in favor of the impending API change
