### ISSUE TITLE
Document how to make components that render Slides

### ISSUE THREAD

**Issue by bdarnell** [FormidableLabs/spectacle#536]
I'm trying to make a react component that produces a spectacle `Slide`. I've run into a couple of problems that resulted in cryptic error messages (at least to me as a react novice) or mysterious misbehavior. Specifically, function-based components don't seem to work, and all `props` must be passed through to the slide even if no such props are visible in your presentation.js file.

The simplest possible custom slide component (as far as I've been able to determine) is therefore

```
class MySlide extends React.Component {
  render() {
    return <Slide {...this.props}>...</Slide>
  }
}
```

It would be great if there were some documentation about this.

**Comment by kenwheeler** [comment]
Does using the hasSlideChildren prop, when using the new component work for you?

**Comment by kitten** [comment]
@kenwheeler I've tried researching and refactoring to support this use-case before, if you recall it, and the biggest (only?) blocker was how slide transitions are handled using hooks on the component, instead of props or other means of animating.

Now that popmotion pose is pretty solid I'd propose for us to refactor to that and introduce a state for the transitions, i.e.: `'before-active' | 'active' | 'after-active'` (this would probably be enough to encode all three states and hence transitions of a slide)

**Comment by kenwheeler** [comment]
@kitten I fully support that refactor, but does that solve this particular issue?

**Comment by kitten** [comment]
@kenwheeler it's a long way off tbh, but such a refactor would ultimately aim at removing all assumptions around the deck, slides, and context structure. It's a huge chunk of work though

**Comment by bdarnell** [comment]
I didn't use transitions in my presentation, so it's possible that I missed something that would make transitions work (I see that [codeslide has some methods](https://github.com/jamiebuilds/spectacle-code-slide/blob/978dffec405d14d135057f99b6306ed2717b46a0/src/CodeSlide.js#L75-L106) that I didn't implement here)

I think my issue is mainly separate from transitions: function-based components raise errors (related to methods like componentWillMount being undefined) and if props aren't passed through things don't get sized properly.

Even with components defined as shown in my original message, things still don't get sized properly in presenter view or PDF export, so I may be missing something else here.

**Comment by loraxx753** [comment]
Not sure if it helps or is even related, but I've been building up my custom slides like this:

```
import React from 'react'
import { Deck, Slide, Text } from 'spectacle'

const FirstSlide = props => {
  return (
    <Slide>
      <Text>Hello there {props.key}.</Text>
      <Text>Ready?</Text>
    </Slide>
  )
}
const SecondSlide = props => {
  return (
    <Slide {...props}>
      <Text>Hello there {props.key}.</Text>
      <Text>Steady...</Text>
    </Slide>
  )
}

export const slides = [
  FirstSlide,
  SecondSlide,
  props => {
    return (
      <Slide>
        <Text>Hello there {props.key}.</Text>
        <Text>Let's rock.</Text>
      </Slide>
    )
  }
]

export default props => (
  <Deck>
    {slides.map((Slide, i) => Slide({ key: i, last: !(i <= slides.length) }))}
  </Deck>
)
```

**Comment by benwiley4000** [comment]
The comments in the first post helped me solve my problem. Animations started kicking in once I started spreading all my unused props to the child `Slide` component in my custom components.

```jsx
class MyCustomSlide extends Component {
  render() {
    const { someprop, ...rest } = this.props;
    return (
      <Slide {...rest}>
        {/*...*/}
      </Slide>
    ); 
  }
}
```

**Comment by affanshahid** [comment]
Even spreading the props isnt working for me, is this something thats on the "roadmap" ? Amazing stuff would be even better if I can break up my slides into components

**Comment by kale-stew** [comment]
Closing as outdated. We are rewriting the library and will re-evaluate documentation requests like these once it is released. 🙂
