### ISSUE TITLE
Using insecure websockets prevents deployment with https.

### ISSUE THREAD

**Issue by vpicone** [FormidableLabs/spectacle#539]
## Expected Behavior
Building and deploying the build folder should result in a site that presents content without being blocked by modern browsers.

## Actual Behavior
Using the ws:// protocol instead of the wss://protocol makes it so the browser blocks the entire content of the page.

### Initial Page Load
<img width="980" alt="initial-page-load" src="https://user-images.githubusercontent.com/4078018/40977065-85a86a70-6895-11e8-8f4f-9e228613c93a.png">

### Before "Loading Unsafe Scripts"
<img width="980" alt="before-permitting-scripts" src="https://user-images.githubusercontent.com/4078018/40977076-8d7f7ba8-6895-11e8-9465-194e8416ac54.png">

### After "Loading Unsafe Scripts"
<img width="980" alt="after-permitting-scripts" src="https://user-images.githubusercontent.com/4078018/40977125-b7243660-6895-11e8-8a31-6c8f03c0b1e5.png">

## Steps to Reproduce the Problem
  1. Install with the CRA workflow `create-react-app my-presentation --scripts-version spectacle-scripts`
  1. Run `yarn build` or `npm run build`
  1. Deploy the build folder using now or surge or GitHub pages i.e. `cd build && now --static`
  1. Open the deployment in Chrome and view the blocked script indicator on the right hand side of the URL bar.

## Fixing the problem
I fixed the problem by digging through the node_modules folder and changing every instance of ws:// to wss:// and it worked perfectly. I'd be happy to make a PR if someone with more experience with sockets can chime in with any potential issues.

## Specifications
  - Version: spectacle-scripts: "2.0.0"
  - Platform: Firefox developer edition, Chrome 66

**Comment by ryan-roemer** [comment]
Introduced in https://github.com/FormidableLabs/spectacle/pull/495

**Comment by ryan-roemer** [comment]
One page spectacle is already hitting this (which uses current off unpkg). For example, https://rawgit.com/seanode/welcome/meetup/may-2018/welcome.html#/1 gives us:

![screen shot 2018-06-05 at 8 04 27 am](https://user-images.githubusercontent.com/445557/40984589-1dd037a0-6897-11e8-9145-61d16f1f8842.png)

And even master in this repo hits it: https://rawgit.com/FormidableLabs/spectacle/master/one-page.html

**Comment by ryan-roemer** [comment]
Reverted websocket integration in https://github.com/FormidableLabs/spectacle/pull/543

https://rawgit.com/seanode/welcome/meetup/may-2018/welcome.html#/1 and https://rawgit.com/FormidableLabs/spectacle/master/one-page.html both work now...
