### ISSUE TITLE
Use `https` as default for Google Fonts

### ISSUE THREAD

**Issue by bebraw** [FormidableLabs/spectacle#54]
That would be a better default especially if you are hosting over GitHub Pages or such (https enabled). Otherwise browser will give a warning about mixed content and fail to render the fonts.

**Comment by kenwheeler** [comment]
Good call

**Comment by bebraw** [comment]
Actually probably what you want to do is to skip `http` or `https` altogether and let browser resolve it. Likely just `//` will do the trick.

**Comment by alexlande** [comment]
`//` is an anti-pattern, no reason not to use `https` :+1:

**Comment by kenwheeler** [comment]
Done
