### ISSUE TITLE
Testing for PR #543

### ISSUE THREAD

**Issue by samwhale** [FormidableLabs/spectacle#544]
Need to add testing for use of `localStorage` in Spectacle. WebSocket support has been removed for the time being, but if that gets reintroduced or used we should add testing for that as well.

Rel #543

**Comment by kale-stew** [comment]
@samwhale did you have a particular strategy for these tests in mind?

**Comment by samwhale** [comment]
Oof it's been a while since I thought about this 😄.

I think the thing that's valuable to test here is whether or not the slides are changing correctly. These local storage changes are getting made when slides are changing, so we can use the localStorage as a way to verify that the slides changed correctly.

If `_goToSlide` is called, then I would expect the value in my local storage to have that slide.

```
test('should change go to the specified slide.', () => {
    const wrapper = mount(
      <Manager transition={['zoom', 'slide']} transitionDuration={500}>
        <MockSlide />
        <MockSlide />
      </Manager>,
      { context: _mockContext(0, []), childContextTypes: _mockChildContext() }
    );

    // trigger a slide change here to make sure _goToSlide() is called

     const msgData = localStorage.getItem('spectacle-slide');
     expect(msgData.slide).toEqual(// the slide we changed it to);
  });
```

what do you think?

**Comment by kale-stew** [comment]
Closing this in favor of a new strategy we discussed offline 🎉
