### ISSUE TITLE
Doesn't work in FF: CSS2Properties doesn't have an indexed property setter in FF

### ISSUE THREAD

**Issue by suevalov** [FormidableLabs/spectacle#55]
The bug is reproducible since 0.0.3. The problem is only during Deck mode. Presenter mode works just fine. This breaks JS on the page and controls don't work at all.

For 0.0.2 everything works fine.

**Comment by kenwheeler** [comment]
What isn't working? I just fired up my FF with master and didn't see a problem.

**Comment by suevalov** [comment]
Sorry for insufficient explanation. 

Transition between slides doesn't work. Basically, slide is rendered, but with these errors. After this you can't translate between slides.
I reproduced the bug on FF 35.0.1 on MacOS, but today I was notified by my colleague about the same problem on latest version on Windows. My presentation just didn't work in his FF.

Just jumped to the latest revision and launched demo presentation. 
![mozilla_firefox_and_doesn_t_work_in_ff__css2properties_doesn_t_have_an_indexed_property_setter_in_ff_ _issue__55_ _formidablelabs_spectacle](https://cloud.githubusercontent.com/assets/3672221/9395877/c3bfa500-4799-11e5-8710-04147b38fd5d.png)

**Comment by kenwheeler** [comment]
What code is it erroring on?

**Comment by kenwheeler** [comment]
Whats line 160?

**Comment by suevalov** [comment]
It goes to 1385 line, which is CSSPropertyOperations React module.

The only thing I could find is https://github.com/anselmh/object-fit/issues/5, but i didn't help to localize the problem in Spectacle.

**Comment by suevalov** [comment]
Did you manage to reproduce the issue?

**Comment by kenwheeler** [comment]
I have not been able to reproduce in FF. Do you know the line in Spectacle that this originates from?

**Comment by kenwheeler** [comment]
Any news on this? Closing, will reopen pending more details.

**Comment by elbaro** [comment]
Ran into this old issue. Download the example [one-page.html](https://github.com/FormidableLabs/spectacle/blob/master/one-page.html) and open it with FF. The page 13 is broken.

**Comment by VirtualDOMinic** [comment]
Closing this issue as I only reopened it to address @elbaro 's more recent comment!

One pager should work as expected in latest master (thanks to #687 )
