### ISSUE TITLE
Greater control on magic moves

### ISSUE THREAD

**Issue by LucaFranceschini** [FormidableLabs/spectacle#550]
From the documentation:

> [...] An upcoming patch will allow for custom keys, which will provide greater control over which elements are identified as common for reuse.
>
> Until then, feedback is very welcome, as this is a non-trivial feature and we anticipate iterating on the behind the scenes mechanics of how it works, so that we can accommodate most use cases.

So... here I am.

Currently, is there any way/hack to have some control over magic moves? Is there any ongoing attempt to implement this?

Consider the following:

```
<Magic>
  <Slide>
    <Heading>This magic</Heading>
  </Slide>
  <Slide>
    <Heading>This is magic</Heading>
  </Slide>
</Magic>
```

Arguably, the most natural thing to expect would be for "this" and "magic" to get more distant letting "is" to appear between them. What spectacle does is to move the "i" from "magic" to the newly appearing word "is", and make another "i" appear in place of the original one.

I do not even know what reasoning is happening behind the choice of elements to reuse, except it is based on text. Would it be possible to add some kind of heuristic? Like, maybe it is a bad idea to move this letter if I am going to substitute it with the same one? Sorry for being naive, I did not dig much into the code behind this.

I also tried to wrap words in a `<span>`, failing miserably.

**Comment by ebrillhart** [comment]
Thanks @LucaFranceschini, we'll look into this!

**Comment by kale-stew** [comment]
Closing as outdated -- magic move functionality is currently broken and not on the roadmap to be fixed before our rewrite is released.
