### ISSUE TITLE
Firefox complains about "TypeError: CSS2Properties doesn't have an indexed property setter for '0'"

### ISSUE THREAD

**Issue by thochra** [FormidableLabs/spectacle#551]
Hello,

I was giving a try to some markdown support and I found that with tables it fails at rendering on Firefox.
I'm using the boilerplate (with the "patch" 4.0.4 applied on the package.json => https://github.com/FormidableLabs/spectacle-boilerplate/issues/57).

```
$ yarn list spectacle
yarn list v1.7.0
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ spectacle@4.3.1
Done in 0.58s.
```

The presentation code is this one:
```
      <Deck transition={["slide"]} transitionDuration={500} theme={theme}>
        <Slide>
          <Markdown>
            {`
# Title 1
Some text for fun
## Title 2
            `}
          </Markdown>
        </Slide>
        <Slide>
          <Markdown>
            {`
some text

| header 1 | header 2 | header |
|----------|----------|--------|
| pony     | carot    | rabbit |
| cat      | dog      | wolf   |

some text
            `}
          </Markdown>
        </Slide>
      </Deck>
```

By going on slide 2 it should fail with firefox but not with chromium.

I tried to go to the source of the issue but it's to hard for me at moment (too junior at react development).
I hope you'll be able to reproduce it easily.

Best,
Thomas

**Comment by ebrillhart** [comment]
Thanks @thochra, we'll look into this!

**Comment by rawrmonstar** [comment]
@thochra sorry for taking so long to investigate this. I can no longer reproduce using the current spectacle boilerplate and up-to-date stable Firefox. Please let me know if you are still experiencing this issue. Thanks 😄
