### ISSUE TITLE
Opt to have bgImage .gif files not replay?

### ISSUE THREAD

**Issue by thomasfarago** [FormidableLabs/spectacle#553]
Is this an option that can be added? Would help greatly.

(Having them stop on the last frame would be amazing.)

**Comment by ebrillhart** [comment]
Hi @thomasfarago, unfortunately this is a pretty complicated piece of functionality and has much more to do with the .gif file itself than with anything that we could reasonably add to the Spectacle library. I hope you're able to find another workaround for this issue! Might be worth looking into processing the image with something like https://davidwalsh.name/prevent-gif-loop before adding it to the presentation. I am going to close this as it's not a feature that we are planning to add.
