### ISSUE TITLE
bgImage load lag

### ISSUE THREAD

**Issue by thomasfarago** [FormidableLabs/spectacle#555]
I think it makes a lot of sense to have the next ~5-10 slides' images (<img> tag and **bgImage**s) load in advance, so as to ensure that there's a seamless transition. I have some **bgImage**s that are higher-resolution images (or animated .gifs), and they frustratingly take too long to get going when Spectacle is loading them in.

One caveat here is that gifs don't start from their beginning points after you've triggered them to play and then you leave their slide and come back to it shortly thereafter. So - there would need to be something that loads the gifs in advance, but makes sure that they start only when the slide they're in is in view.

What does everyone think of this?

**Comment by angelo-v** [comment]
+1 The lag until `bgImage` is loaded is really annoying and nearly a show stopper

**Comment by SamFrampton01** [comment]
+1 the lag until bgImage is loaded is super annoying and doesn't render to cover full page first time. Often have to flick to next slide and back to fit cover.

**Comment by kale-stew** [comment]
Closing as outdated - please see our pinned issue for all things rewrite-related. 🙂
