### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by Alekos92** [FormidableLabs/spectacle#556]
I have been trying for several hours to get typescript to work with spectacle. 
The @types/spectacle definition file seems to have several shortcomings, like missing components. For example, Anim is not even included.

The only way I managed to get the full functionality of spectacle was to clone the repo and work from there. This way my typescript React components were functioning properly in my presentation... 
Given that typescript is very much an industry standard now, I would appreciate it if the repo offered a solution to get started with typescript.

**Comment by ebrillhart** [comment]
Thanks @Alekos92, we'll consider this.

**Comment by Alekos92** [comment]
Greetings, 

I have not been using Visual Studio, I have been using WebStorm. I don't think it's an IDE-specific problem, though. I think the main issue is missing definitions and definitions with wrong argument types.

For the time being, I have decided to bite the bullet and use regular-old JavaScript, and I haven't touched on this issue for months. If I do and realize that the issue has been resolved, I will report back.

**Comment by suhailsinghbains** [comment]
I had been working on Visual Studio, it's a pain to use it with TypeScript and importing ReactJS Libraries. However, this is not our issue.
>If I do and realize that the issue has been resolved, I will report back.

Yeah, sure. I'll try it myself in a bit too :)

**Comment by kale-stew** [comment]
I've opened a PR in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) to update our type definitions, which you can track [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31146). It looks like the current definitions are _extremely_ out of date with the latest features/API, which would explain the problems you're reporting @Alekos92.

**Comment by ebrillhart** [comment]
Closing this issue as type defs have been updated in DefinitelyTyped! See Kylie's comment for more details.
