### ISSUE TITLE
Prism version conflict: Continuation of #546

### ISSUE THREAD

**Issue by imranolas** [FormidableLabs/spectacle#558]
Continuation of #546 

The `tl;dr` is that the "normal" way we import Prism in `react-live` and `spectacle` completely collide as Prism doesn't allow for multiple versions to exist, so we're currently bandaiding to always use `1.6.0`.

Work:

- [ ] Research and identify a better means of allowing us to have multiple projects with potentially _different_ versions of prism installed.

**Comment by kale-stew** [comment]
Closed as outdated - package updates were merged.
