### ISSUE TITLE
Wrong slide transition after using overview mode

### ISSUE THREAD

**Issue by Alekos92** [FormidableLabs/spectacle#559]
I noticed there's some sort of a bug when using overview mode to move back in the presentation. 

Steps to reproduce:

- Open multi-slide Spectacle presentation.
- Go to one of the last slides of the presentation.
- Use overview mode (Alt + O) to overview slides and select first slide of presentation.
- Press right arrow button to transition to second slide.
- Presentation actually moves to the slide we were previously when we toggled overview mode.

This is quite frustrating, as overview is useful to move back and forth in the presentation, and often it's required to go to the next slide after using overview mode.

**Comment by ebrillhart** [comment]
Thanks @Alekos92, we'll look into this.
