### ISSUE TITLE
Feature Request: code-slide with semantic highlighting and walk-through

### ISSUE THREAD

**Issue by Benjamsk** [FormidableLabs/spectacle#565]
Thanks for building such a great library for presentations.

I see many struggle with compatibility of the spectacle-code-slide with newer versions of spectacle, and so I suggest adding a code-slide with semantic highlighting and "walk-through-the-code" features (highlighting code in focus, darkening/blurring out-of-focus code) to the spectacle package.

Thanks again

**Comment by ebrillhart** [comment]
Thanks @Benjamsk! Looking into this.

**Comment by vadimshvetsov** [comment]
@ebrillhart I've faced with many restrictions while was using `spectacle-code-slide`. The idea with jumping in code is so awesome for presenting, but there is no active maintainers. I see many great PR's and nobody merges this. I would like to maintain this library or trying to transfer this functional to spectacle as a component.Is it possible? @kenwheeler has an access to maintaining this library as I know

**Comment by vadimshvetsov** [comment]
@ryan-roemer yeah, I know that this project is not a Formidable project, but there is a closed issue tracker and the last publisher is Ken 😄 Anyway, would be glad to do anything in this direction to get convenient code-walking slide (maintain or reimplement inside spectacle)

**Comment by kale-stew** [comment]
Closing as outdated - we are rewriting the library and have added this feature request to the roadmap. 🎉  Please see our pinned issue for more info.
