### ISSUE TITLE
Keyboard events don't play well with react-live

### ISSUE THREAD

**Issue by doronnac** [FormidableLabs/spectacle#567]
Noticed that keyboard events still work while inside react-live's pseudo textarea. Looking in the code, there is indeed a special handling for textarea but for the standard one only.

I submitted a [PR](https://github.com/FormidableLabs/spectacle/pull/566) which adds awareness for react-live textarea, and also added `keyboard` prop in Deck component to manually toggle keyboard events.

Tests will probably not pass, but if you want this PR (or parts of it) merged I'll gladly take responsibility to make it so.

**Comment by boygirl** [comment]
closed by https://github.com/FormidableLabs/spectacle/pull/566
