### ISSUE TITLE
Allow SlideSets to be defined

### ISSUE THREAD

**Issue by bebraw** [FormidableLabs/spectacle#57]
Currently you are forced to maintain all your `Slides` in a single `Deck`. It would be useful if it was possible to defined `SlideSets` like this:

``` html
<Deck ...>
  <SlideSet ...>
    <Slide ...>...</Slide>
    ...
  </SlideSet>
  ...
</Deck>
```

After this you could push `SlideSets` to outside of the main file easily. As the current system expects `Slides` to belong directly below `Deck` this is hard/impossible to achieve (yup, tried _many_ ways).

**Comment by MarkRedeman** [comment]
For anyone else wanting to separate their slides from their decks, this is how I've done it (it is similar to how #32 has implemented extension of slides):

First I've extended the `Slide` component so that it will render the ouput of a `contents()` method.
```
import {Slide as SpectacleSlide} from "../src/spectacle";

/**
 * I'm using this class so that in deck.js I can use small independent slide components
 * Since most of my slides will use a default transition I also provide some default props
 */
export default class Slide extends SpectacleSlide {
    render() {
      this.props.children = this.contents();
      return super.render();
    }
}

Slide.defaultProps = {
  ...SpectacleSlide.defaultProps,
  transition: ["slide", "fade"]
};
```

Then if I want to create a new slide I can do this:
```
export class Title extends Slide {
  contents() {
    return (
      <div>
        <Heading size={1} caps textColor="primary" fit>
          My Title
        </Heading>
      </div>
    );
  }
}
Title.defaultProps = {
  ...Slide.defaultProps,
  bgImage: images.dna.replace("/", ""),
  bgDarken: 0.5
};

export class AboutMe extends Slide {
  contents() {
    return (
      <div>
        <Heading size={1} caps textColor="black" fit>
          @MarkRedeman
        </Heading>
      </div>
    );
  }
}
```

Next in `deck.js` I import all slides and render them one at a time:
```
import * as Introduction from "./introduction";

// other stuff
render() {
    return (
        <Deck transition={["slide", "fade"]} transitionDuration={500} progress="pacman">
                <Introduction.Title notes="Title notes" />
                <Introduction.AboutMe notes="About me notes." />
        </Deck>
    );
}
```

**Comment by firstdoit** [comment]
This is a nice hack, but `SlideSet`s would definitely be simpler.

**Comment by kenwheeler** [comment]
cc @ryan-roemer as I prep for 1.0.0 release, this is a big one I want to solve. You had mentioned being able to hop set by set, like in Reveal. Is there an ideal way that this would work?

**Comment by ryan-roemer** [comment]
@kenwheeler -- Basically, just like reveal for http://cascadiajs2014.formidablelabs.com/#/title

* Esc: Overview and arrows navigate grid
* Up / Down / Left / Right normally navigate grid
* Space / Shift Space: Replace normal "forward" / "back" capability going through slides in actual order.

**Comment by danecando** [comment]
This is how I'm currently splitting up my Slides. I still need to pass props to Slide inside of the Deck but this works for me.

Container.jsx
```jsx
import React from 'react';
import { Layout, Fill } from 'spectacle';

class Container extends React.Component {
  render() {
    return (
      <Layout>
        <Fill>
          {this.props.children}
        </Fill>
      </Layout>
    );
  }
}

Container.propTypes = {
  children: React.PropTypes.node.isRequired
};

export default Container;
export { Container };
```

TitleSlide.jsx
```jsx
import React from 'react';
import Container from '../Container';
import {
  Heading,
  Image,
  Text
} from 'spectacle';
import { reactLogo } from '../../images';

class TitleSlide extends React.Component {
  render() {
    return (
      <Container>
        <Heading size={1} lineHeight={1} textColor="white">
          React
        </Heading>
        <Text textSize="1.5em" margin="20px 0px 0px" bold>Hit Your Right Arrow To Begin!</Text>
      </Container>
    );
  }
}

export default TitleSlide;
```

**Comment by mikenikles** [comment]
This looks related to #164 where I left a [comment](https://github.com/FormidableLabs/spectacle/issues/164#issuecomment-275894782) with a link to a blog post and Github repo to show how I load slides dynamically.

If there's any feedback on my approach, I'd be happy to see if I can open a PR. I'd like to see what people think though before I go too deep into the code. Thanks

**Comment by zachhale** [comment]
I wrote a solution for adding support for `<SlideSet />` in #280! It currently just includes support for organizing slides. Support for 2D navigation of slides like in reveal isn't implemented yet.

**Comment by zachhale** [comment]
Upgraded the overview to navigate slides as a 2D grid in #285 cc @ryan-roemer @kenwheeler
