### ISSUE TITLE
Feature request: Brighten background images

### ISSUE THREAD

**Issue by codepunkt** [FormidableLabs/spectacle#570]
Sometimes you have images that can only be placed on bright backgrounds. That is easily doable with a bright `bgColor`, but whenever you use a `bgImage`, you can only darken it using `bgDarken`.

I would like to be able to have background images, that are lightened up instead.

API proposals:
1. add `bgLighten` to do so _or_
2. add something like `bgBrightness` or `bgImageBrightness` which could be a value between -1 (darken) and 1 (brighten)

Any thoughts on that?

**Comment by ebrillhart** [comment]
Hey @codepunkt! This is something that's in-progress and will be merged soon. Thanks! Closing with reference to #445

**Comment by codepunkt** [comment]
Thanks Emma! 👍
