### ISSUE TITLE
Suspicious HTML fontSize setting

### ISSUE THREAD

**Issue by totemcaf** [FormidableLabs/spectacle#572]
I was seeing in slide-wrapper.js that any wrapped component modifies the fontSize of the HTML tag based on its own zoom state.

```
    if (!this.props.viewerScaleMode) {
      document.documentElement.style.fontSize = `${16 * this.state.zoom}px`;
    }
```

Is this correct?

What's the use of "viewerScaleMode" attribute?

I was looking for the code that modifies the fontSize of the HTML element after the page starts rendering.

**Comment by ebrillhart** [comment]
Hi @totemcaf! Could you give a bit more detail about what you're trying to do/looking for, or the issue you're running into? That would help me make sure we answer your question fully!

**Comment by ebrillhart** [comment]
Hey @totemcaf since we haven't heard from you I'm going to close this issue. Please feel free to re-open if it's still causing you problems!
