### ISSUE TITLE
Notes only mode

### ISSUE THREAD

**Issue by philipwhiuk** [FormidableLabs/spectacle#578]
It would be nice to have a mode that just provided a printable version of the notes for each slides.

This would be good for scenarios where you won't have a second screen to present from and want to print your slide notes.

It would render as a fairly basic page with the notes for all the slides.

`/?notes` seems like the right URL flag.

**Comment by ebrillhart** [comment]
Thanks @philipwhiuk, we'll look into adding this!

**Comment by kale-stew** [comment]
Closing as outdated, but we have added this feature to our rewrite roadmap! Please see our [pinned issue](https://github.com/FormidableLabs/spectacle/issues/716) for more information about our rewrite endeavor.

**Comment by philipwhiuk** [comment]
Rewrite roadmap sounds great - will keep an eye on it in case there’s anything I / community can do.
