### ISSUE TITLE
Quote tag not visible in Blockquote

### ISSUE THREAD

**Issue by ElreyB** [FormidableLabs/spectacle#580]
### Describe Your Environment
 What version of Spectacle are you using? (can be found by running `npm list spectacle`)
	-spectacle-scripts@2.0.0
 	-spectacle@4.4.1

 What version of React are you using? (can be found by running `npm list react`)
	-react@16.4.2

 What browser are you using?
	-Chrome

 What machine are you on?
	-Mac

 ### Describe the Problem

When using the `BlockQuote` tag the `Quote` tag is not visible. When inspecting the `Quote` tag it is rendering to the DOM but has the same text color as the background color making the tag invisible. 

 **Steps to reproduce:**
1. Used `npm create react-app quote-issue --scripts-version spectacle-scripts
` to create a presentation.
2. After running `npm install` and `npm start` I removed the `Deck` tag and all it’s content from the `presentation.js` file.
3. Created a new `Deck` tag with a single `Slide` tag with the example boilerplate `BlockQuote` and its content.

 **Expected behavior:** 
	-To see the example quote.

 **Actual behavior:** 
	-The `Quote` tag is not visible. 

 **Relevant Code:**

presentation.js
```
// Import React
import React from 'react';

// Import Spectacle Core tags
import {
  BlockQuote,
  Cite,
  Deck,
  Heading,
  ListItem,
  List,
  Quote,
  Slide,
  Text
} from 'spectacle';

// Import theme
import createTheme from 'spectacle/lib/themes/default';

// Require CSS
require('normalize.css');

const theme = createTheme(
  {
    primary: 'white',
    secondary: '#1F2022',
    tertiary: '#03A9FC',
    quartenary: '#CECECE'
  },
  {
    primary: 'Montserrat',
    secondary: 'Helvetica'
  }
);

export default class Presentation extends React.Component {
  render() {
    return (
      <Deck>
        <Slide>
          <BlockQuote>
            <Quote>Example Quote</Quote>
            <Cite>Author</Cite>
          </BlockQuote>
        </Slide>
      </Deck>
    );
  }
}
```
![screen shot 2018-09-05 at 1 20 46 pm](https://user-images.githubusercontent.com/20192033/45120900-5ba80380-b114-11e8-8225-b44c5b6e98a0.png)

 Fork our [simple Spectacle sample Sandbox](), reproduce your issue in the code, and paste the link here.

git@github.com:ElreyB/quote-issue.git

 ### Additional Information
 Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by ebrillhart** [comment]
hey @ElreyB! my suspicion is that in the default theme, both the slide background and the quote tag are assigned the same color. can you try applying `textColor: 'primary'` as a prop to the `<Quote/>` tag?

**Comment by ElreyB** [comment]
@ebrillhart When using `textColor: 'primary'` it still doesn't show up. I am assume this is the default textColor for the `Quote` tag because when I use `textColor: 'secondary'` it shows up.

**Comment by ebrillhart** [comment]
okay! I might look at this a little more to make sure my assumptions are correct. thanks for raising!

**Comment by ebrillhart** [comment]
Okay, my assumptions on this were correct, and the right fix is to update which color the Quote uses if default theme is applied. Thanks for helping to clarify this in the docs!
