### ISSUE TITLE
Poor performance in Chromium

### ISSUE THREAD

**Issue by LucaFranceschini** [FormidableLabs/spectacle#582]
I experience poor performance in Chromium when I start the presentation, namely, transitions are definitely not smooth. Even running the boilerplate example or the live demo on the website exhibits the problem. In Firefox transitions are smooth.

I am using Chromium 69.0.3497.8, on an Arch Linux 64 bits machine.

Is this some kind of known issue? If so, is there a known solution?
Otherwise, can I do something to narrow the problem?

**Comment by ebertmi** [comment]
@LucaFranceschini are you using slides.com or spectacle? Slides.com uses reval.js for the presentations and is not react based.

**Comment by LucaFranceschini** [comment]
@ebertmi Sorry I messed up cause I was trying both. Edited, thanks. Sorry for confusion.

**Comment by ebrillhart** [comment]
Hi @LucaFranceschini thanks for the info, we'll look into this.

**Comment by kale-stew** [comment]
Closing as outdated - we are rewriting the library 🎉  Please see our pinned issue for more info
