### ISSUE TITLE
Password protected presentation

### ISSUE THREAD

**Issue by limoozyn** [FormidableLabs/spectacle#584]
Hi,

### Description

It would be great, if presentation has option to prompt password before showing actual presentation.
It is for the use case if presentation is shared by link but needs authorize user before showing him slide.

**Comment by ebrillhart** [comment]
Hi @limoozyn thanks for the feedback! This is an interesting idea, but not one that we are going to pursue - for the meantime, a manual way to get around this would be sharing the link in a password-protected document or other secure file-sharing method. I'll close this issue, but hope this helps!
