### ISSUE TITLE
Visible menu to turn on Autoplay, Overview, Fullscreen, Print etc.

### ISSUE THREAD

**Issue by limoozyn** [FormidableLabs/spectacle#585]
### Description
Hi,

My use case is shareable presentation. So the target person surely is unaware of  keyboard shortcuts.
It would be great to have visible menu somewhere on the bottom of the screen, which duplicate the shortcuts functionality.

**Comment by kale-stew** [comment]
Closing as outdated, but I am adding this to our rewrite Roadmap! Please see our pinned issue for more info
