### ISSUE TITLE
SlideSet behavior is not as expected

### ISSUE THREAD

**Issue by kale-stew** [FormidableLabs/spectacle#586]
### Describe Your Environment

What version of Spectacle are you using? `"spectacle": "5.1.0"`

What version of React are you using? `"react": "16.4.2"`

What browser are you using? Google Chrome

What machine are you on? Mac OSX

### Describe the Problem

[This CodePen](https://codesandbox.io/s/6wyvy4p85n) describes the problem well.

**Expected behavior:** We should be able to extend styles to a set of slides using `<SlideSet />` or wrapping the slides in a div that has been supplied the prop `hasChildrenSlides`.

**Actual behavior:** `<SlideSet />` does not allow for this. We can't

(1) Wrap a set of slides with SlideSet and extend styles to just that set
(2) Wrap our slides into a separate `<Deck />` component and require it in our main presentation, wrapped with `<SlideSet />`
(3) Any other combination of `hasChildrenSlides` and a div still does not allow an extension of styles to those slides

_Also_, you can't wrap a single Slide into a SlideSet. You have to toggle `hasChildrenSlides` to `false` to make it work. 🙃 

```jsx
<SlideSet hasSlideChildren={false}>
    <Slide>2</Slide>
</SlideSet>
```

### Proposed Changes

I think we can bulk up `<SlideSet />` to handle these cases.

**Comment by ebrillhart** [comment]
Fixed
