### ISSUE TITLE
Support isomorphic rendering

### ISSUE THREAD

**Issue by bebraw** [FormidableLabs/spectacle#59]
This way you get a little faster load I think. I know it's a minor thing but it's not that hard to setup. See [my boilerplate](https://github.com/survivejs/react-component-boilerplate). This might be feasible if you make it easier to customize Webpack configuration.

**Comment by kenwheeler** [comment]
Closing this because 1. There is very specific dom reference in this lib that will have a bad time on the server and 2. It is designed to be built and hosted as a static SPA.
