### ISSUE TITLE
How can I separate my slides into other files?

### ISSUE THREAD

**Issue by ganeshchand** [FormidableLabs/spectacle#593]
This section in the README.md is left empty. If it's possible to separate slides into separate files, could you please document it?

**Comment by ebrillhart** [comment]
Hi @ganeshchand, thanks for raising this issue. We'll fix the documentation.

In the meantime, the easiest way to separate slides into separate files (if you mean what I think you mean) is to create a component in a separate file that modifies a `<Slide />` component in the way that you want, and then importing it into your presentation index file. 

Let me know if you have any other questions.

**Comment by ebrillhart** [comment]
Going to close this since it's not actionable beyond the feature that we're already slated to fix.
