### ISSUE TITLE
Add a "Getting Started" Tutorial

### ISSUE THREAD

**Issue by ebrillhart** [FormidableLabs/spectacle#594]
### Description

I'd like to have a basic "getting started" tutorial for Spectacle similar to [the one we have for Victory](https://formidable.com/open-source/victory/docs/)

### Proposal

I'd like to add it in a separate TUTORIAL.md file at the root level of the project and then link to it in the main README in the getting started section.

**Comment by audoralc** [comment]
Would be happy to help out with this if it's still available.

**Comment by ebrillhart** [comment]
@audoralc yep! feel free to take a whack at it. assign yourself to the issue if you start working on it, and good luck 🙂!

**Comment by suhailsinghbains** [comment]
Hi, can I be assigned this bug, would love to work on it :)

**Comment by ebrillhart** [comment]
github won't let me formally assign you @suhailsinghbains but go for it!

**Comment by suhailsinghbains** [comment]
Okay, no problem, working on it :)

**Comment by suhailsinghbains** [comment]
r ? @ebrillhart
