### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by kenwheeler** [FormidableLabs/spectacle#6]
do it

**Comment by kenwheeler** [comment]
done

**Comment by ryan-roemer** [comment]
@kenwheeler -- Does this print to PDF as a direct analogue to the presentation itself? (meaning background images, background colors, etc.)

If so, maybe also consider an `export to printable-paper-friendly PDF`?

**Comment by kenwheeler** [comment]
@ryan-roemer It does, and good point. Would you retain layout for a print style sheet and just cast all the text colors black? Or would you default to a more default version?

**Comment by kenwheeler** [comment]
Reopened for adding printer paper mode (white background, black text)

**Comment by kenwheeler** [comment]
Fixed via 9e7553919b12fcf230354a9e740b8893303e8f5b
