### ISSUE TITLE
How i can use HashRouter 

### ISSUE THREAD

**Issue by CaoThien96** [FormidableLabs/spectacle#601]
### Question
I see http://stack.formidable.com/spectacle/ , url is http://stack.formidable.com/spectacle/#/0 .
I want to do like it but when i use HashRouter. When i change slide url change from 
http://localhost:3000/#/admin/present to http://localhost:3000/#/1.
Please help me fix it. Thank you everyone

**Comment by ebrillhart** [comment]
hey @CaoThien96 could you throw together a quick codesandbox to illustrate more fully the problem you're running into? thanks!
