### ISSUE TITLE
Vertical Slides

### ISSUE THREAD

**Issue by AndyOGo** [FormidableLabs/spectacle#603]
### Description

It would be nice to have support for vertical slides similar to `reveal.js`.

### Proposal

None yet.

### Links / References

DEMO: https://revealjs.com/#/2
Content: https://github.com/hakimel/reveal.js#markup

**Comment by denny64** [comment]
Any updates on if this will happen?

**Comment by kale-stew** [comment]
An update: I've add this feature request to our internal Roadmap for the [rewrite](https://github.com/FormidableLabs/spectacle/issues/716) endeavor.

**Comment by kale-stew** [comment]
Closing as outdated in favor of the rewrite - please see our pinned issue for more info. 🙂
