### ISSUE TITLE
iframe fullwidth background ?

### ISSUE THREAD

**Issue by lecardozo** [FormidableLabs/spectacle#604]
### Question
I'm trying to reproduce the same behavior of [Reveal.js iframe backgrounds](https://github.com/hakimel/reveal.js/#iframe-backgrounds) with spectacle but, so far, I haven't been successful. I think a similar approach could be used for #510. Any idea on how could I achieve this?

Thanks for such a great project! :smile: 

### Background Info/Attempts
What I tried, so far:

```JSX
const fullScreenSlide = {
    position: 'relative',
    height: '100%',
    width: '100%'
}

const iframeStyle = {
    border: 'none',
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: 0
}

<Slide style={fullScreenSlide}>
    <iframe src='https://...' style={iframeStyle}></iframe>
</Slide>
```

**Comment by ebrillhart** [comment]
@lecardozo we'll look into this, thanks!

**Comment by kale-stew** [comment]
Closing as outdated for now - feel free to reopen if the solution in #683 doesn't work for you. 🙂
