### ISSUE TITLE
Show time left in presentation mode

### ISSUE THREAD

**Issue by bebraw** [FormidableLabs/spectacle#61]
It would be handy to show **remaining** time instead of the current time. One way to solve this would be to allow the user to set the presentation length at config and then use countdown based on that when presentation mode is activated.

**Comment by kenwheeler** [comment]
would this initiate on load? start button in presenter mode?

**Comment by bebraw** [comment]
Good question. Start button would likely make sense. Might as well have "stop" as well (change button state) so you can take a break. :+1:

**Comment by pedrottimark** [comment]
@bebraw When you say "set the presentation length at config" do you mean an attribute of the Deck component or a property in the JavaScript config object?

For an attribute in the JSX, your comment in #67 about #57 causes me to ask: if you could also set the intended length for sections (slide subsets) of a presentation, whether you have any brainstorm about a visual indicator in Presenter mode to see if you are approximately on your intended pace?

**Comment by bebraw** [comment]
> For an attribute in the JSX, your comment in #67 about #57 causes me to ask: if you could also set the intended length for sections (slide subsets) of a presentation, whether you have any brainstorm about a visual indicator in Presenter mode to see if you are approximately on your intended pace?

That's a great idea! Perhaps the setting belongs to JSX level indeed. :+1:

Originally I had just generic presentation time in mind since usually you have a fixed amount of time. Even then, it's fixed to certain actual time (i.e., 14:00) rather than length. Anyway, that's semantics.

The timing point you made is interesting and I had not thought about that. I feel it's important, though, as this way you have more control during presentation and can slow/speed up as needed. Maybe it takes some experimentation to find a good solution for this.

**Comment by pedrottimark** [comment]
@bebraw Good points about a fixed end point and the need for some experimentation. I will ask some people at the local meet ups how they think about this issue. Any “user research” you can do is welcome.

**Comment by bebraw** [comment]
@pedrottimark I don't do a lot of presentations sadly. Just being able to set the end time at the beginning of a presentation for the countdown would be enough for my simple purposes. :+1:

**Comment by otorrillas** [comment]
Hey @bebraw @pedrottimark check out my PR and see if you find it useful: #295

**Comment by ebrillhart** [comment]
Closing this - I think #295 satisfies the general need!
