### ISSUE TITLE
Spectacle Scripts + React 16.6 - unable to run build

### ISSUE THREAD

**Issue by 40x** [FormidableLabs/spectacle#610]
### Describe Your Environment

What version of Spectacle are you using? (can be found by running `npm list spectacle`)

└─┬ spectacle-scripts@2.0.0
  └── spectacle@4.4.1

What version of React are you using? (can be found by running `npm list react`)

└── react@16.6.0

What browser are you using?

Chrome

What machine are you on?

MacBook

### Describe the Problem

Build fails with an error:

<img width="670" alt="screen shot 2018-11-06 at 3 28 53 pm" src="https://user-images.githubusercontent.com/10065828/48094816-cc34d480-e1d8-11e8-9752-6c9218347111.png">

**Expected behavior:** [What you expect to happen]

 Builds successfully

Additional Info:

package.json file

```
{
  "name": "spec",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.6.0",
    "react-dom": "^16.6.0",
    "spectacle-scripts": "2.0.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

**Comment by ibelem** [comment]
Exact same build error on Windows 10, please help.

package.json file:

```
{
  "name": "my-presentation",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "jest-cli": "^23.6.0",
    "react": "^16.6.1",
    "react-dom": "^16.6.1",
    "spectacle-scripts": "2.0.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

npm run-script build

```
> my-presentation@0.1.0 build C:\Users\zhangmin\Documents\GitHub\webgpu_webml_updates
> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/buble/node_modules/regexpu-core/rewrite-pattern.js:33

Read more here: http://bit.ly/2tRViJ9
```

**Comment by ebrillhart** [comment]
This should be fixed with an update to spectacle scripts
