### ISSUE TITLE
Anim does not animate transforms on g tags.

### ISSUE THREAD

**Issue by motleydev** [FormidableLabs/spectacle#614]
**Expected behavior:** [What you expect to happen]
Anim to animate `<g />` tags.
**Actual behavior:** [What actually happens]
Does not animate g tags using transform.
### Additional Information
I'll try to ad some code when I have a moment, but for now the issue can be reported.

**Comment by motleydev** [comment]
The issue is that it doesn't work without units like px after the values.

**Comment by kale-stew** [comment]
Closing as outdated - please see our pinned issue for updates on the rewrite. 🙂
