### ISSUE TITLE
Display a react component in a slide

### ISSUE THREAD

**Issue by sarath-sasikumar** [FormidableLabs/spectacle#616]
### Question

Is it possible to display a react component in each individual slides. 

### Background Info/Attempts

I would like to have a react component rendered in each of the slides, rather than any particular `<Text/>` etc.
I have tried putting in the `<div/>` inside the `<Slide/>` tag but it does not seem to work.

**Comment by ebrillhart** [comment]
Hey @sarath-sasikumar are you trying to display the code for the component or the component itself?

**Comment by sarath-sasikumar** [comment]
Is there any answer for this !!.
It would be of great help !

**Comment by ebrillhart** [comment]
@sarath-sasikumar If I understand correctly, this should just be working as-is! If you could post an example from codesandbox or similar, that might help us see the issue you're running into.
