### ISSUE TITLE
IE11: Viewport is not displayed properly

### ISSUE THREAD

**Issue by bndray** [FormidableLabs/spectacle#620]
Using IE11, the viewport is not displaying properly - the width of the slides are not fitting the width of the viewport, would it be possible to get support on this? 

Spectacle version: Spectacle@5.2.2
OS: Windows 10
React version: react@15.6.2
Browser: IE11 (operates correctly on chrome/firefox

Thanks in advance!

**Comment by kale-stew** [comment]
Hi @bndray - could you provide a little more info? In what way is the viewport not displaying properly? Do you have any screenshots?

**Comment by kale-stew** [comment]
Closing for (1) lack of response and (2) incoming rewrite release
