### ISSUE TITLE
Provide easy access to earlier slides in presentation mode

### ISSUE THREAD

**Issue by bebraw** [FormidableLabs/spectacle#63]
Perhaps there could be some kind of a TOC thinger (dropdown?) to make it easier to jump around.

**Comment by kenwheeler** [comment]
I'm not sure what you mean?

**Comment by waywaaard** [comment]
I think he means a auto generated table of contents dropdown which allows to jump to other sections

**Comment by bebraw** [comment]
Yeah, that was the point. Thanks. :+1:

**Comment by kenwheeler** [comment]
And you want this in presentation mode?

**Comment by bebraw** [comment]
That's where it would be the most useful, yes.

The idea would be to provide means to jump within the presentation fast without forcing a refresh or such.

**Comment by kenwheeler** [comment]
So implementation wise, you would want a slide preview as the selectable tile in the dropdown right?

**Comment by bebraw** [comment]
Even an old fashioned dropdown with slide headers would be great. Of course how to get that meta to to the dropdown is another story...

MVP would be an input that would accept the slide number.

**Comment by kenwheeler** [comment]
Closing this in favor of the Overview mode overhaul
