### ISSUE TITLE
Feature: Autoplaying Toggle + Autoplay on Presentation Start prop/tag

### ISSUE THREAD

**Issue by MathEman-1** [FormidableLabs/spectacle#633]
### Description

I have 2 minor improvement suggestions for the autoplay feature:
1. Alt/Option + A Start autoplay should be a toggle (start/stop depending on the state - same as the other key combination toggles)

Currently only starts the presentation, no key combination to pause the presentation -> would be great if this is a toggle.

2. Add prop/tag to Deck to pause autoplaying on slideshow start

I would like to have the option to enable autoplay, without forcing the presentation to be autoplaying on start.

The use-case is that I want to have the option to enable autoplay after the presentation has started. I think this is only possible if autoplay is true, which forces the presentation to be autoplaying on each opening -> therefore this requires a manual click to pause every time the presentation is opened again.

Instead of autoplay being either on (and the presentation is automatically playing on start) or off (no way to start autoplay again), I would like to propose that autoplay can be turned on, with the option to pause autoplaying at the start, so it is still possible to toggle autoplaying later.

### Proposal

As these are fairly simple changes, I went ahead and did them on this branch:
https://github.com/MathEman-1/spectacle/tree/feature/autoplay-toggle-onStart

See also comparison:
https://github.com/FormidableLabs/spectacle/compare/master...MathEman-1:feature/autoplay-toggle-onStart?expand=1

I am not too experienced with the pull request processes here, so instruct on what to do with that.

### Links / References

I think this is related to this issue as well
https://github.com/FormidableLabs/spectacle/issues/583

**Comment by ebrillhart** [comment]
Hi @MathEman-1, go ahead and create a PR from your forked repo to this repo and I'll review and give feedback! Thanks for putting in some work on this!

**Comment by MathEman-1** [comment]
Thanks for continued support of this cool library :)

I created a PR and went through the checklist, seems like the travis check failed - but not sure what to do about that.
