### ISSUE TITLE
Passing invalid language name to `CodePane` breaks build (HMR)

### ISSUE THREAD

**Issue by bebraw** [FormidableLabs/spectacle#64]
If you are editing a presentation, looks like it can error out pretty badly if you pass an invalid language name to `CodePane`. I.e., just doing `lang="htmlsdfs"` is enough to break it. That yields

> Uncaught Error: Unknown language: "htmlsdfs"

It might be a better idea to deal with a possible error somehow and perhaps give a warning instead.

**Comment by kenwheeler** [comment]
I"m going to group this with #65
