### ISSUE TITLE
Export with Notes does not work

### ISSUE THREAD

**Issue by stevenmusumeche** [FormidableLabs/spectacle#640]
What version of Spectacle are you using? **spectacle@5.2.2**

What version of React are you using? **react@16.7.0**

What browser are you using? **Google Chrome**

What machine are you on? **MacBook Pro**

**Describe the Problem**

I have a presentation created with MDX that includes notes.  I want to export the slides with notes to print, so I went to http://localhost:3000/#/1?export&notes.  Nothing on the screen changes, and when bringing up the print dialog, the notes are not included.

* The code for the presentation can be found at https://github.com/stevenmusumeche/graphql-ignite
* The published presentation can be found at https://graphql-ignite.surge.sh
* The URL I used to attempt to export with notes can be found at https://graphql-ignite.surge.sh/#/1?export&notes

It's easier to show us than tell us what's going wrong with your code. Because of this, we ask that you do one of three things to help us reproduce the bug:

**Expected behavior:** 
I am able to print or export with notes.

**Actual behavior:** 
Presentation shows up as if I hadn't entered any query parameters.

**Comment by ebrillhart** [comment]
Hey @stevenmusumeche! This functionality was actually not released until 5.3.0, let me know if it's working for you on that version.

**Comment by ebrillhart** [comment]
Closing since this _should_ be working in current version.

**Comment by ebrillhart** [comment]
Hrmmm, good q, I'll look into it!

**Comment by kale-stew** [comment]
I did not test these changes with MDX so there's a really good chance this was an oversight on my part. I can dig in @ebrillhart I think I know where the problem lies

**Comment by kale-stew** [comment]
Closing as outdated b/c rewrite - @stevenmusumeche we'll make sure the new export w/ notes functionality addresses the MDX deck as well 🙂
