### ISSUE TITLE
Code highlighting doesn't use specified language

### ISSUE THREAD

**Issue by stevenmusumeche** [FormidableLabs/spectacle#641]
### Describe Your Environment

What version of Spectacle are you using? **spectacle@5.3.0**

What version of React are you using? **react@16.7.0**

What browser are you using? **Google Chrome**

What machine are you on? **MacBook Pro**

### Describe the Problem

I created a new MDX presentation by following the instructions in the README (cloning the Spectacle Boilerplate, etc).  I added a few CodeSlides with different languages specified for syntax highlighting, however, they all use JavaScript syntax highlighting.

**Expected behavior:** Code highlighting works for languages other than JavaScript

**Actual behavior:** Code highlighting does not work for languages other than JavaScript

### Additional Information

**Source**: https://github.com/stevenmusumeche/spectacle-highlight-bug
**Demo**: http://fat-noise.surge.sh

**Comment by ebrillhart** [comment]
closed in mdx-boilerplate!
