### ISSUE TITLE
Example repo: a CRA-based Spectacle + MDX boilerplate

### ISSUE THREAD

**Issue by markerikson** [FormidableLabs/spectacle#651]
I wanted to try out Spectacle's MDX support, but prefer to use CRA as my baseline project setup.  I looked at `spectacle-scripts`, but it doesn't seem to have MDX support added in.

I spent most of today trying to wrangle different pieces around, and eventually was able to put together a CRA repo that overrides some of the Webpack config to load MDX properly.  In the process, I also figured out how to handle breaking the slides into multiple MDX files, and proper syntax and settings for importing images and code block samples.

I put together a cleaned-up example repo that demonstrates the approaches I came up with:

https://github.com/markerikson/cra-spectacle-mdx-boilerplate

Twitter thoughts from today as reference:

https://twitter.com/acemarke/status/1093999521565011969
https://twitter.com/acemarke/status/1094013987669172224

Also, I'll note that one of the things that specifically caused me problems for a while is that `spectacle-boilerplate-mdx` depends on `"@mdx-js/mdx": "^0.15.0-2"`.  Apparently there's a version 0.16.x out, and it changes the compilation output drastically (it now writes a class instead of some kind of anonymous function component).  That was breaking the output of the Webpack MDX loader I'd copied from the boilerplate, because `export default class MDXComponent` was showing up in an invalid location in the transformed code.

I had to drop back to 0.15.x to get this to work.

**Comment by ebrillhart** [comment]
Thanks so much, @markerikson! I'm going to dig into this a bit more later this week

**Comment by kale-stew** [comment]
Closing as outdated - we discussed these feature improvements in the [open rewrite issue](https://github.com/FormidableLabs/spectacle/issues/716).
