### ISSUE TITLE
Full screen button does not change back

### ISSUE THREAD

**Issue by boardfish** [FormidableLabs/spectacle#654]
### Describe Your Environment

What version of Spectacle are you using? (can be found by running `npm list spectacle`) 5.4.0

What version of React are you using? (can be found by running `npm list react`) 16.5.2

What browser are you using? Chrome

What machine are you on? MacBook

### Describe the Problem

**Expected behavior:** [What you expect to happen] Full screen button toggles its appearance when clicked.

**Actual behavior:** [What actually happens] Full screen button does not toggle back after full screen is deactivated using the button. It resets on slide change, however.

Spotted by @ollie-nye when we were checking out a template I'm working on just now. I used spectacle-boilerplate, but I don't think the issue is specific to that.

**Comment by ebrillhart** [comment]
Thanks for the report, @boardfish! We'll look into this.

**Comment by ebrillhart** [comment]
Hey @boardfish could you please put together a small codepen or gif that demonstrates the issue you're running into? We haven't been able to reproduce on our end. Thanks!

**Comment by ashika01** [comment]
The issue seems to be happening in one particular use case refer #668 for info. Let us know, if you come across this issue in a different use case.
