### ISSUE TITLE
Slide templates

### ISSUE THREAD

**Issue by boardfish** [FormidableLabs/spectacle#655]
Hey all, I've picked up Spectacle in the last couple of days. I'm pretty new to React in general, but I got my head around higher order components to make slide templates. I've done something over [here](https://github.com/boardfish/spectacle-slide-templates) to show how it's done, and I'll be dropping it into a personal project very soon so that it can be seen in action. Perhaps it could be worth dropping something into the README to help with issues like #529?

**Comment by boardfish** [comment]
There's now a [demo repo](https://github.com/boardfish/spectacle-slide-templates-demo) too.

**Comment by ebrillhart** [comment]
Thank you!

**Comment by kale-stew** [comment]
This is awesome, thank you for sharing your approach with us! I will update the current README to reference your examples, but I should note that we are rewriting the library and expect to handle themes/templates more simply in the new API 🙂

**Comment by boardfish** [comment]
Thanks for recognizing it! I'd be very happy to update it myself to help with my Hacktoberfest quota, if you'd allow for it 😊

Looking forward to seeing how it changes soon, too.

**Comment by kale-stew** [comment]
@boardfish go ahead and open a PR, we would love to help you increase your Hacktoberfest numbers. 📈
