### ISSUE TITLE
Feature request: Up/Down keyboard hook for next/back slide

### ISSUE THREAD

**Issue by dkosasih** [FormidableLabs/spectacle#657]
### Description
I'd like to request for Up/Down keyboard hook to move the slide back and forth. I know what there are few clickers that only do up/down and it was really troublesome to use third party software to intercept key and map to left/right - that would affect the normal keyboard ket

### Proposal
I can do a PR if the request is approved :)

**Comment by ebrillhart** [comment]
Hey @dkosasih! PR would be totally welcome - would love for it to be flexible enough for a user to disable the feature, but this makes sense!

**Comment by kale-stew** [comment]
Filing this away as a feature request for the rewrite to consolidate our issues. Thanks for all of your work @dkosasih!
