### ISSUE TITLE
getAnimStep is missing in the documentation

### ISSUE THREAD

**Issue by mwanago** [FormidableLabs/spectacle#658]
The getAnimStep function is missing in the documentation. Adding it can save a lot of time for people looking for something like that.

**Comment by ebrillhart** [comment]
Thanks @mwanago! We'll fix this.

**Comment by ebrillhart** [comment]
Hey @mwanago, I've been looking into this a bit and would love if you could give some more context around this - I'm actually not sure this function is included anymore

**Comment by ebrillhart** [comment]
closing, but feel free to re-open if you can give me a bit more context to help me fix!

**Comment by mwanago** [comment]
@ebrillhart https://github.com/FormidableLabs/spectacle/blob/master/src/components/slide.js#L82
There is a prop called "getAnimStep" that you can pass to the Slide component and it acts as a callback to inform of any changes to the animation steps. It was very useful to me, but I don't see it anywhere in the documentation.
