### ISSUE TITLE
Has bulletStyle List props been removed ? 

### ISSUE THREAD

**Issue by guillaumepn** [FormidableLabs/spectacle#659]
### Question

Has the `bulletStyle` List and ListItem prop been removed from spectacle ?  
It is referenced in this repo's README, but not on spectacle's website docs

### Background Info/Attempts

I tried the following and the bullet points are not changing : 

```javascript
<List bulletStyle="star">
    <ListItem>Item 1</ListItem>
    <ListItem>Item 2</ListItem>
    <ListItem>Item 3</ListItem>
    <ListItem>Item 4</ListItem>
</List>
```

**Comment by ebrillhart** [comment]
Hi @guillaumepn, the website docs are actually quite out of date, so the Readme should have the latest documentation. We'll look into why this isn't working.

**Comment by gkn06** [comment]
@ebrillhart  Even am facing this issue. 
How to use bulletstyle in List item. Am using typescript. And in Index.d.ts I can't find bulletstyle prop.

**Comment by keschaefer** [comment]
Hello @guillaumepn! I'm looking into the issue you were having with the bulletStyle prop. I've copied your code directly into my project and its rendering as expected with the `star` icon. 

Are you receiving any errors when you spin this up? If not, what are you seeing, just default bullets or none at all? Any additional info you can provide would be much appreciated.

**Comment by ashika01** [comment]
I faced similar issue , my bulletStyle was not rendering. I just figured it was not working in version 5.4.0 Make sure you are in the latest version. If you are using spectacle-boilerplate like me, then you might wanna update to latest to make it work right. I am creating a PR with update in boilerplate 👍  Can you update us after you get on recent version and check if things are good or if you are still facing the issue? If its not an issue please close this issue :)

**Comment by keschaefer** [comment]
@ashika01 thanks for this insight, I checked my version and I'm working in what I think is the latest, 5.5.0 which may be why my bulletStyle prop IS working, but for others it isn't. Thanks for updating that PR for the boilerplate, hopefully that will solve this issue. For others, try updating the most recent version of Spectacle to fix your bullets!
