### ISSUE TITLE
While changing slides fast while developing (npm start), getting warnings

### ISSUE THREAD

**Issue by bebraw** [FormidableLabs/spectacle#66]
Warning below:

> Warning: owner-based and parent-based contexts differ (values: `5` vs `3`) for key (slide) while mounting Appear (see: http://fb.me/react-context-by-parent)

I suspect that might have something to do with animation. It spams a lot of these if you hit left/right while in development mode.

**Comment by kenwheeler** [comment]
Its caused by the `TransitionGroup` not being able to keep up. Would you prefer to have this flagged as `wontfix` and you can switch fast, or have it flagged as `bug` and I can add a conditional so that the next slide won't enter if you're already animating?

**Comment by bebraw** [comment]
I'm not sure what would be the right way to fix this. Is it possible to cancel `TransitionGroup` if you detect another one is getting triggered? If so, perhaps we can meet somewhere in the middle.

**Comment by knowbody** [comment]
also resolved @kenwheeler

**Comment by codepunkt** [comment]
There's quite a few issues that have been closed without further information.

It might just be that i'm new to spectacle and this repo and missed something.
Isn't this issue still a thing? I'd love animations to be cancelled when transitioning further mid-animation.
