### ISSUE TITLE
No-op when slideshow is programmatically unmounted

### ISSUE THREAD

**Issue by glassblowerscat** [FormidableLabs/spectacle#661]
### Describe Your Environment

What version of Spectacle are you using? 5.4.0

What version of React are you using? 16.8.3

What browser are you using? Chrome 72

What machine are you on? MacBook Pro 6,1

### Describe the Problem

I am using Spectacle for a simple autoplaying slideshow that should disappear as soon as a user clicks or taps the browser window, to be replaced with a survey the user can take. The slideshow should reappear after *n* seconds of user inactivity.

To manage this user behavior I am using react-idle-timer and conditional rendering based on state. When the user is idle, a `<SlideshowContainer />` returns a `<Slideshow />`, which is the component containing the Spectacle Deck and Slides. When the user becomes active, the `<SlideshowContainer />` returns `null`. 

In practice, when the user becomes active, the slideshow does disappear and the survey appears, but I get the following output to the console: 

`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.`

    in Manager (created by Connect(Manager))

    in Connect(Manager) (created by Deck)

    in Context (created by Controller)

    in Controller (created by Deck)

    in Provider (created by Deck)

    in Deck (at Slideshow.js:24)

    in Slideshow (at SlideshowContainer.js:9)

Then, after the user becomes idle again, the slideshow reappears but is obviously broken, with slide transitions happening simultaneously or in the wrong timing... or something. I can't quite identify what the exact behavior is.

I was able to achieve a basic version of my desired functionality by using another slideshow library, but I want to be able to use Spectacle because it has other features I need.

I have created a very basic version of my project that reproduces the issue, which can be accessed at this repo:

https://github.com/glassblowerscat/spectacle-bug-demo

Thanks!

**Comment by jpbourgeon** [comment]
I have the exact same problem. But my deck is still small and this is not blocking me, so far.

AFAIK this usually happens when you try to setState on unmounted Components

This link may be useful ? <https://www.robinwieruch.de/react-warning-cant-call-setstate-on-an-unmounted-component/>

```
index.js:1446 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
```
<details>
 <summary>Click to show the full warning message</summary>

```
    in SlideWrapper (created by TransitionGroup)
    in div (created by TransitionGroup)
    in TransitionGroup (created by Styled(TransitionGroup))
    in Styled(TransitionGroup) (created by Manager)
    in div (created by Styled(div))
    in Styled(div) (created by Manager)
    in Manager (created by Connect(Manager))
    in Connect(Manager) (created by Deck)
    in Context (created by Controller)
    in Controller (created by Deck)
    in Provider (created by Deck)
    in Deck (at 2019-INGE-01/index.js:48)
    in Presentation (created by InnerLoadable)
    in InnerLoadable (created by Context.Consumer)
    in Unknown (created by ForwardRef)
    in ForwardRef (at Presentation/index.js:19)
    in Presentation (created by WithStyles(Presentation))
    in WithStyles(Presentation) (created by InnerLoadable)
    in InnerLoadable (created by Context.Consumer)
    in Unknown (created by ForwardRef)
    in ForwardRef (at Loadable/index.js:45)
function.console.(anonymous function) @ index.js:1446
warningWithoutStack @ react-dom.development.js:520
warnAboutUpdateOnUnmounted @ react-dom.development.js:19357
scheduleWork @ react-dom.development.js:20844
enqueueSetState @ react-dom.development.js:11571
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:336
componentWillLeave @ slide-wrapper.js:175
TransitionGroup._this.performLeave @ TransitionGroup.js:145
TransitionGroup._this._handleDoneAppearing @ TransitionGroup.js:113
(anonymous) @ slide-wrapper.js:191
setTimeout (async)
routerCallback @ slide-wrapper.js:190
componentWillAppear @ slide-wrapper.js:170
TransitionGroup._this.performAppear @ TransitionGroup.js:97
componentDidMount @ TransitionGroup.js:195
commitLifeCycles @ react-dom.development.js:18071
commitAllLifeCycles @ react-dom.development.js:19630
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
commitRoot @ react-dom.development.js:19854
(anonymous) @ react-dom.development.js:21402
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:21401
performWorkOnRoot @ react-dom.development.js:21324
performWork @ react-dom.development.js:21229
performSyncWork @ react-dom.development.js:21203
requestWork @ react-dom.development.js:21058
scheduleWork @ react-dom.development.js:20871
enqueueSetState @ react-dom.development.js:11571
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:336
safeSetState @ loadable.es.js:173
(anonymous) @ loadable.es.js:226
Promise.then (async)
loadAsync @ loadable.es.js:217
componentDidMount @ loadable.es.js:161
commitLifeCycles @ react-dom.development.js:18071
commitAllLifeCycles @ react-dom.development.js:19630
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
commitRoot @ react-dom.development.js:19854
(anonymous) @ react-dom.development.js:21402
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:21401
performWorkOnRoot @ react-dom.development.js:21324
performWork @ react-dom.development.js:21229
performSyncWork @ react-dom.development.js:21203
requestWork @ react-dom.development.js:21058
scheduleWork @ react-dom.development.js:20871
enqueueSetState @ react-dom.development.js:11571
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:336
safeSetState @ loadable.es.js:173
(anonymous) @ loadable.es.js:226
Promise.then (async)
loadAsync @ loadable.es.js:217
componentDidMount @ loadable.es.js:161
commitLifeCycles @ react-dom.development.js:18071
commitAllLifeCycles @ react-dom.development.js:19630
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
commitRoot @ react-dom.development.js:19854
(anonymous) @ react-dom.development.js:21402
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:21401
performWorkOnRoot @ react-dom.development.js:21324
performWork @ react-dom.development.js:21229
performSyncWork @ react-dom.development.js:21203
requestWork @ react-dom.development.js:21058
scheduleWork @ react-dom.development.js:20871
enqueueSetState @ react-dom.development.js:11571
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:336
(anonymous) @ index.js:145
requestAnimationFrame (async)
(anonymous) @ index.js:143
Promise.then (async)
(anonymous) @ index.js:141
popstateListener @ history.js:47
replaceHashPath @ createHashHistory.js:77
(anonymous) @ createHashHistory.js:225
confirmTransitionTo @ createTransitionManager.js:45
replace @ createHashHistory.js:214
_prevSlide @ manager.js:555
_handleEvent @ manager.js:394
_handleKeyPress @ manager.js:430
```
</details>

**Comment by glassblowerscat** [comment]
I strongly suspect that this is indeed the problem. Unfortunately, there is no way that I know of to correct this behavior in Spectacle. If you're thinking of rolling your own slideshow at some point to solve this problem, I'm using [react-timeout](https://www.npmjs.com/package/react-timeout) to implement a safe `setInterval()` that prevents this behavior.

**Comment by narinluangrath** [comment]
I verified that the bug exists. To reproduce:

- Clone https://github.com/glassblowerscat/spectacle-bug-demo
- `yarn start`
- Click `Start Demo`
- After the slideshow starts, click anywhere. 
- At the rating screen, wait until the slideshow starts again (10 seconds)
- The slideshow toggles between "Slide 2" and "Slide 3"
