### ISSUE TITLE
Font handling

### ISSUE THREAD

**Issue by angelo-v** [FormidableLabs/spectacle#663]
### Question

What exactly is the difference between `primary` and `secondary` fonts in `createTheme`? How do I specifiy a fallback font, if a specified Font is not installed on the target system?

### Background Info/Attempts

First I thought `secondary` is meant to specifiy a fallback, but It seams to have a different purpose. I also tried to specify multiple fonts, like in CSS, comma-separated and as JS array, but neither of it worked.

**Comment by ebrillhart** [comment]
Hi @angelo-v - to answer your question about the usage of `primary` and `secondary`, that would be more for when you maybe want one font to reach for for titles, and another font to use for body text.

For fallback fonts, that's actually a great question and it seems like we may need to add better handling and documentation for that functionality. Thanks for bringing this up!

**Comment by angelo-v** [comment]
> Hi @angelo-v - to answer your question about the usage of `primary` and `secondary`, that would be more for when you maybe want one font to reach for for titles, and another font to use for body text.

But all my texts use the primary font only. How do I make use of the secondary font?

>  I think the assumption has generally been that folks are creating a presentation on the computer it'll be displayed from, but that's obviously not always the case.

Yes, HTML/JS slides are great to host on the web for everybody even after the actual talk. So it would be good to have more control over the fonts.

**Comment by ebrillhart** [comment]
Hey @angelo-v, you can use your secondary font by adding `textFont='secondary'` to the component you'd like to use the secondary font. See the base prop docs https://github.com/FormidableLabs/spectacle#base-props

When you want to use a Google font, the recommended setup in `createTheme` can be found here: https://github.com/FormidableLabs/spectacle#createthemecolors-fonts

**Comment by ebrillhart** [comment]
I'm going to close this particular issue now, but there is a follow up issue at #665 for the specific case of being able to add fallback fonts. It should be a pretty straightforward issue if you'd like to push the PR yourself! Otherwise, it'll get handled in our backlog
