### ISSUE TITLE
Improved Handling and Documentation for Fallback Fonts in Themes

### ISSUE THREAD

**Issue by ebrillhart** [FormidableLabs/spectacle#665]
### Description

Currently, there is no clear way to add fallback fonts when creating a theme to handle a font not being available on the machine the presentation is being run on.

### Proposal

Perhaps allow users to add an array of fonts when specifying fonts in a theme

**Comment by emilykoh** [comment]
Took a look at the issue, the ideal way to trigger the fallback based on some sort of check on whether or not the component rendered properly with the desired font, but I couldn't find any good ways to perform the check in `screen.js`. 

Some attempted solutions:
* check if the component was rendered with the right font --> problem is that the component would be rendered with an undesired base default font (based on the browser) before the check can be triggered and then re-rendered with the desired backup font
* check if the font is a supported font based on browser --> doesn't seem to be a good built-in way to do this with javascript

**Comment by kale-stew** [comment]
Closing as outdated - we will document this better in the rewritten codebase. 🙂 See our pinned issue for more info.
