### ISSUE TITLE
Pacman runs out of space with lots of slides

### ISSUE THREAD

**Issue by bebraw** [FormidableLabs/spectacle#67]
I'm not sure what's a neat way to solve this. Anyway, it would be cool to perhaps start from the beginning again or something.

**Comment by kenwheeler** [comment]
Maybe a dot based slide count indicator isn't a good fit for that use case?

**Comment by bebraw** [comment]
That could be true. You can see the presentation [here](https://survivejs.github.io/frontend-in-2015). Pacman sort of works but it's true there are likely nicer ways.

Actually it might be neat to have it run around the presentation.

**Comment by kenwheeler** [comment]
Thats a great looking preso. Also, I see what you mean. My first thought would be to adjust the css to make the pac's smaller. Then again, you could just use the progress bar across the bottom too. I've run into this problem with carousels with dot indicators, and I'm not sure I have a great solution. You can always drop down to two rows, but that looks a little iffy.

**Comment by bebraw** [comment]
Yeah, good ideas, thanks. I'll give those a go. :+1:

Feel free to close unless you feel like changing the current implementation somehow.

**Comment by kenwheeler** [comment]
I suppose it makes sense to make it go to two rows if need be, rather than just overflowing, which renders it unusable.

**Comment by bebraw** [comment]
One alternative way would be to rethink the problem. If we had means to mark presentation sections (#57), then you could do a Pacman per section. Maybe there would be a "master" Pacman then that would move across the sections. Example:

```
*     *     *     * (sections)
* * * * * * * * * (current section)
```

**Comment by MarkRedeman** [comment]
If we could mark presentations sections then It would be awesome if at each special mark (for example at the end of a section) instead of a white dot we would have one of the ghosts.
Not only would it be fun to watch pacman eat the ghosts, I think it would also be a nice indicator for your audience when to expect a new topic.

**Comment by bebraw** [comment]
@MarkRedeman That would be awesome.

**Comment by pawel2105** [comment]
Perhaps some navigation logic that drops Mr Pac for a progress bar when the slide count crosses a threshold? A percent-based progress indicator fits well for this type of use case.

**Comment by kenwheeler** [comment]
Closing for now, fixing progress indicators in the grouping/sectioning feature
