### ISSUE TITLE
Webpack 4 created 2 main.js files.

### ISSUE THREAD

**Issue by nazaruk1228** [FormidableLabs/spectacle#670]
**My plugins: 
Webpack: 4.29.6
WebPack-Cli:3.3.0
Node: 11.13.0
Npm: 6.7.0**
My packaje.json:
`{
  "name": "test_html",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/javurekv/test_html.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/javurekv/test_html/issues"
  },
  "homepage": "https://github.com/javurekv/test_html#readme",
  "dependencies": {
    "webpack": "^4.29.6",
    "webpack-cli": "^3.3.0"
  },
  "scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production"
  }
}
`
my webpack.config.js:
`var path = require('path');

module.exports = {
  mode: 'development',
  entry: './src/app.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'main.js'
  }
};`
I have file app.js,they get all scss and css file.app.js has entry.
main.js output.
When i compile my project.i get 2 main.js files
main.js 1.main.js
And webpack say me what main.js it`s entry.HOW?
`Hash: a2ede639cf5b12872bbc
Version: webpack 4.29.6
Time: 958ms
Built at: 08.04.2019 21:05:41
    Asset       Size  Chunks             Chunk Names
1.main.js  103 bytes       1  [emitted]  
  main.js   1.97 KiB       0  [emitted]  main
Entrypoint main = main.js
[0] ./src/app.js 21 bytes {0} [built]
[1] ./src/js/js.js 27 bytes {1} [built]
`
How i can fix it?

**Comment by ebrillhart** [comment]
Hi @nazaruk1228 it can be hard for us to debug specific webpack setups. If you could give us a bit more detail, or maybe a link to a repository where you're encountering this issue, it might help us out!

**Comment by ebrillhart** [comment]
closing, please feel free to reopen if you can give more details!
