### ISSUE TITLE
Link to demo/example from README

### ISSUE THREAD

**Issue by appsforartists** [FormidableLabs/spectacle#671]
Is there a sample presentation hosted somewhere?  Can there be?

As a prospective user, I'd find it really helpful if there was a link to a demo at the top of the README, so I could play with it and get a feel for whether it will meet my needs without having to read through the docs or download anything.  It would be especially helpful if the example demonstrated the benefits touted in the docs (interactivity, code snippets, auto-sized text, image dimming, etc.).

**Comment by ryan-roemer** [comment]
Not directly answering the demo example code question, but just as a helpful tip -- the "one page" version of Spectacle (which is close, but not quite the same content-wise, functionality-wise) is always live available from our git source which you can view as a live web page at: https://raw.githack.com/FormidableLabs/spectacle/master/one-page.html or in raw source form at: https://github.com/FormidableLabs/spectacle/blob/master/one-page.html

**Comment by ebrillhart** [comment]
Hey @appsforartists, this is a great suggestion. We'll add it to our list.
