### ISSUE TITLE
Does this repo need a maintainer?

### ISSUE THREAD

**Issue by dmitrif** [FormidableLabs/spectacle#672]
### Question

Hi! What is the current maintainer roster? I would like to volunteer to fix some of the issues.

**Comment by boygirl** [comment]
This repo is maintained by @ebrillhart and @kale-stew, but help on issues is always welcome.

**Comment by ebrillhart** [comment]
@dmitrif we always welcome PRs! Please read the Contributing.md file in the docs, and assign yourself to any issues that you pick up so that others know they're in progress. Thanks!
