### ISSUE TITLE
Slide JSX Component in MDX

### ISSUE THREAD

**Issue by elbaro** [FormidableLabs/spectacle#676]
### Description
A Slide component with arguments cannot be used in MDX.
I am using spectacle-boilerplate-mdx.

```
---
export default CodeSlide

\```javascript
class SuperCoolComponent extends React.Component {
  render() {
    return (
      <p>code slide works in markdown too whaaaaat</p>
    );
  }
}
\```
---
export default CodeSlide

<CodeSlide
    transition={[]}
    lang="cpp"
    code={require("raw-loader!../assets/code.example")}
    ranges={[
        { loc: [0, 10], title: "Walking through some code" },
        { loc: [0, 1], title: "The Beginning" },
        { loc: [1, 2] },
        { loc: [1, 2], note: "Heres a note!" },
        { loc: [2, 3] },
        { loc: [4, 7]},
        { loc: [8, 10] },
    ]}/>

```

The second slide uses spectacle-code-slide with arguments but `index.js` ignores this.

Customizing index.js has a limitation. My markdown should be split like this:

```
<Deck transition={[creeperTransition]} transitionDuration={500} theme={theme}>
      {slides1.map((S, i) => {
        let transition = transitions[i] || null;
        return <S transition={transition} key={`slide-${i}`} />;
      })}
      <CodeSlide ../>
      {slides2.map((S, i) => {
        let transition = transitions[i] || null;
        return <S transition={transition} key={`slide-${i}`} />;
      })}
</Deck>
```

I need $n+1$ markdown files for $n$ CodeSlide.

### Proposal

If there is one jsx component in a slide (between `---`) and its type is Slide, then use it as the top component.

**Comment by ebrillhart** [comment]
Thanks @elbaro!

**Comment by tlenclos** [comment]
We definitely need a way to customize slides with mdx.

How can we help going forward with the MDX implementation ?

**Comment by kale-stew** [comment]
@tlenclos are you asking to customize slides with mdx using the CodeSlide extension referenced above?

If so, and given this issue is related to an external package that Formidable doesn't directly maintain, I would encourage you to check out our rewrite effort. We are prioritizing MDX and code slide walkthroughs, this may no longer be an issue [there](https://github.com/FormidableLabs/spectacle/issues/716). We are expecting to release v6 in the coming weeks.

**Comment by kale-stew** [comment]
Closing as I haven't heard back from the OP. Please feel free to reopen if you feel v6 doesn't solve this for you.
