### ISSUE TITLE
Navigation Oddity

### ISSUE THREAD

**Issue by dbendy** [FormidableLabs/spectacle#679]
### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://www.github.com/FormidableLabs/spectacle/issues) to make sure I'm not opening a duplicate issue
- [x] This issue not specific to `spectacle-boilerplate` (those issues should be opened [here](https://github.com/FormidableLabs/spectacle-boilerplate/issues/new)).
- [x] I have read through the [docs](https://formidable.com/open-source/spectacle/docs/) before asking a question
- [x] I am using the latest version of Spectacle

### Describe Your Environment

What version of Spectacle are you using? spectacle@5.4.0

What version of React are you using? react@16.8.5

What browser are you using? Chrome 74.0.3729.131

What machine are you on? Mac, MacOS Sierra 10.12.6

### Describe the Problem

I have a table of contents in my presentation that uses the `<GoToAction>` component to link to different sections within my presentation.  I also placed the `<GoToAction>` on each slide in order to link back to this table of contents.

This setup encourages people to skip around through the deck using the table of contents.

Unfortunately, the logic behind the next button doesn't quite support this.  In stead of always advancing to the next slide in the deck, the next button advances to the next slide that you have not viewed already.

I have created this repo that can be used to reproduce the issue: https://github.com/dbendy/spectacle-bug

After cloning the repo and starting it up, you should be able to go through the following steps in order to reproduce the issue:

1. open first slide and advance to next slide, the table of contents
1. click on "yellow slides" and then use the arrow button to advance through all the yellow slides
1. use the link to navigate back to the table of contents
1. click on "yellow slides" again from the table of content
1. click next arrow.  In stead of seeing the next yellow slide, you will see the next slide in the deck that you haven't seen already.

**Expected behavior:** Under all circumstances, the next button should always advance to the next slide in the presentation.

**Actual behavior:** The next button moves you to the next slide that you haven't seen.

I see the line of code that causes this behavior: https://github.com/FormidableLabs/spectacle/blob/master/src/components/manager.js#L496

I imagine this behavior was chosen for a good reason so I'd love to know why.  If there is no good reason, I'm happy to open a PR to fix it.

Thanks!

**Comment by kale-stew** [comment]
I cannot speak to _why_ this happened in the first place, but I would welcome your PR if you want to give it a go @dbendy 🙂

**Comment by dbendy** [comment]
Ok, I'll open a PR in the next few days.  Thanks for getting back to me @kale-stew

**Comment by AlfredoGJ** [comment]
Hello people, I would like to help and this issue seems god for me to start. Are you @dbendy still working on this one? if no please tell me so I can give it a try.

**Comment by dbendy** [comment]
@AlfredoGJ: I hope to open a PR for this by the end of the weekend.  Sorry that I didn’t get to it until now.  Thanks for offering to help!

**Comment by dbendy** [comment]
Here is my PR @kale-stew and @AlfredoGJ: https://github.com/FormidableLabs/spectacle/pull/780.

**Comment by kale-stew** [comment]
Closing in favor of the rewrite, but I would welcome your input if the problem persists in v6. Thank you for opening this issue, @dbendy!
