### ISSUE TITLE
Can the transition at the start of the presentation be prevented?

### ISSUE THREAD

**Issue by TrevorBurnham** [FormidableLabs/spectacle#680]
### Question

When I open my slide deck, the first slide transitions in by default. For example, if the `Deck` has `transition={['slide']}`, the first slide will slide in when the page opens. How do I prevent this without other side effects?

### Background Info/Attempts

I tried setting `transitionIn={['']}` on the first `Slide` (`transitionIn={[]}`) appears to be a no-op), but this had the surprising side effect of preventing the "out" transition when going from the first slide to the second. (That is, the second slide will slide in, but the first slide does not slide out.) It also has the expected side effect of preventing any visible transition at all when going back from the second slide to the first.

**Comment by kale-stew** [comment]
Good question, @TrevorBurnham. It looks like currently, no, the designated transition will apply to every slide. I'll dig into this to see how easily we can flag that initial transition not to happen.

**Comment by kale-stew** [comment]
Re; #685

**Comment by kale-stew** [comment]
Closed by #690

@TrevorBurnham, can you let me know if you're still having this issue with the latest update?
