### ISSUE TITLE
IFrame Squished

### ISSUE THREAD

**Issue by SamFrampton01** [FormidableLabs/spectacle#683]
Hi, 

First of all I'd like to say thank you to Formidable team for creating Spectacle. 

One issue I am having is embedding iFrame into my project and for the height to be squished creating an overflow: scroll effect when there is ample room to present the Iframe in it's full glory. It's really odd because I can't understand why the slide is squishing a Heading and Iframe into such a small space on the page. 

Can you recommend the most efficient way to embed iFrames? 

Am I doing something stupid? (Most likely...) 

Right now I'm using import Iframe from 'react' library in a separate component and then linking that component into a slide on Index.js.

**Comment by kale-stew** [comment]
Rel #604 - we handle iFrames weird, apparently. This definitely needs to be fixed

**Comment by SamFrampton01** [comment]
Hi,

I managed to fix problem, iframe was getting squished with flex box so had to add custom css styling set it’s position to absolute to make it responsive and utilise full space of page.

**Comment by kale-stew** [comment]
Closing as outdated and resolved - there is a functional workaround for the existing version of Spectacle. 🙂
