### ISSUE TITLE
On Node 12 and the spectacle boilerplate i get thoses errors

### ISSUE THREAD

**Issue by Ebeldev** [FormidableLabs/spectacle#693]
### Describe Your Environment

What version of Spectacle are you using? (can be found by running `npm list spectacle`)
5.5.0
What version of React are you using? (can be found by running `npm list react`)
16.8.6
What browser are you using?
Chrome and Firefox
What machine are you on?
Mac with nodejs 12
### Describe the Problem

It's easier to show us than tell us what's going wrong with your code. Because of this, we ask that you do one of three things to help us reproduce the bug:

I was trying your tutoriel. I followed the guide. After npm installing all the depencies, I got issues with depencies. 

There is a high level for puppeter that comes from spectacle. In the package of spectacle it's at 0.0.x and Puppeter should be at least 1.13.0

since this was there I was getting 
https://www.npmjs.com/advisories/824

**Comment by kale-stew** [comment]
Hi @Ebeldev - I think your issue might be in the implementation of puppeteer and not spectacle. we aren't using puppeteer within spectacle, so the dependency conflict is external to this library.

I'll be happy to re-open this issue if you can point to the line in our docs that you are getting stuck on. I don't believe we mention puppeteer anywhere in our [tutorial](https://github.com/FormidableLabs/spectacle/blob/master/docs/tutorial.md), but I could be wrong. 🙂
