### ISSUE TITLE
React Router - HashHistory missing

### ISSUE THREAD

**Issue by AlanFoster** [FormidableLabs/spectacle#70]
Running on 0.05 release - `npm install` gives the following error -

```
ERROR in ./index.jsx
Module not found: Error: Cannot resolve module 'react-router/lib/HashHistory' in /Users/foo/slides
 @ ./index.jsx 27:33-72
```

**Comment by AlanFoster** [comment]
This is failing because the dependency is on `^1.0.0-beta2` which allows `1.0.0-beta4` to be installed, which does not contain `HashHistory`. 

Thoughts on updating the node dependencies to use beta2/3 explicitly for now, and aligning to the newest API as part of a separate unit of work? Potentially tagged releases of `spectacle` should also include a npm shrinkwrap file to aid with this type of issue in the future too.

**Comment by kenwheeler** [comment]
I think I'll test with latest and then hard pin to it. Thanks for finding this! I'll have an update out soon.

**Comment by ryoia** [comment]
Yup, I tested with just `1.0.0-beta2` without the `^`, worked just fine.

**Comment by luisrudge** [comment]
I had this problem before too.

Fix:

* Update to react-router beta4
* `npm i -S history`
* `import createHistory from 'history/lib/createHashHistory';`
* `ReactDOM.render(<Router history={createHistory()} routes={routes}/>, document.getElementById('app'));`

**Comment by kenwheeler** [comment]
thanks @luisrudge !

**Comment by kenwheeler** [comment]
Pinned on master. I'll update to the new API when it 1.0's
