### ISSUE TITLE
Out of date types in index.d.ts

### ISSUE THREAD

**Issue by mhartington** [FormidableLabs/spectacle#700]
### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://www.github.com/FormidableLabs/spectacle/issues) to make sure I'm not opening a duplicate issue
- [x] This issue not specific to `spectacle-boilerplate` (those issues should be opened [here](https://github.com/FormidableLabs/spectacle-boilerplate/issues/new)).
- [x] I have read through the [docs](https://formidable.com/open-source/spectacle/docs/) before asking a question
- [x] I am using the latest version of Spectacle

### Describe Your Environment

What version of Spectacle are you using? (can be found by running `npm list spectacle`)
5.5.0

What version of React are you using? (can be found by running `npm list react`)
16.8.6

What browser are you using?
Chrome

What machine are you on?
macOS

### Describe the Problem
The current type definitions that ship with spectacle are not accurate or are incomplete. For instance, given a `Deck` component with the following props set

```
      <Deck
        transition={['fade']}
        transitionDuration={250}
        theme={theme}
        contentWidth={1200}
        controls={false}
        progress="bar"
      >..</Deck>`
```

Will error during compilation with: 

```
Type '{ children: Element[]; transition: "fade"[]; transitionDuration: number; theme: Theme; contentWidth: number; controls: false; progress: "bar"; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Deck> & Readonly<DeckProps> & Readonly<{ children?: ReactNode; }>'.
  Property 'contentWidth' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Deck> & Readonly<DeckProps> & Readonly<{ children?: ReactNode; }>'.  TS2322

    83 |   render() {
    84 |     return (
  > 85 |       <Deck
       |        ^
    86 |         transition={['fade']}
    87 |         transitionDuration={250}
    88 |         theme={theme}
```

In a regular JS project, this would build.

Not sure if this is intended as "contentWidth" is documented in the [readme](https://github.com/FormidableLabs/spectacle#deck)

https://codesandbox.io/s/redux-form-typescript-example-pi1qh

**Expected behavior:** [What you expect to happen]
All props would be part of the type defs.

**Actual behavior:** [What actually happens]
Type defs provide a subset of available props

**Comment by kale-stew** [comment]
Fixed with #699, I will be releasing a version with the updated types this afternoon.
