### ISSUE TITLE
How to implement a pre-existing react hash router with Deck

### ISSUE THREAD

**Issue by ArijeetWebonise** [FormidableLabs/spectacle#702]
### Question

How to implement a pre-existing react hash router with Deck

### Background Info/Attempts

I tried creating history as:
`
import { createHashHistory } from 'history'

export default createHashHistory({});
`
Later I set the history prop in Deck, but I am getting redirected to path '/#/1' from my original path '/#/slider'. Can I configure it to '/#/slider/:id'

>

**Comment by kale-stew** [comment]
Thank you for opening this issue, @ArijeetWebonise! We appreciate the question, and I'm sorry for not getting back to you with a direct answer before today. We have rewritten the library (due for release tomorrow) and I would welcome you to reopen this issue if the question persists against the updated library.

All of the above being said, our approach to routing is finicky and we heavily depend on query params to carry state between multiple browser instances of the same presentation. We would really appreciate any feedback to this approach, or of your experience implementing a hash router against your own Deck.
