### ISSUE TITLE
Last frame of transition is not rendered

### ISSUE THREAD

**Issue by fbarbat** [FormidableLabs/spectacle#707]
### Describe Your Environment

What version of Spectacle are you using? (can be found by running `npm list spectacle`)
5.7.0

What version of React are you using? (can be found by running `npm list react`)
16.9.0

What browser are you using?
Chrome/Firefox

What machine are you on?
Ubuntu 18.04.3 LTS

### Describe the Problem

Spectacle transitions skip the last render causing incomplete effects and partially loaded slides. 

To reproduce it just inspect the DOM after the slide transitions and confirm that the final CSS _transform_ values such as _scale_ or _translate3d_ do not reach final values (i.e. scale=1 or translate3d=0).  

See https://codesandbox.io/s/simple-spectacle-example-e96d2 as an example. In this specific case, scale does not reach 1 but a number close to it such as 0.993772. In this case maybe it is not noticeable at a first look, but if the slide has many more components or the resources are stressed, it could stop at lower values causing a very noticeable glitch in the layout.

Forcing the render on the terminating case should fix the issue.

Please see the pull request here https://github.com/FormidableLabs/victory/pull/1368

Once victory-core is fixed and released, Spectacle dependency on victory should be updated.

**Expected behavior:**
Last frame of animation should be rendered. scaled should end at 1.

**Actual behavior:** 
Last frame of animation is not rendered. scale ends being less than 1.

### Additional Information

By the way, I am fixing this bug since I am implementing a cover letter using Spectacle to find a new job. Do you want to hire me? :D Please see [https://fernandobarbat.com](https://fernandobarbat.com) Thanks!

**Comment by michaelperrin** [comment]
I am having the same issue and is a real problem, especially with the slide effect where you can see parts of the previous slide (which shows if the background is not the same).

**Comment by fbarbat** [comment]
@michaelmerrill As a workaround I used this patch https://github.com/fbarbat/cover-letter/tree/master/patches and https://www.npmjs.com/package/patch-package . Maybe that is useful for you as well in the meantime.

**Comment by kale-stew** [comment]
We updated `victory-core` in [v5.7.1](https://github.com/FormidableLabs/spectacle/releases/tag/v5.7.1), so this should be fixed for you @fbarbat. Thank you for your contributions!
