### ISSUE TITLE
Autoplay Appear/Anim

### ISSUE THREAD

**Issue by shortwavedave** [FormidableLabs/spectacle#710]
### Question

How can you automate Appear and Anim on a slide, so that you don't need to click to progress the slide? I don't want to enable autoplay on the entire deck.

**Comment by kale-stew** [comment]
Currently, I do not think there is a way to automate only Appear and Anim elements without applying autoplay to the entire deck. You could try to create a second SlideSet of those animated elements, apply the autoplay to just that "deck", and render it within another presentation?

**Comment by kale-stew** [comment]
Closing as outdated for now - please see our pinned issue for all things rewrite-related.
