### ISSUE TITLE
Support React Hooks

### ISSUE THREAD

**Issue by ganeshchand** [FormidableLabs/spectacle#720]
Spectacle seems to be using React 16.5.2. Hooks were introduced in React 16.8. Is it possible to use a higher React version than the default one that come with the spectacle starter project?
Hooks will simply creating stateful and interactive presentations.

**Comment by kale-stew** [comment]
@ganeshchand updating to Spectacle [v5.7.1](https://github.com/FormidableLabs/spectacle/releases/tag/v5.7.1) should fix this issue for you. 🙂
