### ISSUE TITLE
Consider replacing highlight.js with Prism

### ISSUE THREAD

**Issue by bebraw** [FormidableLabs/spectacle#73]
[Prism](http://prismjs.com/) works far better with JSX. I made a [tiny helper package](https://www.npmjs.com/package/prism-languages) to help with language definitions. It has been designed to be used on backend, though, and as a result it's a bit chunky. I can improve the situation if needed.

I suppose you'll push all of this to spectacle plugins anyway. Better leave it to the community to do these things. :+1:

**Comment by kenwheeler** [comment]
We were actually talking about making the highlighter a bit more interchangeable. Let me give it a try and see what I can come up with.

**Comment by AlanFoster** [comment]
:+1: to this idea

**Comment by bebraw** [comment]
FYI, I made [a tiny prism loader](https://github.com/survivejs/react-demos/blob/master/loaders/prism.js). I haven't extracted it to a project of its own as I know [there's another one](https://github.com/valor-software/prismjs-loader) and we're investigating a merge at the moment.

**Comment by kenwheeler** [comment]
@bebraw what about just including prism.js and calling highlightElement on mount?

**Comment by kenwheeler** [comment]
Done
