### ISSUE TITLE
Fix userTheme import

### ISSUE THREAD

**Issue by alex-saunders** [FormidableLabs/spectacle#737]
Currently (after #732 has landed), the theme is just being imported from `window.userTheme` and is explicitly set in the example `one-page.html`.
We should come up with a more solid solution that supports the CLI flow (allowing theme files to be pointed to via `--theme=path-to-theme.js` - most likely using an import alias like is currently done within task/rewrite) as well as being able to set it when consuming Spectacle via a custom webpack setup.

**Comment by ryan-roemer** [comment]
Fixed with refactor to take theme directly in deck props
