### ISSUE TITLE
export&print does not use theme font

### ISSUE THREAD

**Issue by lambdafu** [FormidableLabs/spectacle#768]
I just created my first presentation following the instructions using the classic boilerplate, and tried the export-and-print option. What I noticed is that the font changed from Montserrat to Open Sans Condensed compared to just the export option or using the normal presentation mode. It seems that the createTheme() function adjusts the screen CSS but not the print CSS. This could mess with the layout of slides, so in my opinion both fonts should be set to Montserrat.

**Comment by kale-stew** [comment]
Thank you for opening this issue, @lambdafu -- I believe we have fixed this in [v6](https://github.com/FormidableLabs/spectacle/tree/task/rewrite), which will be released shortly. 🙂
