### ISSUE TITLE
Allow <Appear> to specify order of appearance

### ISSUE THREAD

**Issue by garetht** [FormidableLabs/spectacle#77]
Currently, navigating through slides causes elements wrapped in `<Appear>` to reveal themselves in (I think) source order. `<Appear>` can be made to take an `order` or similar prop that takes an integer, allowing the order of appearance of the elements to be controlled.

**Comment by pedrottimark** [comment]
@kenwheeler In the default deck, `Appear` components have `fid` props, but they are ignored, true?

Would you like me to push an `appear-77` branch to my fork, so you can review some minimal changes for an optional `order` prop in the `Appear` component as described below?

@garetht What do you think about a close analogy to the `order` attribute in CSS flexbox?
http://www.w3.org/TR/css3-flexbox/#order-property

1. It has a number value. Negative values are okay.
2. The default value is zero if the prop is unspecified.
3. The `Appear` components on a slide become visible in ascending order. Document order is the tie-breaker for components which have the same order. Therefore, if no `Appear` components have `order` props, the default is current behavior.

**Comment by kenwheeler** [comment]
Can you do that one separately

**Comment by pedrottimark** [comment]
Yes, on a branch from the current master. Only 3 files will have changes:
index.js (remove fid prop from default deck and add a few slides with order prop)
src/components/appear.js
src/components/slide.js

**Comment by garetht** [comment]
@pedrottimark That sounds great to me - thanks for looking at it!

**Comment by pedrottimark** [comment]
@kenwheeler https://github.com/pedrottimark/spectacle/tree/appear-77

**Comment by AndersDJohnson** [comment]
@pedrottimark @kenwheeler @garetht Any update on this feature? Really need it.

**Comment by kenwheeler** [comment]
Done!
