### ISSUE TITLE
Incoming live demo deck update regarding disappearing white icons?

### ISSUE THREAD

**Issue by nosrac77** [FormidableLabs/spectacle#779]
### Question

Is there an incoming update for the live demo deck regarding the disappearing white arrow/full-screen icons on slides 8 and 15 (see attached screenshots)?

### Background Info/Attempts

Navigating to the Spectacle Github Repo and clicking the [live demo](https://raw.githack.com/FormidableLabs/spectacle/master/one-page.html#/) link on the master branch's README.md using Mozilla Firefox 71.0 on Ubuntu 18.04

The 8th and 15th slides have white backgrounds that cause all white icons to disappear in both regular and full-screen modes. No reduced functionality as the buttons are still clickable, it just looks odd to see them disappear and also makes them harder to find when using a mouse.

![8th_slide_spectacle](https://user-images.githubusercontent.com/26493435/70762889-202cb980-1d07-11ea-9451-18cb75a9e18e.png)
![15th_slide_spectacle](https://user-images.githubusercontent.com/26493435/70762895-2458d700-1d07-11ea-8ec1-3c630051f6fb.png)

**Comment by ryan-roemer** [comment]
We're almost complete with our [top-to-bottom rewrite](https://github.com/FormidableLabs/spectacle/tree/task/rewrite)! The new live preview site is available at: https://spectacle.formidable.com/ (built off https://github.com/FormidableLabs/spectacle/tree/task/rewrite/examples/js)

**Comment by kale-stew** [comment]
@nosrac77 closing as this question has been answered - feel free to reopen if you would like to discuss requests for our rewrite, or feel free to open a PR against the latest to add them back. 🙂
