### ISSUE TITLE
Update the version of react-live

### ISSUE THREAD

**Issue by alonjupiter** [FormidableLabs/spectacle#781]
### Description

The currently used `react-live` version is 1.6 that depends on `create-react-context` version 0.2.3, which isn't MIT licensed.

This nested dependency is a blocker for installing and using Spectacle in corporate environments and build systems.

### Proposal

Update `react-live` to v2.1.2 or above, which downgraded its `create-react-context` to 0.2.2 that is MIT licensed.

### Links / References

Reference to this issue in the `react-live` repository: https://github.com/FormidableLabs/react-live/pull/147

**Comment by kale-stew** [comment]
Closed by #800

**Comment by kale-stew** [comment]
@alonjupiter this is now fixed in [v5.8.0](https://github.com/FormidableLabs/spectacle/releases/tag/v5.8.0)! Thanks for bringing it to our attention.
