### ISSUE TITLE
Twitter Embed Tag

### ISSUE THREAD

**Issue by ivanoats** [FormidableLabs/spectacle#79]
I'm thinking about writing a tweet embed tag based on this SO answer:
http://stackoverflow.com/questions/25234101/how-to-integrate-the-twitter-widget-into-reactjs

Would the src/image.jsx be a good thing to base it on? Is this something you'd be interested in including?

**Comment by kenwheeler** [comment]
Yeah that would be awesome. I mean, you can embed now, but if you wanted to make it super easy, do like `<Tweet id=""/>` or `<Tweets user="ken_wheeler"/>`

**Comment by ivanoats** [comment]
Thanks, actually using the official docs here: https://dev.twitter.com/web/embedded-tweets/javascript-create. I will submit a PR linked to this issue.

**Comment by ivanoats** [comment]
I am having trouble getting the twttr script to load.. any comments on the approach I am taking? 
https://github.com/ivanoats/spectacle/blob/tweet/src/tweet.jsx#L13

The easy answer would be to just include it in the site template.. https://github.com/ivanoats/spectacle/blob/tweet/themes/default/html.js ?

**Comment by KyleAMathews** [comment]
I added the script @ivanoats suggested to html.js. I also needed to make a mini Tweet component to run `twttr.widgets.load()` in `componentDidMount`.

**Comment by kenwheeler** [comment]
I'm gonna go ahead and close this one. It's the sort of thing someone can just add to a slide and I'm not sure it should be in core

**Comment by ivanoats** [comment]
@KyleAMathews could you share your code where you did that as an example please?

**Comment by KyleAMathews** [comment]
@ivanoats 

Add this to your HTML file:

```javascript
      <script>window.twttr = (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0],
          t = window.twttr || {};
        if (d.getElementById(id)) return t;
        js = d.createElement(s);
        js.id = id;
        js.src = "https://platform.twitter.com/widgets.js";
        fjs.parentNode.insertBefore(js, fjs);
        t._e = [];
        t.ready = function(f) {
          t._e.push(f);
        };
        return t;
      }(document, "script", "twitter-wjs"));</script>
```

Then this is the component:

```javascript
const Tweet = React.createClass({

  componentDidMount() {
    twttr.widgets.load()
  },

  render() {
    return (
      <blockquote className="twitter-tweet">
        {this.props.children}
      </blockquote>
    )
  }
})
```
