### ISSUE TITLE
Infra: Deploy docs to production

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/spectacle#793]
- [x] deploy a staging build to surge.
- [x] Enable testing deployment to `open-source/spectacle-TODO-TESTING` and deploy. Verify site (will have broken code, just check files are there).
- [x] Ticket out and prepare `formidable.com` repository to exclude `open-source/spectacle-TODO-TESTING`. Should _not_ overwrite `open-source/spectacle-TODO-TESTING`.
- [x] Enable production deployment to real `open-source/spectacle` and deploy. Verify site (should completely work).
- [x] Ticket out and prepare `formidable.com` repository to exclude `open-source/spectacle`.  Should _not_ overwrite `open-source/spectacle`. Should remove testing `open-source/spectacle-TODO-TESTING`.

**Comment by boygirl** [comment]
@ryan-roemer would it make sense to include a CI step on PR that produces some staging site that wont have broken code so folks can take a look before deploying? Maybe create the staging build deploy to surge? Or does this seem like overkill to you?

**Comment by ryan-roemer** [comment]
Yeah, we can hook up surge. Maybe I’ll do that in a follow on PR so I can test the deploy code dry run in this Pr?

**Comment by kale-stew** [comment]
Closed by #797 🎉
