### ISSUE TITLE
Main README has broken documentation links

### ISSUE THREAD

**Issue by fzembow** [FormidableLabs/spectacle#801]
Great project, I managed to put together a nice presentation with embedded demos very easily!

FYI: The README on https://github.com/FormidableLabs/spectacle has all broken links. For example the Deck link 404s to https://github.com/FormidableLabs/spectacle/blob/master/docs/tag-api.md#deck

Not sure if they're meant to link to markdowns on github or to the actual documentation site

**Comment by kale-stew** [comment]
Looks like we forgot to update the dir path when we moved all of our docs into a sub-folder ~1 week ago. Thanks for bringing this up, @fzembow, I'll PR a fix now.
