### ISSUE TITLE
Update to work with react 0.14.0-rc1 and react-router 1.0.0-rc1

### ISSUE THREAD

**Issue by jimpick** [FormidableLabs/spectacle#81]
I'm trying to embed a presentation into another project, so I needed to update the dependencies to match. As new version of react and react-router will be out soon, I hope this is useful.

I'm attaching pull request #80 with my fixes.

**Comment by kenwheeler** [comment]
Awesome, I'm going to try and find and fix any errors, and merge when both of them are officially released.

**Comment by kenwheeler** [comment]
Closing, opening a migration to 0.14 ticket now that it's been released
