### ISSUE TITLE
Docs: Revise "deploy" section?

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/spectacle#811]
Maybe we consider removing / replacing `Deploying with Github Pages` section at http://127.0.0.1:3000/docs/advanced-concepts/#deploying-with-github-pages

There seem to be a lot of undocumented assumptions about how you integrated your spectacle presentation and there are lots of deploy options. Might be better to do a `spectacle-boilerplate`-based deployment tutorial? (Or do that in `spectacle-cli` repo instead?)

**Comment by kale-stew** [comment]
I think I would prefer to make a boilerplate-based deployment tutorial, I can wrap it into my current Tutorial work

**Comment by kale-stew** [comment]
Closed by #837
