### ISSUE TITLE
Docs/Bug: Fences code blocks have top/bottom lines.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/spectacle#812]
We have a `json` code block that in dev shows top/bottom lines in a fences code block that look like they should only be for inline code snippets:

![Screen Shot 2020-01-22 at 12 20 38 PM](https://user-images.githubusercontent.com/445557/72930909-c9f16400-3d11-11ea-9063-201673aff7fe.png)

**Comment by kale-stew** [comment]
Repro notes:

This is only happening to formatted (indented and part of a numbered list) code blocks, all else have been fixed in recent PRs: see `.../docs/tutorial/#option-one-using-a-standard-react-based-web-app`
