### ISSUE TITLE
Alternative to Presentation API and Cast

### ISSUE THREAD

**Issue by migh** [FormidableLabs/spectacle#819]
### Question

Will there be an alternative to use the Presentation API to cast for the rewrite?

### Background Info/Attempts

I create a project using spectacle boilerplate with the MDX mode and automatically installed the v6.0.0-alpha3, I think it is really nice, but still missing documentation. After searching in the code I saw how to use the presenter mode, but I was not able to find a way to use it with two tabs as it was in the past, without casting.

**Comment by kale-stew** [comment]
Thanks for bringing up this issue, @migh - we've fixed this in #841, you should have no problem syncing slides between two tabs and documentation has been updating accordingly.
