### ISSUE TITLE
Shortlist component

### ISSUE THREAD

**Issue by MarkRedeman** [FormidableLabs/spectacle#82]
I noticed that I often use short lists without additional markup. For these cases writing `<List><ListItem>statment 1</ListItem><ListItem>statement 2</ListItem>{/* etc */}</List>` can be a bit tedious.

I've written a small component `<ShortList items={["Statement 1", "Statement 2", "etc"]} />` so that I don't have to repeat writing `<ListItem>`s. Would a pull request for this be appreciated?

---

You could similarly also make a `ShortTable` component with the following interface:

```
<ShortTable 
    headers={[
        "Package", "LC", "MSI", "MCC", "CCM", "Execution"
    ]}
    items={[
        ["carbon/carbon", "61%", "95%", "100", "95%", "2.25m",]
        ["symfony/event-dispatcher", "85%", "54%", "69%", "78%", "20s",]
        ["hylianshield/validator", "100", "75%", "89%", "85%", "1.35m",]
        ["mathiasverraes/money", "96%", "92%", "100", "92%", "16.9s",]
        ["thephpleague/fractal", "98%", "84%", "98%", "85%", "31s",]
        ["broadway/broadway-demo", "96%", "88%", "92%", "86%", "5s",]
        ["broadway/broadway", "57%", "49%", "56%", "87%", "46s",]
    ]}
/>
```

I think this is a lot more easy to work with than all of the `<TableRow>` tags etc. but it does have the disadvantage that stying the table can be a bit more tricky.

**Comment by bebraw** [comment]
That looks good to me. I think you could reuse the current table implementation behind a facade like that somewhat easily.

**Comment by kenwheeler** [comment]
Would love a PR for this stuff
