### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by kevinsimper** [FormidableLabs/spectacle#83]
Are you suppose to git clone this project?

That just seems inefficient, if you don't want the git history of this project, but want to commit it yourself.

Is there a plan to release this as a module?

**Comment by kenwheeler** [comment]
Working on it. Git clone seemed like the best way to go about it, because you'll inevitably want to edit the theme, but when I upgrade for 0.14 I'll likely separate the core modules as npm installable and then get a generator set up for the rest.

**Comment by ryan-roemer** [comment]
In the meantime while @kenwheeler works out the official path, I've got an example repo with an NPM install of spectacle and a custom theme at: https://github.com/ryan-roemer/surge2015

Hope that helps!

**Comment by kevinsimper** [comment]
I git clone it and was working right away :+1: 

Spectacle has been by far the best experience for creating a presentation! This is super awesome! :dancers:

**Comment by kenwheeler** [comment]
@kevinsimper Thats awesome! We're working on making it clearer moving forward and removing even more friction to getting started.

**Comment by kevinsimper** [comment]
@kenwheeler Is there a issue for that?

**Comment by kenwheeler** [comment]
https://github.com/FormidableLabs/spectacle/issues/27 @kevinsimper
