### ISSUE TITLE
Docs: Upgrade to react-static v^7

### ISSUE THREAD

**Issue by kale-stew** [FormidableLabs/spectacle#838]
We should upgrade to react-static v7 to reinstate hot-reloading to make doc development less painful.

There are a number of [breaking changes](https://github.com/react-static/react-static/blob/master/CHANGELOG.md#breaking-changes) we'll need to address upgrading from v5.9.12, including upgrading babel and deprecating our use of a couple plugins.

This should be considered a future improvement we can implement after the v6 release.

**Comment by boygirl** [comment]
@kale-stew urql recently migrated to react-static 7 and created a plugin to assist with creating docs routes from .md. You can pattern off that work: https://github.com/FormidableLabs/urql/tree/master/packages/site
