### ISSUE TITLE
Fullscreen button component

### ISSUE THREAD

**Issue by zpao** [FormidableLabs/spectacle#85]
It would be great to have some (built-in) way to trigger the [fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API) so that you can completely hide the browser chrome when giving a presentation. My initial thoughts on how to support this would just be a button that you can throw on the first slide (maybe the default theme has that positioned in a corner with visibility:hidden so you can still hover it to click).

**Comment by mathieudutour** [comment]
View -> Enter Presentation Mode ?

**Comment by kenwheeler** [comment]
Yeah that'd be helpful, maybe use mouse movement to trigger the opacity on it, have the screen toggle fixed position in the corner

**Comment by zpao** [comment]
@mathieudutour We don't all use Chrome 😛 (also, I don't see presentation mode in Chrome anymore but maybe my config is screwed up).

@kenwheeler Exactly what I was thinking (not really sure why I said visibility:hidden, I totally meant opacity for a nice fade in).

**Comment by kenwheeler** [comment]
@zpao if you're on master, hovering in the bottom right corner brings the button up. 1.0.0 release w/ docs to this effect is forthcoming.

**Comment by zpao** [comment]
🎉
