### ISSUE TITLE
How to use a background image for slides in v6?

### ISSUE THREAD

**Issue by migh** [FormidableLabs/spectacle#851]
### Question

How to use a background image for slides in v6?

### Background Info/Attempts

I've been trying to transition to v6, one thing I've not been able to do is to add a background image to the SlideContainer Component. I am using spectacle-boilerplate and mdx mode.

**Comment by ryan-roemer** [comment]
There's a PR open right now for background images: https://github.com/FormidableLabs/spectacle/pull/849

**Comment by kale-stew** [comment]
Closed by #849 👍
