### ISSUE TITLE
Unable to Update FontSize in CodePane

### ISSUE THREAD

**Issue by forrest-akin** [FormidableLabs/spectacle#874]
react : 6.13.1
spectacle : 6.0.1

CodePane doesn't respond to changes in `fontSize` if `themeContext.fontSizes.monospace` exists. The expected strategy for determining `fontSize` is the first of `props.fontSize`, `themeContext.fontSizes.monospace`, `15` (default value).

Please see this [CodeSandbox](https://codesandbox.io/s/unable-to-update-fontsize-in-codepane-874-ukn65) I've prepared demonstrating this issue.

**Comment by kale-stew** [comment]
I agree, it makes the most sense to determine CodePane font size in this order:
1. Check for `props.fontSize`
2. Check for `themeContext.fontSizes.monospace`
3. Default to `15px`

I've opened [a PR](https://github.com/FormidableLabs/spectacle/pull/875) to fix this. Thank you for bringing it to our attention. 😀
