### ISSUE TITLE
Bug: Links break with internal navigation stuff.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/spectacle#878]
I looked into some of the links at issue in https://github.com/FormidableLabs/spectacle/pull/877 and found there's something weird going on with routing:

## A working example

- Open new browser tab to: https://formidable.com/open-source/spectacle/docs/tutorial/
- Search for "For more information on presenting" and click the `presenting` link.
- **Result**: Navigates to `https://formidable.com/open-source/spectacle/docs/basic-concepts/#presenting` in browser URL and we get a working page. 🎉 

## A broken example
- Open new browser tab to: https://formidable.com/open-source/spectacle
- Find and click `DOCS` link.
- Find and click `Tutorial` in sidenav.
- Search for "For more information on presenting" and click the `presenting` link.
- **Result**: Navigates to `https://formidable.com/docs/basic-concepts#presenting` in browser URL which doesn't exist (below spectacle sub-app dir) and we get a 404. 😿 

I'm guessing this applies to other links as well (this is the one I checked).

**Comment by kale-stew** [comment]
@boygirl fixed this by removing/rewriting the `relative` fn we had determining our relative paths in the rewritten docs. When we re-release that react-static update, we should solve this issue.

**Comment by kale-stew** [comment]
Closed by #885
