### ISSUE TITLE
Markdown component does not seem to work correctly

### ISSUE THREAD

**Issue by on3iro** [FormidableLabs/spectacle#887]
### Describe Your Environment

What version of Spectacle are you using? **6.0.2**

What version of React are you using? **16.13.1**

What browser are you using? **Firefox Developer Edition**

What machine are you on? **Mac OSX**

### Describe the Problem

[Link to CodeSandBox](https://codesandbox.io/s/simple-spectacle-example-w0sgq?file=/src/index.js) (first slide)

**Expected behavior:**
According to the [docs](https://formidable.com/open-source/spectacle/docs/api-reference/#markdown) my markdown slide should be correct.
I would expect the slide to show a heading (lvl2) as well as an unordered list.

**Actual behavior:**
All children are simply rendered as a single unformated bulk of text.

<img width="837" alt="Screenshot 2020-04-23 at 09 59 34" src="https://user-images.githubusercontent.com/8681413/80074231-28b0be80-8549-11ea-8e8f-67b3c2ea00f1.png">

### Additional information
The CodeSandbox somehow formats my code upon saving (the fork seems to use prettier or something along those lines). This leads to a situation where all markdown is joined into a single line.

![Screenshot 2020-04-23 at 09 58 52](https://user-images.githubusercontent.com/8681413/80074159-0e76e080-8549-11ea-99ee-7816fb2a41b8.png)

 However the issue persists even if you start formatting the markdown correctly. This is how it looks in my editor:

![Screenshot 2020-04-23 at 09 57 57](https://user-images.githubusercontent.com/8681413/80074078-f1daa880-8548-11ea-8404-54c633986bb4.png)

**Comment by mAAdhaTTah** [comment]
You need to pass it in as a string, not just `children`:

```jsx
<Markdown>{`Your Markdown Here`}</Markdown>
```

![Screen Shot 2020-04-23 at 11 37 27 AM](https://user-images.githubusercontent.com/4371429/80118741-d70f3080-8556-11ea-992e-926782c14853.jpg)

**Comment by kale-stew** [comment]
^ what he said! I'll make sure this is properly documented, but you need to pass your Markdown content in as a template literal for it to render properly. 🙂

**Comment by on3iro** [comment]
Ah, I see. Thanks for the quick response. It would definitely be great if this was reflected inside the docs, as the markdown component is used without a template string there.
