### ISSUE TITLE
Access to old docs? Looking for pacman progress.

### ISSUE THREAD

**Issue by qodesmith** [FormidableLabs/spectacle#892]
### Question

The current docs point to the nice fancy website you guys have set up. Is there a way to get a version of the older docs? I'm looking to use the pacman progress but it doesn't look like v6 has it. I'd like to see the latest version of the ^5 docs. Thank you!

**Comment by kale-stew** [comment]
You can check out our old doc content by looking at the docs/content dir from the last released version pre-v6 in Github, [here](https://github.com/FormidableLabs/spectacle/tree/fa3a54fb7905f55b633a6dec28740a61985bf831/docs/content).

I tried to pull a webarchive link but the crawler did not play nicely with our CSS and the latest version I could find is nearly impossible to parse.

We do intend to re-introduce the pacman progress to v6, I am sorry it's lacking this feature for now!
