### ISSUE TITLE
The d.ts file needs minor fixes

### ISSUE THREAD

**Issue by ronarvaez** [FormidableLabs/spectacle#906]
In the d.ts file you can find a few wrong types and names.

**Expected behavior:**
- Deck's prop `animationsWhenGoingBack` is named correctly.
- Slide's `backgroundColor` has string type
- Slide's `backgroundImage` has string type
- Slide's `backgroundOpacity` has number type
- Slide's `backgroundPosition` has string type
- Slide's `backgroundRepeat` has string type
- Slide's `backgroundSize` has string type

**Actual behavior:** 
- Deck's `animationsWhenGoingBack` prop is named `animationsWhileGoingBack`
- The next Slide's props instead of typings have a reference to PropTypes:
  - backgroundColor
  - backgroundImage
  - backgroundOpacity
  - backgroundPosition
  - backgroundRepeat
  - backgroundSize

**Comment by kale-stew** [comment]
Thank you so much for not only bringing this to our attention, but immediately opening a PR to fix it. We appreciate you, Rodrigo!

Have released this fix in [v6.1.0](https://github.com/FormidableLabs/spectacle/releases/tag/v6.1.0)! If you update, types should work correctly now 👍
