### ISSUE TITLE
Export to PDF functionality

### ISSUE THREAD

**Issue by aristofanischionis** [FormidableLabs/spectacle#909]
### Question
According to the [docs](https://formidable.com/open-source/spectacle/docs/advanced-concepts/), if I have a spectacle presentation and I want to create the PDF version of it, I should just add ?exportMode=true after the url, like this: [http://localhost:3000/?exportMode=true](http://localhost:3000/?exportMode=true). So this could also work If I have another URL, let's say http://localhost:3000/present/username/title/?exportMode=true, where I render a Spectacle  
 `<Deck />`  ?

**Comment by kale-stew** [comment]
Yes, that should be the case! Should also work with hosted URLs, not just local ones.
