### ISSUE TITLE
Issue when building

### ISSUE THREAD

**Issue by kirilzh** [FormidableLabs/spectacle#910]
### Question

What should be the build configuration so that slides don't get merged into one?

### Background Info/Attempts

I'm importing an `slides.md` file that looks like

```md
# Hi 👋

---

# Under construction...
```

and I have it rendered like

```js
import * as React from 'react';
import { Box, Deck, FlexBox, Markdown, Progress } from 'spectacle';
import * as slides from './slides.md'

export const App = () => (
  <Deck
    transitionEffect="slide"
    template={() => (
      <FlexBox
        position="absolute"
        bottom={0}
        width={1}
      >
        <Box padding="1em">
          <Progress
            color="#CECECE"
            size={12}
          />
        </Box>
      </FlexBox>
    )}
  >
    <Markdown containsSlides>
      {slides}
    </Markdown>
  </Deck>
);
```
It works as expected running the on my dev server. However, when I build the project everything is loaded on one slide. I'm loading `.md` files using html-loader

```
module: {
  rules: [
    { 
      test: /\.md$/,
      use: [ 'html-loader' ]
    }
  ]
} 
```

could this be the problem?

**Comment by ryan-roemer** [comment]
Hi @kirilzh !

Checkout our MD examples with a webpack config. In your case I've highlighted the lines where we use `raw-loader`: https://github.com/FormidableLabs/spectacle/blob/master/examples/md/webpack.config.js#L18-L21

**Comment by kale-stew** [comment]
Bumping this - @kirilzh are you still having an issue?

We have updated the default branch name since @ryan-roemer's comment above, so if you're looking for the functioning link of that example, here it is: https://github.com/FormidableLabs/spectacle/blob/main/examples/md/webpack.config.js.

Closing for now but happy to re-open if this is still a problem for you!
