### ISSUE TITLE
Code highlighting not working when returning to previous slide

### ISSUE THREAD

**Issue by JiDai** [FormidableLabs/spectacle#918]
### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://www.github.com/FormidableLabs/spectacle/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the [docs](https://www.formidable.com/open-source/spectacle/docs) before asking a question
- [x] I am using the latest version of Spectacle

### Describe Your Environment

What version of Spectacle are you using?
spectacle@6.1.0

What version of React are you using?
react@16.13.1

What browser are you using?
Firefox/Chrome

What machine are you on?
OSX

### Describe the Problem
When I back to the previous slide the code block does not scroll to the right line but stay at top of the frame. On my example It works once but after second back, the problem appears. On my project it happens at first back. It seems happens with long code when highlighting a bottom line.

https://codesandbox.io/s/spectacle-code-scroll-problem-m9yi5

**Expected behavior:** [What you expect to happen]
Code block scrolls at the right code line

**Actual behavior:** [What actually happens]
Code block scrolls to the top

**Comment by JiDai** [comment]
I use the `Stepper` component as a workaround.

```
<Stepper values={[[56, 65], [58, 58], [64, 64]]} defaultValue={[]}>
      <CodePane
        language="js"
        autoFillHeight
        highlightStart={value[0]}
        highlightEnd={value[1]}
      >
          {longCode}
      </CodePane>
</Stepper>
```

Besides, the `defaultValues` prop is mandatory to prevent an error `value is undefined`

**Comment by kale-stew** [comment]
Can verify this bug, but it does appear to function as expected if you navigate backwards _slowly_. 
If I wait 2 seconds before hitting navigating to the previous slide, it jumps to the correct line, even without use of `Stepper`. 🤔 Still, not ideal behavior - going to look into this further.

**Comment by chrisipanaque** [comment]
Verified that issue has already been fixed in upcoming v7! 🥳 🎉 

![1198-fix](https://user-images.githubusercontent.com/16032631/98879838-4a1cbd80-243b-11eb-9ec5-0c5dd6105715.gif)

**Comment by fritz-c** [comment]
Confirmed as fixed. Demo here: https://codesandbox.io/s/spectacle-code-scroll-problem-forked-ldms7y?file=/src/index.js
