### ISSUE TITLE
Build error, 'ERROR in ./index.jsx'

### ISSUE THREAD

**Issue by peterobrien** [FormidableLabs/spectacle#93]
Was getting the following error on your master branch

```
ERROR in ./index.jsx
Module not found: Error: Cannot resolve module 'node_modules/webpack/buildin/module.js' in /Users/pob/WebstormProjects/spectacle
 @ ./index.jsx 1:0-49
```

Did a blunt fix by changing package's devDependencies to specify versions to most recent patch release and sent you a pull request https://github.com/FormidableLabs/spectacle/pull/92 

You may of course want to fix it in a more intelligent way though...

**Comment by kenwheeler** [comment]
Getting #90 in, fixing some small stuff prior, should fix this
