### ISSUE TITLE
Overview mode is not working

### ISSUE THREAD

**Issue by davidpham87** [FormidableLabs/spectacle#931]
# How to reproduce the bug

Open the spectacle presentation (https://raw.githack.com/FormidableLabs/spectacle/main/examples/one-page.html?slide=0&slideElement=-1) and then hit alt/cmd + o.

# Expected outcome

We should the all the slide, but we only see the last one.

**Comment by will-hart** [comment]
Is this related https://github.com/FormidableLabs/spectacle/issues/888?

**Comment by davidpham87** [comment]
Yes probably.

**Comment by gingerrific** [comment]
@davidpham87 this is now resolved in v7! Enabling overview mode with either the key command or the queryParam `overviewMode=true` will display all slides in an overview mode

**Comment by soft-circles** [comment]
We believe this issue has been addressed in 8.0.0 and later, if this issue persists please feel free to open a new issue.
