### ISSUE TITLE
How can I make the CodeBlock Larger?

### ISSUE THREAD

**Issue by birdiesanders** [FormidableLabs/spectacle#939]
### Question

What question do you have about using Spectacle?

I cannot seem to make the code block larger, it is just too short for what I need, and the notes tend to cover up a line or two of what I am showing. 
### Background Info/Attempts

Any background information that might help us answer your questions, or a code snippet or link to a code example if you have an implementation question.

**Comment by dephiros** [comment]
I ended up looking through the source code and found you can override the theme:
```
const theme = {
  size: {
    maxCodePaneHeight: 600
  }
};
// ...
    <Deck theme={theme}>
```
I think spectacle do a deep merge with the [default theme](https://github.com/FormidableLabs/spectacle/blob/main/src/theme/default-theme.js)

Hope it helps

**Comment by erin-doyle** [comment]
This is massively helpful!  It would be great if this were pointed out better in the docs!

**Comment by kale-stew** [comment]
@dephiros - thanks for taking the time to look at the source and confirm that this is possible.

@erin-doyle - we do have a [page about theming in the docs themselves](https://formidable.com/open-source/spectacle/docs/themes/#theme-object), I would love feedback on how we can make the language more clear around this, if you have the time to spare.

**Comment by kale-stew** [comment]
Closing in favor of the `maxCodePaneHeight` override provided above. Please feel free to re-open this issue if the problem persists.
