### ISSUE TITLE
Adding new language to CodePane

### ISSUE THREAD

**Issue by dephiros** [FormidableLabs/spectacle#943]
### Question

What question do you have about using Spectacle?
How to add a new language for highlight? 

### Background Info/Attempts
I want to add a kotlin codeblock
I tried a solution in https://github.com/FormidableLabs/prism-react-renderer#faq but does not seems to work

**Comment by kale-stew** [comment]
Hi @dephiros - unfortunately, `prismjs` doesn't currently support Kotlin syntax, and we cannot easily add an extension to the lib to support an unsupported language. I know this isn't what I would want to hear as a potential contributor and I would like to apologize for that.

If this is a feature you can afford to spend time on, I would encourage you to PR [`prismjs` itself](https://github.com/PrismJS/prism) for support of Kotlin, as I feel this would be a language used by many consumers of the library, not unlike ourselves.

**Comment by dephiros** [comment]
@kale-stew , thanks for your response. I see that prism list Kotlin as a supported language in https://prismjs.com/index.html#supported-languages
