### ISSUE TITLE
Long frames

### ISSUE THREAD

**Issue by kevinsimper** [FormidableLabs/spectacle#95]
There is a problem with long frames which causes jank.

I am on a Macbook Pro, and this is from switch from page one to two on demo presentation.

Any also tried that?

![image](https://cloud.githubusercontent.com/assets/1126497/11035404/aaba48b0-86f2-11e5-95a4-6bae97c8569e.png)

**Comment by kenwheeler** [comment]
From an initial inspection, it looks like the thats coming from the routing hash change. Does anyone see anything else there that could be the culprit?

**Comment by kevinsimper** [comment]
I tried to update all the dependencies, because I did also find that it was Reac-router that caused the delay but then Radium seemed to break.

**Comment by kenwheeler** [comment]
I have the 0.14 update branch coming in probably today, so after thats in I'll see if I can isolate and fix this issue.

**Comment by knowbody** [comment]
this also seems to be resolved @kenwheeler

**Comment by kevinsimper** [comment]
Still seeing it in the latest master
![image](https://cloud.githubusercontent.com/assets/1126497/11502335/77ca47da-983a-11e5-8135-4ab27dbb9667.png)

**Comment by kenwheeler** [comment]
@kevinsimper have you built using the production flag?

**Comment by kevinsimper** [comment]
No, but why should that make a difference? :)

It seems that the build info in README is not up to date

**Comment by kevinsimper** [comment]
The production flag is confusing as running `npm run build:dist` builds the js file, but `npm start` does not seem to have a config to serve that dist.
