### ISSUE TITLE
Problems formatting a FlexBox with 2 columns and Text

### ISSUE THREAD

**Issue by Zenahr** [FormidableLabs/spectacle#953]
### Question

What is the best way (any Best Practices applicable here?) for displaying a comparison table?

This is what it looks like right now

![image](https://user-images.githubusercontent.com/47085752/95227223-247a1400-07fe-11eb-8dc5-99a25996c675.png)

The titles are not exactly aligned in the center of their boxes. Should I use a "Spacer" element between them instead of using margins?

My list of items will be uneven. Meaning one column might have less elements than the other. In my current layout, this leads to uneven spacing inside the columns

![image](https://user-images.githubusercontent.com/47085752/95227625-9e120200-07fe-11eb-9838-b31cc7834c60.png)

### Background Info/Attempts

This is the code to this:

```js
<Slide>
    <FlexBox>
    <Box marginRight="180px">
      <Heading>SOME TITLE</Heading>
    </Box>
    <Box  marginLeft="180px">
      <Heading>SOME OTHER TITLE</Heading>
    </Box>
    </FlexBox>

  <FlexBox>
    <Box marginRight="180px">
      <Appear elementNum={0}><Text>lorem</Text></Appear>
      <Appear elementNum={2}><Text>lorem</Text></Appear>
      <Appear elementNum={4}><Text>lorem</Text></Appear>
      <Appear elementNum={6}><Text>lorem</Text></Appear>
    </Box>

    <Box  marginLeft="180px">
    <Appear elementNum={1}><Text>lorem</Text></Appear>
    <Appear elementNum={3}><Text>lorem</Text></Appear>
    <Appear elementNum={5}><Text>lorem</Text></Appear>
    <Appear elementNum={7}><Text>lorem</Text></Appear>
    <Appear elementNum={9}><Text>lorem</Text></Appear>
    </Box>
  </FlexBox>
</Slide>

```

This is the theme and template that I'm using on my deck:

```js

const theme = {
  fonts: {
    header: '"Open Sans Condensed", Helvetica, Arial, sans-serif',
    text: '"Open Sans Condensed", Helvetica, Arial, sans-serif',
    transitionEffect: 'slide'
  }
};

const template = () => (
  <FlexBox
    justifyContent="space-between"
    position="absolute"
    bottom={0}
    width={1}
  >
    <Box padding="0 1em">
      <FullScreen />
    </Box>
    <Box padding="1em">
      {/* <Progress /> */}
    </Box>
  </FlexBox>
);


```
### Further Notes

Another thing I tried to do is lowering the top-bottom margins of the Text components inside the Boxes using margin="0" but that didn't do anything. Am I missing something here? That's just another small problem I'm having.

**Comment by sneakers-the-rat** [comment]
use <Grid> and if you have uneven numbers just use a placeholder `<></>` 

if all your text objects were guaranteed to be the same number of lines, then rather than <Box> use another <FlexBox> and make sure that `flexDirection="column"` and you align the content to flex-start
