### ISSUE TITLE
Favicon being loaded on every transition

### ISSUE THREAD

**Issue by davidkpiano** [FormidableLabs/spectacle#96]
If you take a look at the network requests, it seems the `favicon.ico` is being loaded for every single slide, even if you go back to a previously-viewed slide. I'd expect the `favicon.ico` to load only once. Seems like a minor issue, but hopefully it's not a symptom of a larger issue.

**Comment by kenwheeler** [comment]
I would assume it probably has something to do with hash url navigation? I'll look into it.

**Comment by knowbody** [comment]
It seems like this is resolved, at least I can't reproduce it anymore.
