### ISSUE TITLE
Does false differ from undefined for boolean base style props?

### ISSUE THREAD

**Issue by pedrottimark** [FormidableLabs/spectacle#97]
For example, in the default theme, heading styles include fontWeight: "bold" and besides, that is in default formatting of the HTML elements h1, h2, h3, h4, h5, h6.

Should a false value of the bold prop for a Heading component mean this instance is not bold?

In the current logic of getStyles in base.jsx, false has same (non) effect as undefined.

Depending on the intended meaning, the logic might become something like:

if (typeof this.props.italic === "boolean") {
  styles.fontStyle = this.props.italic ? "italic" : "normal";
}
if (typeof this.props.bold === "boolean") {
  styles.fontWeight = this.props.bold ? "bold" : "normal";
}
if (typeof this.props.caps === "boolean") {
  styles.textTransform = this.props.caps ? "uppercase" : "none";
}

Missed this the first time around because in my deck, I defined font-weight: "normal" in my theme; missed it the second time around in unit tests for style refactoring, hit it while writing a "tricky" deck to find any misunderstandings I have about effects of theme, base props, specific props, style prop, default element formatting, and inherited formatting.

**Comment by kenwheeler** [comment]
Good catch, can you PR this after I merge the 0.14 PR? I just figured out the last bug on that one, so its going in today

**Comment by pedrottimark** [comment]
Yes, thank you for giving me the opportunity. It will be my third PR total in open source, first with JavaScript code.

**Comment by kenwheeler** [comment]
you found it , you get the credit dude :)
