### ISSUE TITLE
Touch control for mobile device is not working

### ISSUE THREAD

**Issue by iot-art** [FormidableLabs/spectacle#984]
Hi! Earlier, you wrote that the touch control function for mobile devices has been added. But in the new version, changed 10 days ago, this feature is again missing:( How can I add this functionality to a presentation? Do you plan to return it?

**Comment by nonoumasy** [comment]
Same issue here. I can't seem to navigate by Touch(slide, click) on mobile.

**Comment by carlos-kelly** [comment]
Addressed in spectacle@8.0.1.
